// Code generated by kanon. DO NOT EDIT.
// source: fixed.go

//kanon:numbers Fixed Int32=1 Int64=2 Uint32=3 Uint64=4 Level=5 Size=6

package slice

import (
	"io"
	"slices"

	"go.thesmos.sh/kanon"
	"go.thesmos.sh/kanon/wire"
)

// The file compiles against a runtime that supports version 2 of the generator.
const (
	_ = kanon.EnforceVersion(2 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 2)
)

// The generated types implement kanon.Cloner.
var (
	_ kanon.Cloner[Fixed] = (*Fixed)(nil)
)

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Fixed) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if len(m.Int32) > 0 {
		n += 1 + wire.SizeBytes(len(m.Int32)*4)
	}
	if len(m.Int64) > 0 {
		n += 1 + wire.SizeBytes(len(m.Int64)*8)
	}
	if len(m.Uint32) > 0 {
		n += 1 + wire.SizeBytes(len(m.Uint32)*4)
	}
	if len(m.Uint64) > 0 {
		n += 1 + wire.SizeBytes(len(m.Uint64)*8)
	}
	if len(m.Level) > 0 {
		n += 1 + wire.SizeBytes(len(m.Level)*4)
	}
	if len(m.Size) > 0 {
		n += 1 + wire.SizeBytes(len(m.Size)*8)
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer.
// The error is always nil.
func (m *Fixed) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. The error is always nil.
func (m *Fixed) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if len(m.Size) > 0 {
		i -= _fixed_putSliceSize(buf[:i], m.Size)
		i = wire.PutTag(buf, i, 6<<3|wire.Bytes)
	}
	if len(m.Level) > 0 {
		i -= _fixed_putSliceLevel(buf[:i], m.Level)
		i = wire.PutTag(buf, i, 5<<3|wire.Bytes)
	}
	if len(m.Uint64) > 0 {
		i -= _fixed_putSliceUint64(buf[:i], m.Uint64)
		i = wire.PutTag(buf, i, 4<<3|wire.Bytes)
	}
	if len(m.Uint32) > 0 {
		i -= _fixed_putSliceUint32(buf[:i], m.Uint32)
		i = wire.PutTag(buf, i, 3<<3|wire.Bytes)
	}
	if len(m.Int64) > 0 {
		i -= _fixed_putSliceInt64(buf[:i], m.Int64)
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if len(m.Int32) > 0 {
		i -= _fixed_putSliceInt32(buf[:i], m.Int32)
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. The error
// is always nil.
func (m *Fixed) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	m.encodeKanon(out)
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. The error is always nil.
func (m *Fixed) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which do not copy data, since Fixed contains no string.
func (m *Fixed) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Fixed) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := "", opts.Offset
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Fixed) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := "", opts.Offset
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Fixed
// call it.
func (m *Fixed) decodeKanon(data []byte, slab string, off, depth int) error {
	m.Int32 = m.Int32[:0]
	m.Int64 = m.Int64[:0]
	m.Uint32 = m.Uint32[:0]
	m.Uint64 = m.Uint64[:0]
	m.Level = m.Level[:0]
	m.Size = m.Size[:0]
	return m.mergeKanon(data, slab, off, depth)
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Fixed
// call it.
func (m *Fixed) mergeKanon(data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "Fixed", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Fixed.Int32", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Fixed.Int32", 1, off+i)
			}
			i += n
			if err := _fixed_readSliceInt32(&m.Int32, data[i:i+int(l)], slab, off+i, depth-1, "Fixed.Int32", 1); err != nil {
				return err
			}
			i += int(l)
		case 2:
			if tag != 2<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Fixed.Int64", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Fixed.Int64", 2, off+i)
			}
			i += n
			if err := _fixed_readSliceInt64(&m.Int64, data[i:i+int(l)], slab, off+i, depth-1, "Fixed.Int64", 2); err != nil {
				return err
			}
			i += int(l)
		case 3:
			if tag != 3<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Fixed.Uint32", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Fixed.Uint32", 3, off+i)
			}
			i += n
			if err := _fixed_readSliceUint32(&m.Uint32, data[i:i+int(l)], slab, off+i, depth-1, "Fixed.Uint32", 3); err != nil {
				return err
			}
			i += int(l)
		case 4:
			if tag != 4<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Fixed.Uint64", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Fixed.Uint64", 4, off+i)
			}
			i += n
			if err := _fixed_readSliceUint64(&m.Uint64, data[i:i+int(l)], slab, off+i, depth-1, "Fixed.Uint64", 4); err != nil {
				return err
			}
			i += int(l)
		case 5:
			if tag != 5<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Fixed.Level", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Fixed.Level", 5, off+i)
			}
			i += n
			if err := _fixed_readSliceLevel(&m.Level, data[i:i+int(l)], slab, off+i, depth-1, "Fixed.Level", 5); err != nil {
				return err
			}
			i += int(l)
		case 6:
			if tag != 6<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Fixed.Size", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Fixed.Size", 6, off+i)
			}
			i += n
			if err := _fixed_readSliceSize(&m.Size, data[i:i+int(l)], slab, off+i, depth-1, "Fixed.Size", 6); err != nil {
				return err
			}
			i += int(l)
		default:
			n, err := wire.Skip(data[i:], tag, "Fixed", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded content remains
// in m or in the storage that it keeps.
func (m *Fixed) Reset() {
	if m == nil {
		return
	}
	clear(m.Int32[:cap(m.Int32)])
	m.Int32 = m.Int32[:0]
	clear(m.Int64[:cap(m.Int64)])
	m.Int64 = m.Int64[:0]
	clear(m.Uint32[:cap(m.Uint32)])
	m.Uint32 = m.Uint32[:0]
	clear(m.Uint64[:cap(m.Uint64)])
	m.Uint64 = m.Uint64[:0]
	clear(m.Level[:cap(m.Level)])
	m.Level = m.Level[:0]
	clear(m.Size[:cap(m.Size)])
	m.Size = m.Size[:0]
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Fixed) CloneKanon() *Fixed {
	if m == nil {
		return nil
	}
	c := new(Fixed)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Fixed call it.
func (m *Fixed) cloneKanon(c *Fixed) {
	c.Int32 = slices.Clone(m.Int32)
	c.Int64 = slices.Clone(m.Int64)
	c.Uint32 = slices.Clone(m.Uint32)
	c.Uint64 = slices.Clone(m.Uint64)
	c.Level = slices.Clone(m.Level)
	c.Size = slices.Clone(m.Size)
}

// _fixed_putSliceSize writes the encoding of x, a []Size, into the end of buf,
// which has room for it, and returns its length.
func _fixed_putSliceSize(buf []byte, x []Size) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutUint64(buf, i, uint64(x[k]))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _fixed_putSliceLevel writes the encoding of x, a []Level, into the end of
// buf, which has room for it, and returns its length.
func _fixed_putSliceLevel(buf []byte, x []Level) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutUint32(buf, i, uint32(x[k]))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _fixed_putSliceUint64 writes the encoding of x, a []uint64, into the end of
// buf, which has room for it, and returns its length.
func _fixed_putSliceUint64(buf []byte, x []uint64) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutUint64(buf, i, x[k])
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _fixed_putSliceUint32 writes the encoding of x, a []uint32, into the end of
// buf, which has room for it, and returns its length.
func _fixed_putSliceUint32(buf []byte, x []uint32) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutUint32(buf, i, x[k])
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _fixed_putSliceInt64 writes the encoding of x, a []int64, into the end of
// buf, which has room for it, and returns its length.
func _fixed_putSliceInt64(buf []byte, x []int64) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutUint64(buf, i, uint64(x[k]))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _fixed_putSliceInt32 writes the encoding of x, a []int32, into the end of
// buf, which has room for it, and returns its length.
func _fixed_putSliceInt32(buf []byte, x []int32) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutUint32(buf, i, uint32(x[k]))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _fixed_readSliceInt32 appends the elements that data encodes, a []int32
// without its length, to *dst. data starts at offset off of slab, and the
// decode enters depth levels below the value at most. loc and num locate the
// field in errors.
func _fixed_readSliceInt32(dst *[]int32, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]int32, 0, len(data)/4)
	}
	for i := 0; i < len(data); {
		x = append(x, 0)
		last := len(x) - 1
		u, n := wire.Uint32(data[i:])
		if n <= 0 {
			return wire.ReadError(n, loc, num, off+i)
		}
		x[last] = int32(u)
		i += n
	}
	*dst = x
	return nil
}

// _fixed_readSliceInt64 appends the elements that data encodes, a []int64
// without its length, to *dst. data starts at offset off of slab, and the
// decode enters depth levels below the value at most. loc and num locate the
// field in errors.
func _fixed_readSliceInt64(dst *[]int64, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]int64, 0, len(data)/8)
	}
	for i := 0; i < len(data); {
		x = append(x, 0)
		last := len(x) - 1
		u, n := wire.Uint64(data[i:])
		if n <= 0 {
			return wire.ReadError(n, loc, num, off+i)
		}
		x[last] = int64(u)
		i += n
	}
	*dst = x
	return nil
}

// _fixed_readSliceUint32 appends the elements that data encodes, a []uint32
// without its length, to *dst. data starts at offset off of slab, and the
// decode enters depth levels below the value at most. loc and num locate the
// field in errors.
func _fixed_readSliceUint32(dst *[]uint32, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]uint32, 0, len(data)/4)
	}
	for i := 0; i < len(data); {
		x = append(x, 0)
		last := len(x) - 1
		u, n := wire.Uint32(data[i:])
		if n <= 0 {
			return wire.ReadError(n, loc, num, off+i)
		}
		x[last] = u
		i += n
	}
	*dst = x
	return nil
}

// _fixed_readSliceUint64 appends the elements that data encodes, a []uint64
// without its length, to *dst. data starts at offset off of slab, and the
// decode enters depth levels below the value at most. loc and num locate the
// field in errors.
func _fixed_readSliceUint64(dst *[]uint64, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]uint64, 0, len(data)/8)
	}
	for i := 0; i < len(data); {
		x = append(x, 0)
		last := len(x) - 1
		u, n := wire.Uint64(data[i:])
		if n <= 0 {
			return wire.ReadError(n, loc, num, off+i)
		}
		x[last] = u
		i += n
	}
	*dst = x
	return nil
}

// _fixed_readSliceLevel appends the elements that data encodes, a []Level
// without its length, to *dst. data starts at offset off of slab, and the
// decode enters depth levels below the value at most. loc and num locate the
// field in errors.
func _fixed_readSliceLevel(dst *[]Level, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]Level, 0, len(data)/4)
	}
	for i := 0; i < len(data); {
		x = append(x, 0)
		last := len(x) - 1
		u, n := wire.Uint32(data[i:])
		if n <= 0 {
			return wire.ReadError(n, loc, num, off+i)
		}
		x[last] = Level(u)
		i += n
	}
	*dst = x
	return nil
}

// _fixed_readSliceSize appends the elements that data encodes, a []Size without
// its length, to *dst. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _fixed_readSliceSize(dst *[]Size, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]Size, 0, len(data)/8)
	}
	for i := 0; i < len(data); {
		x = append(x, 0)
		last := len(x) - 1
		u, n := wire.Uint64(data[i:])
		if n <= 0 {
			return wire.ReadError(n, loc, num, off+i)
		}
		x[last] = Size(u)
		i += n
	}
	*dst = x
	return nil
}
