// Code generated by kanon. DO NOT EDIT.
// source: time.go

package slice

import (
	"testing"

	"go.thesmos.sh/kanon/kanontest"
)

// kanonSpecTimes describes Times to the conformance suite.
var kanonSpecTimes = kanontest.Spec[Times]{
	Fields: []kanontest.Field{
		{Name: "Time", Number: 1},
	},
}

// TestKanonTimes runs the conformance suite on Times.
func TestKanonTimes(t *testing.T) {
	kanontest.Run(t, kanonSpecTimes)
}

// BenchmarkKanonTimes measures the codec of Times.
func BenchmarkKanonTimes(b *testing.B) {
	kanontest.Bench(b, kanonSpecTimes)
}

// FuzzKanonTimes fuzzes the decode of Times.
func FuzzKanonTimes(f *testing.F) {
	kanontest.Fuzz(f, kanonSpecTimes)
}
