// Code generated by kanon. DO NOT EDIT.
// source: unsigned.go

package slice

import (
	"testing"

	"go.thesmos.sh/kanon/kanontest"
)

// kanonSpecUnsigned describes Unsigned to the conformance suite.
var kanonSpecUnsigned = kanontest.Spec[Unsigned]{
	Fields: []kanontest.Field{
		{Name: "Uint", Number: 1},
		{Name: "Uint16", Number: 2},
		{Name: "Uint32", Number: 3},
		{Name: "Uint64", Number: 4},
		{Name: "Uintptr", Number: 5},
		{Name: "Status", Number: 6},
		{Name: "Port", Number: 7},
		{Name: "Count", Number: 8},
		{Name: "Size", Number: 9},
		{Name: "Index", Number: 10},
		{Name: "Handle", Number: 11},
	},
}

// TestKanonUnsigned runs the conformance suite on Unsigned.
func TestKanonUnsigned(t *testing.T) {
	kanontest.Run(t, kanonSpecUnsigned)
}

// BenchmarkKanonUnsigned measures the codec of Unsigned.
func BenchmarkKanonUnsigned(b *testing.B) {
	kanontest.Bench(b, kanonSpecUnsigned)
}

// FuzzKanonUnsigned fuzzes the decode of Unsigned.
func FuzzKanonUnsigned(f *testing.F) {
	kanontest.Fuzz(f, kanonSpecUnsigned)
}
