// Code generated by kanon. DO NOT EDIT.
// source: angles.go

//kanon:numbers Angles Turn=1 Angles=2

package imports

import (
	"io"
	"math"
	"slices"

	"go.thesmos.sh/kanon"
	math2 "go.thesmos.sh/kanon/internal/fixture/math"
	"go.thesmos.sh/kanon/wire"
)

// The file compiles against a runtime that supports version 4 of the generator.
const (
	_ = kanon.EnforceVersion(4 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 4)
)

// The generated types implement kanon.Cloner.
var (
	_ kanon.Cloner[Angles] = (*Angles)(nil)
)

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Angles) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if math.Float64bits(float64(m.Turn)) != 0 {
		n += 9
	}
	if len(m.Angles) > 0 {
		n += 1 + wire.SizeBytes(len(m.Angles)*8)
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer.
// The error is always nil.
func (m *Angles) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. The error is always nil.
func (m *Angles) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if len(m.Angles) > 0 {
		i -= _angles_putSliceMathAngle(buf[:i], m.Angles)
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if math.Float64bits(float64(m.Turn)) != 0 {
		i = wire.PutUint64(buf, i, math.Float64bits(float64(m.Turn)))
		i = wire.PutTag(buf, i, 1<<3|wire.Fixed64)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. The error
// is always nil.
func (m *Angles) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	m.encodeKanon(out)
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. The error is always nil.
func (m *Angles) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which do not copy data, since Angles contains no string.
func (m *Angles) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Angles) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := "", opts.Offset
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Angles) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := "", opts.Offset
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Angles
// call it.
func (m *Angles) decodeKanon(data []byte, slab string, off, depth int) error {
	m.Turn = 0
	m.Angles = m.Angles[:0]
	return m.mergeKanon(data, slab, off, depth)
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Angles
// call it.
func (m *Angles) mergeKanon(data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "Angles", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Fixed64 {
				return wire.FormatError(tag, wire.Fixed64, "Angles.Turn", off+at)
			}
			u, n := wire.Uint64(data[i:])
			if n <= 0 {
				return wire.ReadError(n, "Angles.Turn", 1, off+i)
			}
			m.Turn = math2.Angle(math.Float64frombits(u))
			i += n
		case 2:
			if tag != 2<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Angles.Angles", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Angles.Angles", 2, off+i)
			}
			i += n
			if err := _angles_readSliceMathAngle(&m.Angles, data[i:i+int(l)], slab, off+i, depth-1, "Angles.Angles", 2); err != nil {
				return err
			}
			i += int(l)
		default:
			n, err := wire.Skip(data[i:], tag, "Angles", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded content remains
// in m or in the storage that it keeps.
func (m *Angles) Reset() {
	if m == nil {
		return
	}
	m.Turn = 0
	clear(m.Angles[:cap(m.Angles)])
	m.Angles = m.Angles[:0]
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Angles) CloneKanon() *Angles {
	if m == nil {
		return nil
	}
	c := new(Angles)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Angles call it.
func (m *Angles) cloneKanon(c *Angles) {
	c.Turn = m.Turn
	c.Angles = slices.Clone(m.Angles)
}

// _angles_putSliceMathAngle writes the encoding of x, a []math2.Angle, into the
// end of buf, which has room for it, and returns its length.
func _angles_putSliceMathAngle(buf []byte, x []math2.Angle) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutUint64(buf, i, math.Float64bits(float64(x[k])))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _angles_readSliceMathAngle appends the elements that data encodes, a
// []math2.Angle without its length, to *dst. data starts at offset off of slab,
// and the decode enters depth levels below the value at most. loc and num
// locate the field in errors.
func _angles_readSliceMathAngle(dst *[]math2.Angle, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]math2.Angle, 0, wire.SliceCap[math2.Angle](len(data)/8))
	}
	for i := 0; i < len(data); {
		x = append(x, 0)
		last := len(x) - 1
		u, n := wire.Uint64(data[i:])
		if n <= 0 {
			return wire.ReadError(n, loc, num, off+i)
		}
		x[last] = math2.Angle(math.Float64frombits(u))
		i += n
	}
	*dst = x
	return nil
}
