// Code generated by kanon. DO NOT EDIT.
// source: bool.go

//kanon:numbers Bools Bool=1 Flag=2

package mapvalue

import (
	"io"
	"slices"
	"strings"

	"go.thesmos.sh/kanon"
	"go.thesmos.sh/kanon/wire"
)

// The file compiles against a runtime that supports version 1 of the generator.
const (
	_ = kanon.EnforceVersion(1 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 1)
)

// The generated types implement kanon.Cloner.
var (
	_ kanon.Cloner[Bools] = (*Bools)(nil)
)

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Bools) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if len(m.Bool) > 0 {
		n += 1 + wire.SizeBytes(_bool_sizeMapStringBool(m.Bool))
	}
	if len(m.Flag) > 0 {
		n += 1 + wire.SizeBytes(_bool_sizeMapStringFlag(m.Flag))
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer.
// The error is always nil.
func (m *Bools) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. The error is always nil.
func (m *Bools) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if len(m.Flag) > 0 {
		i -= _bool_putMapStringFlag(buf[:i], m.Flag)
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if len(m.Bool) > 0 {
		i -= _bool_putMapStringBool(buf[:i], m.Bool)
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. The error
// is always nil.
func (m *Bools) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	m.encodeKanon(out)
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. The error is always nil.
func (m *Bools) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which copy data once.
func (m *Bools) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Bools) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Bools) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Bools
// call it.
func (m *Bools) decodeKanon(data []byte, slab string, off, depth int) error {
	seen, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{})
	if seen[0]&(1<<0) == 0 {
		clear(m.Bool)
	}
	if seen[0]&(1<<1) == 0 {
		clear(m.Flag)
	}
	return err
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Bools
// call it.
func (m *Bools) mergeKanon(data []byte, slab string, off, depth int) error {
	_, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{^uint64(0)})
	return err
}

// fieldsKanon decodes the fields in data into m for decodeKanon and mergeKanon.
// The first occurrence of a tracked field whose bit in seen is clear decodes
// into the memory of the field, and every other occurrence merges. fieldsKanon
// returns seen with the bits of the tracked fields that data contains.
func (m *Bools) fieldsKanon(data []byte, slab string, off, depth int, seen [1]uint64) ([1]uint64, error) {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return seen, wire.ReadError(n, "Bools", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Bools.Bool", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Bools.Bool", 1, off+i)
			}
			i += n
			if err := _bool_readMapStringBool(&m.Bool, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<0) == 0, "Bools.Bool", 1); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 0
		case 2:
			if tag != 2<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Bools.Flag", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Bools.Flag", 2, off+i)
			}
			i += n
			if err := _bool_readMapStringFlag(&m.Flag, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<1) == 0, "Bools.Flag", 2); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 1
		default:
			n, err := wire.Skip(data[i:], tag, "Bools", 0, off+at)
			if err != nil {
				return seen, err
			}
			i += n
		}
	}
	return seen, nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded data stays
// reachable through m.
func (m *Bools) Reset() {
	if m == nil {
		return
	}
	clear(m.Bool)
	clear(m.Flag)
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Bools) CloneKanon() *Bools {
	if m == nil {
		return nil
	}
	c := new(Bools)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Bools call it.
func (m *Bools) cloneKanon(c *Bools) {
	c.Bool = _bool_cloneMapStringBool(m.Bool)
	c.Flag = _bool_cloneMapStringFlag(m.Flag)
}

// _bool_sizeMapStringBool returns the length of the encoding of the keys and
// values of x, a map[string]bool.
func _bool_sizeMapStringBool(x map[string]bool) int {
	n := len(x)
	var mk string
	for mk = range x {
		n += wire.SizeBytes(len(mk))
	}
	return n
}

// _bool_sizeMapStringFlag returns the length of the encoding of the keys and
// values of x, a map[string]Flag.
func _bool_sizeMapStringFlag(x map[string]Flag) int {
	n := len(x)
	var mk string
	for mk = range x {
		n += wire.SizeBytes(len(mk))
	}
	return n
}

// _bool_putMapStringFlag writes the encoding of x, a map[string]Flag, into the
// end of buf, which has room for it, and returns its length.
func _bool_putMapStringFlag(buf []byte, x map[string]Flag) int {
	i := len(buf)
	if len(x) <= 16 {
		type pair = wire.Pair[string, Flag]
		var arr [16]pair
		pairs := arr[:0]
		for mk, mv := range x {
			pairs = append(pairs, pair{Key: mk, Value: mv})
		}
		wire.SortPairs(pairs)
		for k := len(pairs) - 1; k >= 0; k-- {
			i = wire.PutBool(buf, i, bool(pairs[k].Value))
			i = wire.PutRaw(buf, i, pairs[k].Key)
			i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Key)))
		}
	} else {
		keys := make([]string, 0, len(x))
		for mk := range x {
			keys = append(keys, mk)
		}
		slices.Sort(keys)
		for k := len(keys) - 1; k >= 0; k-- {
			mk := keys[k]
			mv := x[mk]
			i = wire.PutBool(buf, i, bool(mv))
			i = wire.PutRaw(buf, i, mk)
			i = wire.PutUvarint(buf, i, uint64(len(mk)))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _bool_putMapStringBool writes the encoding of x, a map[string]bool, into the
// end of buf, which has room for it, and returns its length.
func _bool_putMapStringBool(buf []byte, x map[string]bool) int {
	i := len(buf)
	if len(x) <= 16 {
		type pair = wire.Pair[string, bool]
		var arr [16]pair
		pairs := arr[:0]
		for mk, mv := range x {
			pairs = append(pairs, pair{Key: mk, Value: mv})
		}
		wire.SortPairs(pairs)
		for k := len(pairs) - 1; k >= 0; k-- {
			i = wire.PutBool(buf, i, pairs[k].Value)
			i = wire.PutRaw(buf, i, pairs[k].Key)
			i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Key)))
		}
	} else {
		keys := make([]string, 0, len(x))
		for mk := range x {
			keys = append(keys, mk)
		}
		slices.Sort(keys)
		for k := len(keys) - 1; k >= 0; k-- {
			mk := keys[k]
			mv := x[mk]
			i = wire.PutBool(buf, i, mv)
			i = wire.PutRaw(buf, i, mk)
			i = wire.PutUvarint(buf, i, uint64(len(mk)))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _bool_readMapStringBool adds the entries that data encodes, a map[string]bool
// without its length, to *dst. With collect set, it clears *dst first, and the
// entries reuse the memory of up to 16 of its values. data starts at offset off
// of slab, and the decode enters depth levels below the value at most. loc and
// num locate the field in errors.
func _bool_readMapStringBool(dst *map[string]bool, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string]bool)
		*dst = x
	}
	var mk string
	var mv bool
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		{
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, loc, num, off+i)
			}
			mv = u != 0
			i += n
		}
		x[mk] = mv
	}
	return nil
}

// _bool_readMapStringFlag adds the entries that data encodes, a map[string]Flag
// without its length, to *dst. With collect set, it clears *dst first, and the
// entries reuse the memory of up to 16 of its values. data starts at offset off
// of slab, and the decode enters depth levels below the value at most. loc and
// num locate the field in errors.
func _bool_readMapStringFlag(dst *map[string]Flag, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string]Flag)
		*dst = x
	}
	var mk string
	var mv Flag
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		{
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, loc, num, off+i)
			}
			mv = Flag(u != 0)
			i += n
		}
		x[mk] = mv
	}
	return nil
}

// _bool_cloneMapStringBool returns a copy of x, a map[string]bool, and nil for
// a nil x.
func _bool_cloneMapStringBool(x map[string]bool) map[string]bool {
	if x == nil {
		return nil
	}
	c := make(map[string]bool, len(x))
	for mk, mv := range x {
		c[strings.Clone(mk)] = mv
	}
	return c
}

// _bool_cloneMapStringFlag returns a copy of x, a map[string]Flag, and nil for
// a nil x.
func _bool_cloneMapStringFlag(x map[string]Flag) map[string]Flag {
	if x == nil {
		return nil
	}
	c := make(map[string]Flag, len(x))
	for mk, mv := range x {
		c[strings.Clone(mk)] = mv
	}
	return c
}
