// Code generated by kanon. DO NOT EDIT.
// source: nested.go

//kanon:numbers Nested Slice=1 Map=2 Sets=3 Array=4 Lists=5 Int32=6 Inner=7 Label=8 Holders=9 Graph=10
//kanon:numbers Holder Names=1 Inner=2

package mapvalue

import (
	"io"
	"slices"
	"strings"

	"go.thesmos.sh/kanon"
	"go.thesmos.sh/kanon/internal/fixture/external"
	"go.thesmos.sh/kanon/wire"
)

// The file compiles against a runtime that supports version 4 of the generator.
const (
	_ = kanon.EnforceVersion(4 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 4)
)

// The generated types implement kanon.Cloner.
var (
	_ kanon.Cloner[Nested] = (*Nested)(nil)
)

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Nested) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if len(m.Slice) > 0 {
		n += 1 + wire.SizeBytes(_nested_sizeMapStringSliceInt32(m.Slice))
	}
	if len(m.Map) > 0 {
		n += 1 + wire.SizeBytes(_nested_sizeMapStringMapInt64String(m.Map))
	}
	if len(m.Sets) > 0 {
		n += 1 + wire.SizeBytes(_nested_sizeMapInt32MapStringBool(m.Sets))
	}
	if len(m.Array) > 0 {
		n += 1 + wire.SizeBytes(_nested_sizeMapStringArray3Int32(m.Array))
	}
	if len(m.Lists) > 0 {
		n += 1 + wire.SizeBytes(_nested_sizeMapStringArray2SliceInt32(m.Lists))
	}
	if len(m.Int32) > 0 {
		n += 1 + wire.SizeBytes(_nested_sizeMapStringPtrInt32(m.Int32))
	}
	if len(m.Inner) > 0 {
		n += 1 + wire.SizeBytes(_nested_sizeMapStringPtrInner(m.Inner))
	}
	if len(m.Label) > 0 {
		n += 1 + wire.SizeBytes(_nested_sizeMapStringPtrExternalLabel(m.Label))
	}
	if len(m.Holders) > 0 {
		n += 1 + wire.SizeBytes(_nested_sizeMapStringHolder(m.Holders))
	}
	if len(m.Graph) > 0 {
		n += 1 + wire.SizeBytes(_nested_sizeGraph(m.Graph))
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer. It
// fails when the value of a field fails to encode: a type that encodes itself
// returns an error, ValidateKanon of a type rejects a value, an interface
// stores a type that the tag option types of its field does not list, a map has
// a key with a NaN component or two keys of one projection, or a slice or a map
// has more elements than the tag option max of its field allows.
func (m *Nested) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. It fails when the value of a field
// fails to encode: a type that encodes itself returns an error, ValidateKanon
// of a type rejects a value, an interface stores a type that the tag option
// types of its field does not list, a map has a key with a NaN component or two
// keys of one projection, or a slice or a map has more elements than the tag
// option max of its field allows.
func (m *Nested) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if len(m.Graph) > 0 {
		i -= _nested_putGraph(buf[:i], m.Graph)
		i = wire.PutTag(buf, i, 10<<3|wire.Bytes)
	}
	if len(m.Holders) > 0 {
		i -= _nested_putMapStringHolder(buf[:i], m.Holders)
		i = wire.PutTag(buf, i, 9<<3|wire.Bytes)
	}
	if len(m.Label) > 0 {
		w, err := _nested_putMapStringPtrExternalLabel(buf[:i], m.Label, "Nested.Label", 8)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 8<<3|wire.Bytes)
	}
	if len(m.Inner) > 0 {
		i -= _nested_putMapStringPtrInner(buf[:i], m.Inner)
		i = wire.PutTag(buf, i, 7<<3|wire.Bytes)
	}
	if len(m.Int32) > 0 {
		i -= _nested_putMapStringPtrInt32(buf[:i], m.Int32)
		i = wire.PutTag(buf, i, 6<<3|wire.Bytes)
	}
	if len(m.Lists) > 0 {
		i -= _nested_putMapStringArray2SliceInt32(buf[:i], m.Lists)
		i = wire.PutTag(buf, i, 5<<3|wire.Bytes)
	}
	if len(m.Array) > 0 {
		i -= _nested_putMapStringArray3Int32(buf[:i], m.Array)
		i = wire.PutTag(buf, i, 4<<3|wire.Bytes)
	}
	if len(m.Sets) > 0 {
		i -= _nested_putMapInt32MapStringBool(buf[:i], m.Sets)
		i = wire.PutTag(buf, i, 3<<3|wire.Bytes)
	}
	if len(m.Map) > 0 {
		i -= _nested_putMapStringMapInt64String(buf[:i], m.Map)
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if len(m.Slice) > 0 {
		i -= _nested_putMapStringSliceInt32(buf[:i], m.Slice)
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. It fails
// when the value of a field fails to encode: a type that encodes itself returns
// an error, ValidateKanon of a type rejects a value, an interface stores a type
// that the tag option types of its field does not list, a map has a key with a
// NaN component or two keys of one projection, or a slice or a map has more
// elements than the tag option max of its field allows.
func (m *Nested) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	if _, err := m.encodeKanon(out); err != nil {
		return b, err
	}
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. It fails when the value of a field fails to encode: a type that
// encodes itself returns an error, ValidateKanon of a type rejects a value, an
// interface stores a type that the tag option types of its field does not list,
// a map has a key with a NaN component or two keys of one projection, or a
// slice or a map has more elements than the tag option max of its field allows.
func (m *Nested) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which copy data once.
func (m *Nested) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Nested) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Nested) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Nested
// call it.
func (m *Nested) decodeKanon(data []byte, slab string, off, depth int) error {
	seen, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{})
	if seen[0]&(1<<0) == 0 {
		clear(m.Slice)
	}
	if seen[0]&(1<<1) == 0 {
		clear(m.Map)
	}
	if seen[0]&(1<<2) == 0 {
		clear(m.Sets)
	}
	if seen[0]&(1<<3) == 0 {
		clear(m.Array)
	}
	if seen[0]&(1<<4) == 0 {
		clear(m.Lists)
	}
	if seen[0]&(1<<5) == 0 {
		clear(m.Int32)
	}
	if seen[0]&(1<<6) == 0 {
		clear(m.Inner)
	}
	if seen[0]&(1<<7) == 0 {
		clear(m.Label)
	}
	if seen[0]&(1<<8) == 0 {
		clear(m.Holders)
	}
	if seen[0]&(1<<9) == 0 {
		clear(m.Graph)
	}
	return err
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Nested
// call it.
func (m *Nested) mergeKanon(data []byte, slab string, off, depth int) error {
	_, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{^uint64(0)})
	return err
}

// fieldsKanon decodes the fields in data into m for decodeKanon and mergeKanon.
// The first occurrence of a tracked field whose bit in seen is clear decodes
// into the memory of the field, and every other occurrence merges. fieldsKanon
// returns seen with the bits of the tracked fields that data contains.
func (m *Nested) fieldsKanon(data []byte, slab string, off, depth int, seen [1]uint64) ([1]uint64, error) {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return seen, wire.ReadError(n, "Nested", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Nested.Slice", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Nested.Slice", 1, off+i)
			}
			i += n
			if err := _nested_readMapStringSliceInt32(&m.Slice, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<0) == 0, "Nested.Slice", 1); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 0
		case 2:
			if tag != 2<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Nested.Map", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Nested.Map", 2, off+i)
			}
			i += n
			if err := _nested_readMapStringMapInt64String(&m.Map, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<1) == 0, "Nested.Map", 2); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 1
		case 3:
			if tag != 3<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Nested.Sets", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Nested.Sets", 3, off+i)
			}
			i += n
			if err := _nested_readMapInt32MapStringBool(&m.Sets, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<2) == 0, "Nested.Sets", 3); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 2
		case 4:
			if tag != 4<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Nested.Array", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Nested.Array", 4, off+i)
			}
			i += n
			if err := _nested_readMapStringArray3Int32(&m.Array, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<3) == 0, "Nested.Array", 4); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 3
		case 5:
			if tag != 5<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Nested.Lists", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Nested.Lists", 5, off+i)
			}
			i += n
			if err := _nested_readMapStringArray2SliceInt32(&m.Lists, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<4) == 0, "Nested.Lists", 5); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 4
		case 6:
			if tag != 6<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Nested.Int32", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Nested.Int32", 6, off+i)
			}
			i += n
			if err := _nested_readMapStringPtrInt32(&m.Int32, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<5) == 0, "Nested.Int32", 6); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 5
		case 7:
			if tag != 7<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Nested.Inner", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Nested.Inner", 7, off+i)
			}
			i += n
			if err := _nested_readMapStringPtrInner(&m.Inner, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<6) == 0, "Nested.Inner", 7); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 6
		case 8:
			if tag != 8<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Nested.Label", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Nested.Label", 8, off+i)
			}
			i += n
			if err := _nested_readMapStringPtrExternalLabel(&m.Label, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<7) == 0, "Nested.Label", 8); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 7
		case 9:
			if tag != 9<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Nested.Holders", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Nested.Holders", 9, off+i)
			}
			i += n
			if err := _nested_readMapStringHolder(&m.Holders, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<8) == 0, "Nested.Holders", 9); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 8
		case 10:
			if tag != 10<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Nested.Graph", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Nested.Graph", 10, off+i)
			}
			i += n
			if err := _nested_readGraph(&m.Graph, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<9) == 0, "Nested.Graph", 10); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 9
		default:
			n, err := wire.Skip(data[i:], tag, "Nested", 0, off+at)
			if err != nil {
				return seen, err
			}
			i += n
		}
	}
	return seen, nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded content remains
// in m or in the storage that it keeps.
func (m *Nested) Reset() {
	if m == nil {
		return
	}
	clear(m.Slice)
	clear(m.Map)
	clear(m.Sets)
	clear(m.Array)
	clear(m.Lists)
	clear(m.Int32)
	clear(m.Inner)
	clear(m.Label)
	clear(m.Holders)
	clear(m.Graph)
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Nested) CloneKanon() *Nested {
	if m == nil {
		return nil
	}
	c := new(Nested)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Nested call it.
func (m *Nested) cloneKanon(c *Nested) {
	c.Slice = _nested_cloneMapStringSliceInt32(m.Slice)
	c.Map = _nested_cloneMapStringMapInt64String(m.Map)
	c.Sets = _nested_cloneMapInt32MapStringBool(m.Sets)
	c.Array = _nested_cloneMapStringArray3Int32(m.Array)
	c.Lists = _nested_cloneMapStringArray2SliceInt32(m.Lists)
	c.Int32 = _nested_cloneMapStringPtrInt32(m.Int32)
	c.Inner = _nested_cloneMapStringPtrInner(m.Inner)
	c.Label = _nested_cloneMapStringPtrExternalLabel(m.Label)
	c.Holders = _nested_cloneMapStringHolder(m.Holders)
	c.Graph = _nested_cloneGraph(m.Graph)
}

// _nested_sizeMapStringSliceInt32 returns the length of the encoding of the
// keys and values of x, a map[string][]int32.
func _nested_sizeMapStringSliceInt32(x map[string][]int32) int {
	n := 0
	var mk string
	var mv []int32
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + wire.SizeBytes(_nested_sizeSliceInt32(mv))
	}
	return n
}

// _nested_sizeMapStringMapInt64String returns the length of the encoding of the
// keys and values of x, a map[string]map[int64]string.
func _nested_sizeMapStringMapInt64String(x map[string]map[int64]string) int {
	n := 0
	var mk string
	var mv map[int64]string
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + wire.SizeBytes(_nested_sizeMapInt64String(mv))
	}
	return n
}

// _nested_sizeMapInt32MapStringBool returns the length of the encoding of the
// keys and values of x, a map[int32]map[string]bool.
func _nested_sizeMapInt32MapStringBool(x map[int32]map[string]bool) int {
	n := 0
	var mk int32
	var mv map[string]bool
	for mk, mv = range x {
		n += wire.SizeUvarint(wire.Zigzag(int64(mk))) + wire.SizeBytes(_nested_sizeMapStringBool(mv))
	}
	return n
}

// _nested_sizeMapStringArray3Int32 returns the length of the encoding of the
// keys and values of x, a map[string][3]int32.
func _nested_sizeMapStringArray3Int32(x map[string][3]int32) int {
	n := 0
	var mk string
	var mv [3]int32
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + wire.SizeBytes(_nested_sizeArray3Int32(&mv))
	}
	return n
}

// _nested_sizeMapStringArray2SliceInt32 returns the length of the encoding of
// the keys and values of x, a map[string][2][]int32.
func _nested_sizeMapStringArray2SliceInt32(x map[string][2][]int32) int {
	n := 0
	var mk string
	var mv [2][]int32
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + wire.SizeBytes(_nested_sizeArray2SliceInt32(&mv))
	}
	return n
}

// _nested_sizeMapStringPtrInt32 returns the length of the encoding of the keys
// and values of x, a map[string]*int32.
func _nested_sizeMapStringPtrInt32(x map[string]*int32) int {
	n := 0
	var mk string
	var mv *int32
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + _nested_sizePtrInt32(mv)
	}
	return n
}

// _nested_sizeMapStringPtrInner returns the length of the encoding of the keys
// and values of x, a map[string]*Inner.
func _nested_sizeMapStringPtrInner(x map[string]*Inner) int {
	n := 0
	var mk string
	var mv *Inner
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + _nested_sizePtrInner(mv)
	}
	return n
}

// _nested_sizeMapStringPtrExternalLabel returns the length of the encoding of
// the keys and values of x, a map[string]*external.Label.
func _nested_sizeMapStringPtrExternalLabel(x map[string]*external.Label) int {
	n := 0
	var mk string
	var mv *external.Label
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + _nested_sizePtrExternalLabel(mv)
	}
	return n
}

// _nested_sizeMapStringHolder returns the length of the encoding of the keys
// and values of x, a map[string]Holder.
func _nested_sizeMapStringHolder(x map[string]Holder) int {
	n := 0
	var mk string
	var mv Holder
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + wire.SizeBytes(_nested_sizeHolder(&mv))
	}
	return n
}

// _nested_sizeGraph returns the length of the encoding of the keys and values
// of x, a Graph.
func _nested_sizeGraph(x Graph) int {
	n := 0
	var mk string
	var mv Graph
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + wire.SizeBytes(_nested_sizeGraph(mv))
	}
	return n
}

// _nested_putGraph writes the encoding of x, a Graph, into the end of buf,
// which has room for it, and returns its length.
func _nested_putGraph(buf []byte, x Graph) int {
	i := len(buf)
	if len(x) <= 16 {
		type pair = wire.Pair[string, Graph]
		var arr [16]pair
		pairs := arr[:0]
		for mk, mv := range x {
			pairs = append(pairs, pair{Key: mk, Value: mv})
		}
		wire.SortPairs(pairs)
		for k := len(pairs) - 1; k >= 0; k-- {
			i -= _nested_putGraph(buf[:i], pairs[k].Value)
			i = wire.PutRaw(buf, i, pairs[k].Key)
			i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Key)))
		}
	} else {
		keys := make([]string, 0, len(x))
		for mk := range x {
			keys = append(keys, mk)
		}
		slices.Sort(keys)
		for k := len(keys) - 1; k >= 0; k-- {
			mk := keys[k]
			mv := x[mk]
			i -= _nested_putGraph(buf[:i], mv)
			i = wire.PutRaw(buf, i, mk)
			i = wire.PutUvarint(buf, i, uint64(len(mk)))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _nested_putMapStringHolder writes the encoding of x, a map[string]Holder,
// into the end of buf, which has room for it, and returns its length.
func _nested_putMapStringHolder(buf []byte, x map[string]Holder) int {
	i := len(buf)
	var arr [16]string
	keys := arr[:0]
	for mk := range x {
		keys = append(keys, mk)
	}
	slices.Sort(keys)
	for k := len(keys) - 1; k >= 0; k-- {
		mk := keys[k]
		mv := x[mk]
		{
			w := _nested_putHolder(buf[:i], &mv)
			i -= w
			i = wire.PutUvarint(buf, i, uint64(w))
		}
		i = wire.PutRaw(buf, i, mk)
		i = wire.PutUvarint(buf, i, uint64(len(mk)))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _nested_putMapStringPtrExternalLabel writes the encoding of x, a
// map[string]*external.Label, into the end of buf, which has room for it, and
// returns its length. It fails for a value that fails to encode, which loc and
// num locate.
func _nested_putMapStringPtrExternalLabel(buf []byte, x map[string]*external.Label, loc string, num int) (int, error) {
	i := len(buf)
	if len(x) <= 16 {
		type pair = wire.Pair[string, *external.Label]
		var arr [16]pair
		pairs := arr[:0]
		for mk, mv := range x {
			pairs = append(pairs, pair{Key: mk, Value: mv})
		}
		wire.SortPairs(pairs)
		for k := len(pairs) - 1; k >= 0; k-- {
			{
				w, err := _nested_putPtrExternalLabel(buf[:i], pairs[k].Value, loc, num)
				if err != nil {
					return 0, err
				}
				i -= w
			}
			i = wire.PutRaw(buf, i, pairs[k].Key)
			i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Key)))
		}
	} else {
		keys := make([]string, 0, len(x))
		for mk := range x {
			keys = append(keys, mk)
		}
		slices.Sort(keys)
		for k := len(keys) - 1; k >= 0; k-- {
			mk := keys[k]
			mv := x[mk]
			{
				w, err := _nested_putPtrExternalLabel(buf[:i], mv, loc, num)
				if err != nil {
					return 0, err
				}
				i -= w
			}
			i = wire.PutRaw(buf, i, mk)
			i = wire.PutUvarint(buf, i, uint64(len(mk)))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, nil
}

// _nested_putMapStringPtrInner writes the encoding of x, a map[string]*Inner,
// into the end of buf, which has room for it, and returns its length.
func _nested_putMapStringPtrInner(buf []byte, x map[string]*Inner) int {
	i := len(buf)
	if len(x) <= 16 {
		type pair = wire.Pair[string, *Inner]
		var arr [16]pair
		pairs := arr[:0]
		for mk, mv := range x {
			pairs = append(pairs, pair{Key: mk, Value: mv})
		}
		wire.SortPairs(pairs)
		for k := len(pairs) - 1; k >= 0; k-- {
			i -= _nested_putPtrInner(buf[:i], pairs[k].Value)
			i = wire.PutRaw(buf, i, pairs[k].Key)
			i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Key)))
		}
	} else {
		keys := make([]string, 0, len(x))
		for mk := range x {
			keys = append(keys, mk)
		}
		slices.Sort(keys)
		for k := len(keys) - 1; k >= 0; k-- {
			mk := keys[k]
			mv := x[mk]
			i -= _nested_putPtrInner(buf[:i], mv)
			i = wire.PutRaw(buf, i, mk)
			i = wire.PutUvarint(buf, i, uint64(len(mk)))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _nested_putMapStringPtrInt32 writes the encoding of x, a map[string]*int32,
// into the end of buf, which has room for it, and returns its length.
func _nested_putMapStringPtrInt32(buf []byte, x map[string]*int32) int {
	i := len(buf)
	if len(x) <= 16 {
		type pair = wire.Pair[string, *int32]
		var arr [16]pair
		pairs := arr[:0]
		for mk, mv := range x {
			pairs = append(pairs, pair{Key: mk, Value: mv})
		}
		wire.SortPairs(pairs)
		for k := len(pairs) - 1; k >= 0; k-- {
			i -= _nested_putPtrInt32(buf[:i], pairs[k].Value)
			i = wire.PutRaw(buf, i, pairs[k].Key)
			i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Key)))
		}
	} else {
		keys := make([]string, 0, len(x))
		for mk := range x {
			keys = append(keys, mk)
		}
		slices.Sort(keys)
		for k := len(keys) - 1; k >= 0; k-- {
			mk := keys[k]
			mv := x[mk]
			i -= _nested_putPtrInt32(buf[:i], mv)
			i = wire.PutRaw(buf, i, mk)
			i = wire.PutUvarint(buf, i, uint64(len(mk)))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _nested_putMapStringArray2SliceInt32 writes the encoding of x, a
// map[string][2][]int32, into the end of buf, which has room for it, and
// returns its length.
func _nested_putMapStringArray2SliceInt32(buf []byte, x map[string][2][]int32) int {
	i := len(buf)
	var arr [16]string
	keys := arr[:0]
	for mk := range x {
		keys = append(keys, mk)
	}
	slices.Sort(keys)
	for k := len(keys) - 1; k >= 0; k-- {
		mk := keys[k]
		mv := x[mk]
		i -= _nested_putArray2SliceInt32(buf[:i], &mv)
		i = wire.PutRaw(buf, i, mk)
		i = wire.PutUvarint(buf, i, uint64(len(mk)))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _nested_putMapStringArray3Int32 writes the encoding of x, a
// map[string][3]int32, into the end of buf, which has room for it, and returns
// its length.
func _nested_putMapStringArray3Int32(buf []byte, x map[string][3]int32) int {
	i := len(buf)
	var arr [16]string
	keys := arr[:0]
	for mk := range x {
		keys = append(keys, mk)
	}
	slices.Sort(keys)
	for k := len(keys) - 1; k >= 0; k-- {
		mk := keys[k]
		mv := x[mk]
		i -= _nested_putArray3Int32(buf[:i], &mv)
		i = wire.PutRaw(buf, i, mk)
		i = wire.PutUvarint(buf, i, uint64(len(mk)))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _nested_putMapInt32MapStringBool writes the encoding of x, a
// map[int32]map[string]bool, into the end of buf, which has room for it, and
// returns its length.
func _nested_putMapInt32MapStringBool(buf []byte, x map[int32]map[string]bool) int {
	i := len(buf)
	if len(x) <= 16 {
		type pair = wire.Pair[int32, map[string]bool]
		var arr [16]pair
		pairs := arr[:0]
		for mk, mv := range x {
			pairs = append(pairs, pair{Key: mk, Value: mv})
		}
		wire.SortPairs(pairs)
		for k := len(pairs) - 1; k >= 0; k-- {
			i -= _nested_putMapStringBool(buf[:i], pairs[k].Value)
			i = wire.PutUvarint(buf, i, wire.Zigzag(int64(pairs[k].Key)))
		}
	} else {
		keys := make([]int32, 0, len(x))
		for mk := range x {
			keys = append(keys, mk)
		}
		slices.Sort(keys)
		for k := len(keys) - 1; k >= 0; k-- {
			mk := keys[k]
			mv := x[mk]
			i -= _nested_putMapStringBool(buf[:i], mv)
			i = wire.PutUvarint(buf, i, wire.Zigzag(int64(mk)))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _nested_putMapStringMapInt64String writes the encoding of x, a
// map[string]map[int64]string, into the end of buf, which has room for it, and
// returns its length.
func _nested_putMapStringMapInt64String(buf []byte, x map[string]map[int64]string) int {
	i := len(buf)
	if len(x) <= 16 {
		type pair = wire.Pair[string, map[int64]string]
		var arr [16]pair
		pairs := arr[:0]
		for mk, mv := range x {
			pairs = append(pairs, pair{Key: mk, Value: mv})
		}
		wire.SortPairs(pairs)
		for k := len(pairs) - 1; k >= 0; k-- {
			i -= _nested_putMapInt64String(buf[:i], pairs[k].Value)
			i = wire.PutRaw(buf, i, pairs[k].Key)
			i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Key)))
		}
	} else {
		keys := make([]string, 0, len(x))
		for mk := range x {
			keys = append(keys, mk)
		}
		slices.Sort(keys)
		for k := len(keys) - 1; k >= 0; k-- {
			mk := keys[k]
			mv := x[mk]
			i -= _nested_putMapInt64String(buf[:i], mv)
			i = wire.PutRaw(buf, i, mk)
			i = wire.PutUvarint(buf, i, uint64(len(mk)))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _nested_putMapStringSliceInt32 writes the encoding of x, a
// map[string][]int32, into the end of buf, which has room for it, and returns
// its length.
func _nested_putMapStringSliceInt32(buf []byte, x map[string][]int32) int {
	i := len(buf)
	if len(x) <= 16 {
		type pair = wire.Pair[string, []int32]
		var arr [16]pair
		pairs := arr[:0]
		for mk, mv := range x {
			pairs = append(pairs, pair{Key: mk, Value: mv})
		}
		wire.SortPairs(pairs)
		for k := len(pairs) - 1; k >= 0; k-- {
			i -= _nested_putSliceInt32(buf[:i], pairs[k].Value)
			i = wire.PutRaw(buf, i, pairs[k].Key)
			i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Key)))
		}
	} else {
		keys := make([]string, 0, len(x))
		for mk := range x {
			keys = append(keys, mk)
		}
		slices.Sort(keys)
		for k := len(keys) - 1; k >= 0; k-- {
			mk := keys[k]
			mv := x[mk]
			i -= _nested_putSliceInt32(buf[:i], mv)
			i = wire.PutRaw(buf, i, mk)
			i = wire.PutUvarint(buf, i, uint64(len(mk)))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _nested_readMapStringSliceInt32 adds the entries that data encodes, a
// map[string][]int32 without its length, to *dst. With collect set, it clears
// *dst first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _nested_readMapStringSliceInt32(dst *map[string][]int32, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	var free [16][]int32
	var freeKeys [16]string
	held := 0
	if collect {
		for mk, mv := range x {
			if held == len(free) {
				break
			}
			freeKeys[held], free[held] = mk, mv
			held++
		}
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string][]int32)
		*dst = x
	}
	var mk string
	var mv []int32
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		mv = nil
		if held > 0 {
			held = wire.Take(freeKeys[:], free[:], held, mk)
			mv = free[held]
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mv = mv[:0]
			if err := _nested_readSliceInt32(&mv, data[i:i+int(l)], slab, off+i, depth-1, loc, num); err != nil {
				return err
			}
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _nested_readMapStringMapInt64String adds the entries that data encodes, a
// map[string]map[int64]string without its length, to *dst. With collect set, it
// clears *dst first, and the entries reuse the memory of up to 16 of its
// values. data starts at offset off of slab, and the decode enters depth levels
// below the value at most. loc and num locate the field in errors.
func _nested_readMapStringMapInt64String(dst *map[string]map[int64]string, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	var free [16]map[int64]string
	var freeKeys [16]string
	held := 0
	if collect {
		for mk, mv := range x {
			if held == len(free) {
				break
			}
			freeKeys[held], free[held] = mk, mv
			held++
		}
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string]map[int64]string)
		*dst = x
	}
	var mk string
	var mv map[int64]string
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		mv = nil
		if held > 0 {
			held = wire.Take(freeKeys[:], free[:], held, mk)
			mv = free[held]
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if err := _nested_readMapInt64String(&mv, data[i:i+int(l)], slab, off+i, depth-1, true, loc, num); err != nil {
				return err
			}
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _nested_readMapInt32MapStringBool adds the entries that data encodes, a
// map[int32]map[string]bool without its length, to *dst. With collect set, it
// clears *dst first, and the entries reuse the memory of up to 16 of its
// values. data starts at offset off of slab, and the decode enters depth levels
// below the value at most. loc and num locate the field in errors.
func _nested_readMapInt32MapStringBool(dst *map[int32]map[string]bool, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	var free [16]map[string]bool
	var freeKeys [16]int32
	held := 0
	if collect {
		for mk, mv := range x {
			if held == len(free) {
				break
			}
			freeKeys[held], free[held] = mk, mv
			held++
		}
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[int32]map[string]bool)
		*dst = x
	}
	var mk int32
	var mv map[string]bool
	for i := 0; i < len(data); {
		{
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, loc, num, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int32(s)) {
				return wire.RangeError(s, "int32", loc, num, off+i)
			}
			mk = int32(s)
			i += n
		}
		mv = nil
		if held > 0 {
			held = wire.Take(freeKeys[:], free[:], held, mk)
			mv = free[held]
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if err := _nested_readMapStringBool(&mv, data[i:i+int(l)], slab, off+i, depth-1, true, loc, num); err != nil {
				return err
			}
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _nested_readMapStringArray3Int32 adds the entries that data encodes, a
// map[string][3]int32 without its length, to *dst. With collect set, it clears
// *dst first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _nested_readMapStringArray3Int32(dst *map[string][3]int32, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string][3]int32)
		*dst = x
	}
	var mk string
	var mv [3]int32
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if err := _nested_readArray3Int32(&mv, data[i:i+int(l)], slab, off+i, depth-1, loc, num); err != nil {
				return err
			}
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _nested_readMapStringArray2SliceInt32 adds the entries that data encodes, a
// map[string][2][]int32 without its length, to *dst. With collect set, it
// clears *dst first, and the entries reuse the memory of up to 16 of its
// values. data starts at offset off of slab, and the decode enters depth levels
// below the value at most. loc and num locate the field in errors.
func _nested_readMapStringArray2SliceInt32(dst *map[string][2][]int32, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	var free [16][2][]int32
	var freeKeys [16]string
	held := 0
	if collect {
		for mk, mv := range x {
			if held == len(free) {
				break
			}
			freeKeys[held], free[held] = mk, mv
			held++
		}
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string][2][]int32)
		*dst = x
	}
	var mk string
	var mv [2][]int32
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		mv = [2][]int32{}
		if held > 0 {
			held = wire.Take(freeKeys[:], free[:], held, mk)
			mv = free[held]
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if err := _nested_readArray2SliceInt32(&mv, data[i:i+int(l)], slab, off+i, depth-1, loc, num); err != nil {
				return err
			}
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _nested_readMapStringPtrInt32 adds the entries that data encodes, a
// map[string]*int32 without its length, to *dst. With collect set, it clears
// *dst first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _nested_readMapStringPtrInt32(dst *map[string]*int32, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	var free [16]*int32
	var freeKeys [16]string
	held := 0
	if collect {
		for mk, mv := range x {
			if held == len(free) {
				break
			}
			freeKeys[held], free[held] = mk, mv
			held++
		}
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string]*int32)
		*dst = x
	}
	var mk string
	var mv *int32
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		mv = nil
		if held > 0 {
			held = wire.Take(freeKeys[:], free[:], held, mk)
			mv = free[held]
		}
		{
			used, err := _nested_readPtrInt32(&mv, data[i:], slab, off+i, depth-1, loc, num)
			if err != nil {
				return err
			}
			i += used
		}
		x[mk] = mv
	}
	return nil
}

// _nested_readMapStringPtrInner adds the entries that data encodes, a
// map[string]*Inner without its length, to *dst. With collect set, it clears
// *dst first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _nested_readMapStringPtrInner(dst *map[string]*Inner, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	var free [16]*Inner
	var freeKeys [16]string
	held := 0
	if collect {
		for mk, mv := range x {
			if held == len(free) {
				break
			}
			freeKeys[held], free[held] = mk, mv
			held++
		}
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string]*Inner)
		*dst = x
	}
	var mk string
	var mv *Inner
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		mv = nil
		if held > 0 {
			held = wire.Take(freeKeys[:], free[:], held, mk)
			mv = free[held]
		}
		{
			used, err := _nested_readPtrInner(&mv, data[i:], slab, off+i, depth-1, loc, num)
			if err != nil {
				return err
			}
			i += used
		}
		x[mk] = mv
	}
	return nil
}

// _nested_readMapStringPtrExternalLabel adds the entries that data encodes, a
// map[string]*external.Label without its length, to *dst. With collect set, it
// clears *dst first, and the entries reuse the memory of up to 16 of its
// values. data starts at offset off of slab, and the decode enters depth levels
// below the value at most. loc and num locate the field in errors.
func _nested_readMapStringPtrExternalLabel(dst *map[string]*external.Label, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	var free [16]*external.Label
	var freeKeys [16]string
	held := 0
	if collect {
		for mk, mv := range x {
			if held == len(free) {
				break
			}
			freeKeys[held], free[held] = mk, mv
			held++
		}
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string]*external.Label)
		*dst = x
	}
	var mk string
	var mv *external.Label
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		mv = nil
		if held > 0 {
			held = wire.Take(freeKeys[:], free[:], held, mk)
			mv = free[held]
		}
		{
			used, err := _nested_readPtrExternalLabel(&mv, data[i:], slab, off+i, depth-1, loc, num)
			if err != nil {
				return err
			}
			i += used
		}
		x[mk] = mv
	}
	return nil
}

// _nested_readMapStringHolder adds the entries that data encodes, a
// map[string]Holder without its length, to *dst. With collect set, it clears
// *dst first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _nested_readMapStringHolder(dst *map[string]Holder, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	var free [16]Holder
	var freeKeys [16]string
	held := 0
	if collect {
		for mk, mv := range x {
			if held == len(free) {
				break
			}
			freeKeys[held], free[held] = mk, mv
			held++
		}
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string]Holder)
		*dst = x
	}
	var mk string
	var mv Holder
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		mv = Holder{}
		if held > 0 {
			held = wire.Take(freeKeys[:], free[:], held, mk)
			mv = free[held]
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("Holder", 0, off+i)
			}
			if err := _nested_readHolder(&mv, data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _nested_readGraph adds the entries that data encodes, a Graph without its
// length, to *dst. With collect set, it clears *dst first, and the entries
// reuse the memory of up to 16 of its values. data starts at offset off of
// slab, and the decode enters depth levels below the value at most. loc and num
// locate the field in errors.
func _nested_readGraph(dst *Graph, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	var free [16]Graph
	var freeKeys [16]string
	held := 0
	if collect {
		for mk, mv := range x {
			if held == len(free) {
				break
			}
			freeKeys[held], free[held] = mk, mv
			held++
		}
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(Graph)
		*dst = x
	}
	var mk string
	var mv Graph
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		mv = nil
		if held > 0 {
			held = wire.Take(freeKeys[:], free[:], held, mk)
			mv = free[held]
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if err := _nested_readGraph(&mv, data[i:i+int(l)], slab, off+i, depth-1, true, loc, num); err != nil {
				return err
			}
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _nested_cloneMapStringSliceInt32 returns a copy of x, a map[string][]int32,
// and nil for a nil x.
func _nested_cloneMapStringSliceInt32(x map[string][]int32) map[string][]int32 {
	if x == nil {
		return nil
	}
	c := make(map[string][]int32, len(x))
	for mk, mv := range x {
		c[strings.Clone(mk)] = slices.Clone(mv)
	}
	return c
}

// _nested_cloneMapStringMapInt64String returns a copy of x, a
// map[string]map[int64]string, and nil for a nil x.
func _nested_cloneMapStringMapInt64String(x map[string]map[int64]string) map[string]map[int64]string {
	if x == nil {
		return nil
	}
	c := make(map[string]map[int64]string, len(x))
	for mk, mv := range x {
		c[strings.Clone(mk)] = _nested_cloneMapInt64String(mv)
	}
	return c
}

// _nested_cloneMapInt32MapStringBool returns a copy of x, a
// map[int32]map[string]bool, and nil for a nil x.
func _nested_cloneMapInt32MapStringBool(x map[int32]map[string]bool) map[int32]map[string]bool {
	if x == nil {
		return nil
	}
	c := make(map[int32]map[string]bool, len(x))
	for mk, mv := range x {
		c[mk] = _nested_cloneMapStringBool(mv)
	}
	return c
}

// _nested_cloneMapStringArray3Int32 returns a copy of x, a map[string][3]int32,
// and nil for a nil x.
func _nested_cloneMapStringArray3Int32(x map[string][3]int32) map[string][3]int32 {
	if x == nil {
		return nil
	}
	c := make(map[string][3]int32, len(x))
	for mk, mv := range x {
		c[strings.Clone(mk)] = mv
	}
	return c
}

// _nested_cloneMapStringArray2SliceInt32 returns a copy of x, a
// map[string][2][]int32, and nil for a nil x.
func _nested_cloneMapStringArray2SliceInt32(x map[string][2][]int32) map[string][2][]int32 {
	if x == nil {
		return nil
	}
	c := make(map[string][2][]int32, len(x))
	for mk, mv := range x {
		var cv [2][]int32
		_nested_cloneArray2SliceInt32(&cv, &mv)
		c[strings.Clone(mk)] = cv
	}
	return c
}

// _nested_cloneMapStringPtrInt32 returns a copy of x, a map[string]*int32, and
// nil for a nil x.
func _nested_cloneMapStringPtrInt32(x map[string]*int32) map[string]*int32 {
	if x == nil {
		return nil
	}
	c := make(map[string]*int32, len(x))
	for mk, mv := range x {
		c[strings.Clone(mk)] = _nested_clonePtrInt32(mv)
	}
	return c
}

// _nested_cloneMapStringPtrInner returns a copy of x, a map[string]*Inner, and
// nil for a nil x.
func _nested_cloneMapStringPtrInner(x map[string]*Inner) map[string]*Inner {
	if x == nil {
		return nil
	}
	c := make(map[string]*Inner, len(x))
	for mk, mv := range x {
		c[strings.Clone(mk)] = _nested_clonePtrInner(mv)
	}
	return c
}

// _nested_cloneMapStringPtrExternalLabel returns a copy of x, a
// map[string]*external.Label, and nil for a nil x.
func _nested_cloneMapStringPtrExternalLabel(x map[string]*external.Label) map[string]*external.Label {
	if x == nil {
		return nil
	}
	c := make(map[string]*external.Label, len(x))
	for mk, mv := range x {
		c[strings.Clone(mk)] = _nested_clonePtrExternalLabel(mv)
	}
	return c
}

// _nested_cloneMapStringHolder returns a copy of x, a map[string]Holder, and
// nil for a nil x.
func _nested_cloneMapStringHolder(x map[string]Holder) map[string]Holder {
	if x == nil {
		return nil
	}
	c := make(map[string]Holder, len(x))
	for mk, mv := range x {
		var cv Holder
		_nested_cloneHolder(&cv, &mv)
		c[strings.Clone(mk)] = cv
	}
	return c
}

// _nested_cloneGraph returns a copy of x, a Graph, and nil for a nil x.
func _nested_cloneGraph(x Graph) Graph {
	if x == nil {
		return nil
	}
	c := make(Graph, len(x))
	for mk, mv := range x {
		c[strings.Clone(mk)] = _nested_cloneGraph(mv)
	}
	return c
}

// _nested_sizeSliceInt32 returns the length of the encoding of the elements of
// x, a []int32.
func _nested_sizeSliceInt32(x []int32) int {
	n := 0
	for k := range x {
		n += wire.SizeUvarint(wire.Zigzag(int64(x[k])))
	}
	return n
}

// _nested_sizeMapInt64String returns the length of the encoding of the keys and
// values of x, a map[int64]string.
func _nested_sizeMapInt64String(x map[int64]string) int {
	n := 0
	var mk int64
	var mv string
	for mk, mv = range x {
		n += wire.SizeUvarint(wire.Zigzag(mk)) + wire.SizeBytes(len(mv))
	}
	return n
}

// _nested_sizeMapStringBool returns the length of the encoding of the keys and
// values of x, a map[string]bool.
func _nested_sizeMapStringBool(x map[string]bool) int {
	n := len(x)
	var mk string
	for mk = range x {
		n += wire.SizeBytes(len(mk))
	}
	return n
}

// _nested_sizeArray3Int32 returns the length of the encoding of the elements of
// x, a [3]int32.
func _nested_sizeArray3Int32(x *[3]int32) int {
	n := 0
	for k := range x {
		n += wire.SizeUvarint(wire.Zigzag(int64(x[k])))
	}
	return n
}

// _nested_sizeArray2SliceInt32 returns the length of the encoding of the
// elements of x, a [2][]int32.
func _nested_sizeArray2SliceInt32(x *[2][]int32) int {
	n := 0
	for k := range x {
		n += wire.SizeBytes(_nested_sizeSliceInt32(x[k]))
	}
	return n
}

// _nested_sizePtrInt32 returns the length of the encoding of x, a *int32: its
// presence byte and the value that it points at.
func _nested_sizePtrInt32(x *int32) int {
	if x == nil {
		return 1
	}
	return 1 + wire.SizeUvarint(wire.Zigzag(int64(*x)))
}

// _nested_sizePtrInner returns the length of the encoding of x, a *Inner: its
// presence byte and the value that it points at.
func _nested_sizePtrInner(x *Inner) int {
	if x == nil {
		return 1
	}
	return 1 + wire.SizeBytes(x.SizeKanon())
}

// _nested_sizePtrExternalLabel returns the length of the encoding of x, a
// *external.Label: its presence byte and the value that it points at.
func _nested_sizePtrExternalLabel(x *external.Label) int {
	if x == nil {
		return 1
	}
	return 1 + wire.SizeBytes(x.SizeKanon())
}

// _nested_sizeHolder returns the length of the encoding of the Holder that m
// points at.
func _nested_sizeHolder(m *Holder) int {
	n := 0
	if len(m.Names) > 0 {
		n += 1 + wire.SizeBytes(_nested_sizeSliceString(m.Names))
	}
	if m.Inner != nil {
		n += 1 + wire.SizeBytes(m.Inner.SizeKanon())
	}
	return n
}

// _nested_putHolder writes the encoding of the Holder that m points at into the
// end of buf, which has room for it, and returns its length.
func _nested_putHolder(buf []byte, m *Holder) int {
	i := len(buf)
	if m.Inner != nil {
		w, _ := m.Inner.encodeKanon(buf[:i])
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if len(m.Names) > 0 {
		i -= _nested_putSliceString(buf[:i], m.Names)
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i
}

// _nested_putPtrExternalLabel writes the encoding of x, a *external.Label, into
// the end of buf, which has room for it, and returns its length. It fails for a
// value that fails to encode, which loc and num locate.
func _nested_putPtrExternalLabel(buf []byte, x *external.Label, loc string, num int) (int, error) {
	i := len(buf)
	if x != nil {
		w, err := x.EncodeKanon(buf[:i])
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
	}
	i = wire.PutBool(buf, i, x != nil)
	return len(buf) - i, nil
}

// _nested_putPtrInner writes the encoding of x, a *Inner, into the end of buf,
// which has room for it, and returns its length.
func _nested_putPtrInner(buf []byte, x *Inner) int {
	i := len(buf)
	if x != nil {
		w, _ := x.encodeKanon(buf[:i])
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
	}
	i = wire.PutBool(buf, i, x != nil)
	return len(buf) - i
}

// _nested_putPtrInt32 writes the encoding of x, a *int32, into the end of buf,
// which has room for it, and returns its length.
func _nested_putPtrInt32(buf []byte, x *int32) int {
	i := len(buf)
	if x != nil {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(*x)))
	}
	i = wire.PutBool(buf, i, x != nil)
	return len(buf) - i
}

// _nested_putArray2SliceInt32 writes the encoding of x, a [2][]int32, into the
// end of buf, which has room for it, and returns its length.
func _nested_putArray2SliceInt32(buf []byte, x *[2][]int32) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i -= _nested_putSliceInt32(buf[:i], x[k])
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _nested_putArray3Int32 writes the encoding of x, a [3]int32, into the end of
// buf, which has room for it, and returns its length.
func _nested_putArray3Int32(buf []byte, x *[3]int32) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(x[k])))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _nested_putMapStringBool writes the encoding of x, a map[string]bool, into
// the end of buf, which has room for it, and returns its length.
func _nested_putMapStringBool(buf []byte, x map[string]bool) int {
	i := len(buf)
	if len(x) <= 16 {
		type pair = wire.Pair[string, bool]
		var arr [16]pair
		pairs := arr[:0]
		for mk, mv := range x {
			pairs = append(pairs, pair{Key: mk, Value: mv})
		}
		wire.SortPairs(pairs)
		for k := len(pairs) - 1; k >= 0; k-- {
			i = wire.PutBool(buf, i, pairs[k].Value)
			i = wire.PutRaw(buf, i, pairs[k].Key)
			i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Key)))
		}
	} else {
		keys := make([]string, 0, len(x))
		for mk := range x {
			keys = append(keys, mk)
		}
		slices.Sort(keys)
		for k := len(keys) - 1; k >= 0; k-- {
			mk := keys[k]
			mv := x[mk]
			i = wire.PutBool(buf, i, mv)
			i = wire.PutRaw(buf, i, mk)
			i = wire.PutUvarint(buf, i, uint64(len(mk)))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _nested_putMapInt64String writes the encoding of x, a map[int64]string, into
// the end of buf, which has room for it, and returns its length.
func _nested_putMapInt64String(buf []byte, x map[int64]string) int {
	i := len(buf)
	if len(x) <= 16 {
		type pair = wire.Pair[int64, string]
		var arr [16]pair
		pairs := arr[:0]
		for mk, mv := range x {
			pairs = append(pairs, pair{Key: mk, Value: mv})
		}
		wire.SortPairs(pairs)
		for k := len(pairs) - 1; k >= 0; k-- {
			i = wire.PutRaw(buf, i, pairs[k].Value)
			i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Value)))
			i = wire.PutUvarint(buf, i, wire.Zigzag(pairs[k].Key))
		}
	} else {
		keys := make([]int64, 0, len(x))
		for mk := range x {
			keys = append(keys, mk)
		}
		slices.Sort(keys)
		for k := len(keys) - 1; k >= 0; k-- {
			mk := keys[k]
			mv := x[mk]
			i = wire.PutRaw(buf, i, mv)
			i = wire.PutUvarint(buf, i, uint64(len(mv)))
			i = wire.PutUvarint(buf, i, wire.Zigzag(mk))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _nested_putSliceInt32 writes the encoding of x, a []int32, into the end of
// buf, which has room for it, and returns its length.
func _nested_putSliceInt32(buf []byte, x []int32) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(x[k])))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _nested_readSliceInt32 appends the elements that data encodes, a []int32
// without its length, to *dst. data starts at offset off of slab, and the
// decode enters depth levels below the value at most. loc and num locate the
// field in errors.
func _nested_readSliceInt32(dst *[]int32, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]int32, 0, wire.SliceCap[int32](wire.CountVarints(data)))
	}
	for i := 0; i < len(data); {
		x = append(x, 0)
		last := len(x) - 1
		u, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, loc, num, off+i)
		}
		s := wire.Unzigzag(u)
		if s != int64(int32(s)) {
			return wire.RangeError(s, "int32", loc, num, off+i)
		}
		x[last] = int32(s)
		i += n
	}
	*dst = x
	return nil
}

// _nested_readMapInt64String adds the entries that data encodes, a
// map[int64]string without its length, to *dst. With collect set, it clears
// *dst first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _nested_readMapInt64String(dst *map[int64]string, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[int64]string)
		*dst = x
	}
	var mk int64
	var mv string
	for i := 0; i < len(data); {
		{
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, loc, num, off+i)
			}
			mk = wire.Unzigzag(u)
			i += n
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mv = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _nested_readMapStringBool adds the entries that data encodes, a
// map[string]bool without its length, to *dst. With collect set, it clears *dst
// first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _nested_readMapStringBool(dst *map[string]bool, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string]bool)
		*dst = x
	}
	var mk string
	var mv bool
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		{
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, loc, num, off+i)
			}
			mv = u != 0
			i += n
		}
		x[mk] = mv
	}
	return nil
}

// _nested_readArray3Int32 decodes the elements that data encodes, a [3]int32
// without its length, into *dst. It fails unless data encodes exactly 3
// elements. data starts at offset off of slab, and the decode enters depth
// levels below the value at most. loc and num locate the field in errors.
func _nested_readArray3Int32(dst *[3]int32, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		u, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, loc, num, off+i)
		}
		s := wire.Unzigzag(u)
		if s != int64(int32(s)) {
			return wire.RangeError(s, "int32", loc, num, off+i)
		}
		dst[k] = int32(s)
		i += n
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}

// _nested_readArray2SliceInt32 decodes the elements that data encodes, a
// [2][]int32 without its length, into *dst. It fails unless data encodes
// exactly 2 elements. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _nested_readArray2SliceInt32(dst *[2][]int32, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		dst[k] = dst[k][:0]
		if err := _nested_readSliceInt32(&dst[k], data[i:i+int(l)], slab, off+i, depth, loc, num); err != nil {
			return err
		}
		i += int(l)
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}

// _nested_readPtrInt32 decodes the *int32 at the start of data into *dst and
// returns the length of its encoding: nil for the presence byte 0, and for the
// presence byte 1 the value that follows, into the value that *dst points at or
// into a new one. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _nested_readPtrInt32(dst **int32, data []byte, slab string, off, depth int, loc string, num int) (int, error) {
	if depth < 0 {
		return 0, wire.DepthError(loc, num, off)
	}
	present, err := wire.Presence(data, loc, num, off)
	if err != nil {
		return 0, err
	}
	if !present {
		*dst = nil
		return 1, nil
	}
	x := *dst
	if x == nil {
		x = new(int32)
		*dst = x
	}
	i := 1
	u, n := wire.Uvarint(data[i:])
	if n <= 0 {
		return 0, wire.ReadError(n, loc, num, off+i)
	}
	s := wire.Unzigzag(u)
	if s != int64(int32(s)) {
		return 0, wire.RangeError(s, "int32", loc, num, off+i)
	}
	*x = int32(s)
	i += n
	return i, nil
}

// _nested_readPtrInner decodes the *Inner at the start of data into *dst and
// returns the length of its encoding: nil for the presence byte 0, and for the
// presence byte 1 the value that follows, into the value that *dst points at or
// into a new one. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _nested_readPtrInner(dst **Inner, data []byte, slab string, off, depth int, loc string, num int) (int, error) {
	if depth < 0 {
		return 0, wire.DepthError(loc, num, off)
	}
	present, err := wire.Presence(data, loc, num, off)
	if err != nil {
		return 0, err
	}
	if !present {
		*dst = nil
		return 1, nil
	}
	x := *dst
	if x == nil {
		x = new(Inner)
		*dst = x
	}
	i := 1
	l, n := wire.Uvarint(data[i:])
	if n <= 0 || uint64(len(data)-i-n) < l {
		return 0, wire.ReadError(n, loc, num, off+i)
	}
	i += n
	if depth < 1 {
		return 0, wire.DepthError("Inner", 0, off+i)
	}
	if err := x.decodeKanon(data[i:i+int(l)], slab, off+i, depth-1); err != nil {
		return 0, err
	}
	i += int(l)
	return i, nil
}

// _nested_readPtrExternalLabel decodes the *external.Label at the start of data
// into *dst and returns the length of its encoding: nil for the presence byte
// 0, and for the presence byte 1 the value that follows, into the value that
// *dst points at or into a new one. data starts at offset off of slab, and the
// decode enters depth levels below the value at most. loc and num locate the
// field in errors.
func _nested_readPtrExternalLabel(dst **external.Label, data []byte, slab string, off, depth int, loc string, num int) (int, error) {
	if depth < 0 {
		return 0, wire.DepthError(loc, num, off)
	}
	present, err := wire.Presence(data, loc, num, off)
	if err != nil {
		return 0, err
	}
	if !present {
		*dst = nil
		return 1, nil
	}
	x := *dst
	if x == nil {
		x = new(external.Label)
		*dst = x
	}
	i := 1
	l, n := wire.Uvarint(data[i:])
	if n <= 0 || uint64(len(data)-i-n) < l {
		return 0, wire.ReadError(n, loc, num, off+i)
	}
	i += n
	if depth < 1 {
		return 0, wire.DepthError("external.Label", 0, off+i)
	}
	if err := x.DecodeKanon(data[i:i+int(l)], wire.Nested(slab, off+i, depth-1)); err != nil {
		return 0, err
	}
	i += int(l)
	return i, nil
}

// _nested_readHolder sets the Holder that m points at to the value encoded in
// data and reuses its memory, as DecodeKanon does. data starts at offset off of
// slab, and the decode enters depth levels below the value at most.
func _nested_readHolder(m *Holder, data []byte, slab string, off, depth int) error {
	m.Names = m.Names[:0]
	seen, err := _nested_fieldsHolder(m, data, slab, off, depth, [1]uint64{})
	if seen[0]&(1<<0) == 0 {
		m.Inner = nil
	}
	return err
}

// _nested_cloneMapInt64String returns a copy of x, a map[int64]string, and nil
// for a nil x.
func _nested_cloneMapInt64String(x map[int64]string) map[int64]string {
	if x == nil {
		return nil
	}
	c := make(map[int64]string, len(x))
	for mk, mv := range x {
		c[mk] = strings.Clone(mv)
	}
	return c
}

// _nested_cloneMapStringBool returns a copy of x, a map[string]bool, and nil
// for a nil x.
func _nested_cloneMapStringBool(x map[string]bool) map[string]bool {
	if x == nil {
		return nil
	}
	c := make(map[string]bool, len(x))
	for mk, mv := range x {
		c[strings.Clone(mk)] = mv
	}
	return c
}

// _nested_cloneArray2SliceInt32 copies the [2][]int32 that src points at into
// the one that dst points at, element by element.
func _nested_cloneArray2SliceInt32(dst, src *[2][]int32) {
	for k := range src {
		dst[k] = slices.Clone(src[k])
	}
}

// _nested_clonePtrInt32 returns a pointer to a copy of the value that x, a
// *int32, points at, and nil for a nil x.
func _nested_clonePtrInt32(x *int32) *int32 {
	if x == nil {
		return nil
	}
	return new(*x)
}

// _nested_clonePtrInner returns a pointer to a copy of the value that x, a
// *Inner, points at, and nil for a nil x.
func _nested_clonePtrInner(x *Inner) *Inner {
	if x == nil {
		return nil
	}
	return x.CloneKanon()
}

// _nested_clonePtrExternalLabel returns a pointer to a copy of the value that
// x, a *external.Label, points at, and nil for a nil x.
func _nested_clonePtrExternalLabel(x *external.Label) *external.Label {
	if x == nil {
		return nil
	}
	return x.CloneKanon()
}

// _nested_cloneHolder copies the Holder that src points at into the one that
// dst points at, as CloneKanon does.
func _nested_cloneHolder(dst, src *Holder) {
	dst.Names = _nested_cloneSliceString(src.Names)
	dst.Inner = _nested_clonePtrInner(src.Inner)
}

// _nested_sizeSliceString returns the length of the encoding of the elements of
// x, a []string.
func _nested_sizeSliceString(x []string) int {
	n := 0
	for k := range x {
		n += wire.SizeBytes(len(x[k]))
	}
	return n
}

// _nested_putSliceString writes the encoding of x, a []string, into the end of
// buf, which has room for it, and returns its length.
func _nested_putSliceString(buf []byte, x []string) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutRaw(buf, i, x[k])
		i = wire.PutUvarint(buf, i, uint64(len(x[k])))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _nested_fieldsHolder decodes the fields in data into m for the decode and the
// merge of Holder. The first occurrence of a tracked field whose bit in seen is
// clear decodes into the memory of the field, and every other occurrence
// merges. _nested_fieldsHolder returns seen with the bits of the tracked fields
// that data contains.
func _nested_fieldsHolder(m *Holder, data []byte, slab string, off, depth int, seen [1]uint64) ([1]uint64, error) {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return seen, wire.ReadError(n, "Holder", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Holder.Names", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Holder.Names", 1, off+i)
			}
			i += n
			if err := _nested_readSliceString(&m.Names, data[i:i+int(l)], slab, off+i, depth-1, "Holder.Names", 1); err != nil {
				return seen, err
			}
			i += int(l)
		case 2:
			if tag != 2<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Holder.Inner", off+at)
			}
			if m.Inner == nil {
				m.Inner = new(Inner)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Holder.Inner", 2, off+i)
			}
			i += n
			if depth < 2 {
				return seen, wire.DepthError("Inner", 0, off+i)
			}
			var err error
			if seen[0]&(1<<0) == 0 {
				seen[0] |= 1 << 0
				err = m.Inner.decodeKanon(data[i:i+int(l)], slab, off+i, depth-2)
			} else {
				err = m.Inner.mergeKanon(data[i:i+int(l)], slab, off+i, depth-2)
			}
			if err != nil {
				return seen, err
			}
			i += int(l)
		default:
			n, err := wire.Skip(data[i:], tag, "Holder", 0, off+at)
			if err != nil {
				return seen, err
			}
			i += n
		}
	}
	return seen, nil
}

// _nested_cloneSliceString returns a copy of x, a []string, and nil for a nil
// x.
func _nested_cloneSliceString(x []string) []string {
	if x == nil {
		return nil
	}
	c := make([]string, len(x))
	for k := range x {
		c[k] = strings.Clone(x[k])
	}
	return c
}

// _nested_readSliceString appends the elements that data encodes, a []string
// without its length, to *dst. data starts at offset off of slab, and the
// decode enters depth levels below the value at most. loc and num locate the
// field in errors.
func _nested_readSliceString(dst *[]string, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]string, 0, wire.SliceCap[string](wire.CountValues(data)))
	}
	for i := 0; i < len(data); {
		x = append(x, "")
		last := len(x) - 1
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		x[last] = slab[off+i : off+i+int(l)]
		i += int(l)
	}
	*dst = x
	return nil
}
