// Code generated by kanon. DO NOT EDIT.
// source: nested.go

package mapvalue

import (
	"reflect"
	"testing"

	"go.thesmos.sh/kanon/kanontest"
)

// kanonSpecNested describes Nested to the conformance suite.
var kanonSpecNested = kanontest.Spec[Nested]{
	Fields: []kanontest.Field{
		{Name: "Slice", Number: 1},
		{Name: "Map", Number: 2},
		{Name: "Sets", Number: 3},
		{Name: "Array", Number: 4},
		{Name: "Lists", Number: 5},
		{Name: "Int32", Number: 6},
		{Name: "Inner", Number: 7},
		{Name: "Label", Number: 8},
		{Name: "Holders", Number: 9},
		{Name: "Graph", Number: 10},
	},
	Structs: []kanontest.Struct{
		{
			Type: reflect.TypeFor[Holder](),
			Name: "Holder",
			Fields: []kanontest.Field{
				{Name: "Names", Number: 1},
				{Name: "Inner", Number: 2},
			},
		},
	},
}

// TestKanonNested runs the conformance suite on Nested.
func TestKanonNested(t *testing.T) {
	kanontest.Run(t, kanonSpecNested)
}

// BenchmarkKanonNested measures the codec of Nested.
func BenchmarkKanonNested(b *testing.B) {
	kanontest.Bench(b, kanonSpecNested)
}

// FuzzKanonNested fuzzes the decode of Nested.
func FuzzKanonNested(f *testing.F) {
	kanontest.Fuzz(f, kanonSpecNested)
}
