// Code generated by kanon. DO NOT EDIT.
// source: struct.go

//kanon:numbers Inner Label=1 Count=2
//kanon:numbers Structs Inner=1 Label=2 Loose=3 Remote=4 Pair=5 Anonym=6 Nothing=7
//kanon:numbers Loose Note=1 Size=2
//kanon:numbers go.thesmos.sh/kanon/internal/fixture/external.Remote Name=1 Count=2 Meta=3
//kanon:numbers go.thesmos.sh/kanon/internal/fixture/external.Remote.Meta Tag=1 Rank=2
//kanon:numbers go.thesmos.sh/kanon/internal/fixture/external.Pair Key=1 Val=2
//kanon:numbers Structs.Anonym[value] A=1 B=2
//kanon:numbers Structs.Nothing[value]

package mapvalue

import (
	"io"
	"slices"
	"strings"

	"go.thesmos.sh/kanon"
	"go.thesmos.sh/kanon/internal/fixture/external"
	"go.thesmos.sh/kanon/wire"
)

// The file compiles against a runtime that supports version 2 of the generator.
const (
	_ = kanon.EnforceVersion(2 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 2)
)

// The generated types implement kanon.Cloner.
var (
	_ kanon.Cloner[Inner]   = (*Inner)(nil)
	_ kanon.Cloner[Structs] = (*Structs)(nil)
)

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Inner) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Label != "" {
		n += 1 + wire.SizeBytes(len(m.Label))
	}
	if m.Count != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(m.Count))
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer.
// The error is always nil.
func (m *Inner) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. The error is always nil.
func (m *Inner) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if m.Count != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(m.Count))
		i = wire.PutTag(buf, i, 2<<3|wire.Varint)
	}
	if m.Label != "" {
		i = wire.PutRaw(buf, i, m.Label)
		i = wire.PutUvarint(buf, i, uint64(len(m.Label)))
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. The error
// is always nil.
func (m *Inner) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	m.encodeKanon(out)
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. The error is always nil.
func (m *Inner) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which copy data once.
func (m *Inner) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Inner) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Inner) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Inner
// call it.
func (m *Inner) decodeKanon(data []byte, slab string, off, depth int) error {
	m.Label = ""
	m.Count = 0
	return m.mergeKanon(data, slab, off, depth)
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Inner
// call it.
func (m *Inner) mergeKanon(data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "Inner", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Inner.Label", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Inner.Label", 1, off+i)
			}
			i += n
			m.Label = slab[off+i : off+i+int(l)]
			i += int(l)
		case 2:
			if tag != 2<<3|wire.Varint {
				return wire.FormatError(tag, wire.Varint, "Inner.Count", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, "Inner.Count", 2, off+i)
			}
			m.Count = wire.Unzigzag(u)
			i += n
		default:
			n, err := wire.Skip(data[i:], tag, "Inner", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded data stays
// reachable through m.
func (m *Inner) Reset() {
	if m == nil {
		return
	}
	m.Label = ""
	m.Count = 0
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Inner) CloneKanon() *Inner {
	if m == nil {
		return nil
	}
	c := new(Inner)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Inner call it.
func (m *Inner) cloneKanon(c *Inner) {
	c.Label = strings.Clone(m.Label)
	c.Count = m.Count
}

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Structs) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if len(m.Inner) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapStringInner(m.Inner))
	}
	if len(m.Label) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapStringExternalLabel(m.Label))
	}
	if len(m.Loose) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapStringLoose(m.Loose))
	}
	if len(m.Remote) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapStringExternalRemote(m.Remote))
	}
	if len(m.Pair) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapStringExternalPairStringInt32(m.Pair))
	}
	if len(m.Anonym) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapStringAny(m.Anonym))
	}
	if len(m.Nothing) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapStringAny2(m.Nothing))
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer. It
// fails when the value of a field fails to encode: a type that encodes itself
// returns an error, ValidateKanon of a type rejects a value, an interface
// stores a type that the tag option types of its field does not list, or a map
// has a key with a NaN component or two keys of one projection.
func (m *Structs) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. It fails when the value of a field
// fails to encode: a type that encodes itself returns an error, ValidateKanon
// of a type rejects a value, an interface stores a type that the tag option
// types of its field does not list, or a map has a key with a NaN component or
// two keys of one projection.
func (m *Structs) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if len(m.Nothing) > 0 {
		i -= _struct_putMapStringAny2(buf[:i], m.Nothing)
		i = wire.PutTag(buf, i, 7<<3|wire.Bytes)
	}
	if len(m.Anonym) > 0 {
		i -= _struct_putMapStringAny(buf[:i], m.Anonym)
		i = wire.PutTag(buf, i, 6<<3|wire.Bytes)
	}
	if len(m.Pair) > 0 {
		i -= _struct_putMapStringExternalPairStringInt32(buf[:i], m.Pair)
		i = wire.PutTag(buf, i, 5<<3|wire.Bytes)
	}
	if len(m.Remote) > 0 {
		i -= _struct_putMapStringExternalRemote(buf[:i], m.Remote)
		i = wire.PutTag(buf, i, 4<<3|wire.Bytes)
	}
	if len(m.Loose) > 0 {
		i -= _struct_putMapStringLoose(buf[:i], m.Loose)
		i = wire.PutTag(buf, i, 3<<3|wire.Bytes)
	}
	if len(m.Label) > 0 {
		w, err := _struct_putMapStringExternalLabel(buf[:i], m.Label, "Structs.Label", 2)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if len(m.Inner) > 0 {
		i -= _struct_putMapStringInner(buf[:i], m.Inner)
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. It fails
// when the value of a field fails to encode: a type that encodes itself returns
// an error, ValidateKanon of a type rejects a value, an interface stores a type
// that the tag option types of its field does not list, or a map has a key with
// a NaN component or two keys of one projection.
func (m *Structs) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	if _, err := m.encodeKanon(out); err != nil {
		return b, err
	}
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. It fails when the value of a field fails to encode: a type that
// encodes itself returns an error, ValidateKanon of a type rejects a value, an
// interface stores a type that the tag option types of its field does not list,
// or a map has a key with a NaN component or two keys of one projection.
func (m *Structs) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which copy data once.
func (m *Structs) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Structs) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Structs) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Structs
// call it.
func (m *Structs) decodeKanon(data []byte, slab string, off, depth int) error {
	seen, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{})
	if seen[0]&(1<<0) == 0 {
		clear(m.Inner)
	}
	if seen[0]&(1<<1) == 0 {
		clear(m.Label)
	}
	if seen[0]&(1<<2) == 0 {
		clear(m.Loose)
	}
	if seen[0]&(1<<3) == 0 {
		clear(m.Remote)
	}
	if seen[0]&(1<<4) == 0 {
		clear(m.Pair)
	}
	if seen[0]&(1<<5) == 0 {
		clear(m.Anonym)
	}
	if seen[0]&(1<<6) == 0 {
		clear(m.Nothing)
	}
	return err
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Structs
// call it.
func (m *Structs) mergeKanon(data []byte, slab string, off, depth int) error {
	_, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{^uint64(0)})
	return err
}

// fieldsKanon decodes the fields in data into m for decodeKanon and mergeKanon.
// The first occurrence of a tracked field whose bit in seen is clear decodes
// into the memory of the field, and every other occurrence merges. fieldsKanon
// returns seen with the bits of the tracked fields that data contains.
func (m *Structs) fieldsKanon(data []byte, slab string, off, depth int, seen [1]uint64) ([1]uint64, error) {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return seen, wire.ReadError(n, "Structs", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Inner", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Inner", 1, off+i)
			}
			i += n
			if err := _struct_readMapStringInner(&m.Inner, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<0) == 0, "Structs.Inner", 1); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 0
		case 2:
			if tag != 2<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Label", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Label", 2, off+i)
			}
			i += n
			if err := _struct_readMapStringExternalLabel(&m.Label, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<1) == 0, "Structs.Label", 2); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 1
		case 3:
			if tag != 3<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Loose", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Loose", 3, off+i)
			}
			i += n
			if err := _struct_readMapStringLoose(&m.Loose, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<2) == 0, "Structs.Loose", 3); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 2
		case 4:
			if tag != 4<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Remote", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Remote", 4, off+i)
			}
			i += n
			if err := _struct_readMapStringExternalRemote(&m.Remote, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<3) == 0, "Structs.Remote", 4); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 3
		case 5:
			if tag != 5<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Pair", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Pair", 5, off+i)
			}
			i += n
			if err := _struct_readMapStringExternalPairStringInt32(&m.Pair, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<4) == 0, "Structs.Pair", 5); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 4
		case 6:
			if tag != 6<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Anonym", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Anonym", 6, off+i)
			}
			i += n
			if err := _struct_readMapStringAny(&m.Anonym, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<5) == 0, "Structs.Anonym", 6); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 5
		case 7:
			if tag != 7<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Nothing", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Nothing", 7, off+i)
			}
			i += n
			if err := _struct_readMapStringAny2(&m.Nothing, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<6) == 0, "Structs.Nothing", 7); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 6
		default:
			n, err := wire.Skip(data[i:], tag, "Structs", 0, off+at)
			if err != nil {
				return seen, err
			}
			i += n
		}
	}
	return seen, nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded data stays
// reachable through m.
func (m *Structs) Reset() {
	if m == nil {
		return
	}
	clear(m.Inner)
	clear(m.Label)
	clear(m.Loose)
	clear(m.Remote)
	clear(m.Pair)
	clear(m.Anonym)
	clear(m.Nothing)
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Structs) CloneKanon() *Structs {
	if m == nil {
		return nil
	}
	c := new(Structs)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Structs call it.
func (m *Structs) cloneKanon(c *Structs) {
	c.Inner = _struct_cloneMapStringInner(m.Inner)
	c.Label = _struct_cloneMapStringExternalLabel(m.Label)
	c.Loose = _struct_cloneMapStringLoose(m.Loose)
	c.Remote = _struct_cloneMapStringExternalRemote(m.Remote)
	c.Pair = _struct_cloneMapStringExternalPairStringInt32(m.Pair)
	c.Anonym = _struct_cloneMapStringAny(m.Anonym)
	c.Nothing = _struct_cloneMapStringAny2(m.Nothing)
}

// _struct_sizeMapStringInner returns the length of the encoding of the keys and
// values of x, a map[string]Inner.
func _struct_sizeMapStringInner(x map[string]Inner) int {
	n := 0
	var mk string
	var mv Inner
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + wire.SizeBytes(mv.SizeKanon())
	}
	return n
}

// _struct_sizeMapStringExternalLabel returns the length of the encoding of the
// keys and values of x, a map[string]external.Label.
func _struct_sizeMapStringExternalLabel(x map[string]external.Label) int {
	n := 0
	var mk string
	var mv external.Label
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + wire.SizeBytes(mv.SizeKanon())
	}
	return n
}

// _struct_sizeMapStringLoose returns the length of the encoding of the keys and
// values of x, a map[string]Loose.
func _struct_sizeMapStringLoose(x map[string]Loose) int {
	n := 0
	var mk string
	var mv Loose
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + wire.SizeBytes(_struct_sizeLoose(&mv))
	}
	return n
}

// _struct_sizeMapStringExternalRemote returns the length of the encoding of the
// keys and values of x, a map[string]external.Remote.
func _struct_sizeMapStringExternalRemote(x map[string]external.Remote) int {
	n := 0
	var mk string
	var mv external.Remote
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + wire.SizeBytes(_struct_sizeExternalRemote(&mv))
	}
	return n
}

// _struct_sizeMapStringExternalPairStringInt32 returns the length of the
// encoding of the keys and values of x, a map[string]external.Pair[string,
// int32].
func _struct_sizeMapStringExternalPairStringInt32(x map[string]external.Pair[string, int32]) int {
	n := 0
	var mk string
	var mv external.Pair[string, int32]
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + wire.SizeBytes(_struct_sizeExternalPairStringInt32(&mv))
	}
	return n
}

// _struct_sizeMapStringAny returns the length of the encoding of the keys and
// values of x, a map[string]struct{A int32; B int32}.
func _struct_sizeMapStringAny(x map[string]struct {
	A int32
	B int32
}) int {
	n := 0
	var mk string
	var mv struct {
		A int32
		B int32
	}
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + wire.SizeBytes(_struct_sizeStructsAnonymValue(&mv))
	}
	return n
}

// _struct_sizeMapStringAny2 returns the length of the encoding of the keys and
// values of x, a map[string]struct{}.
func _struct_sizeMapStringAny2(x map[string]struct{}) int {
	n := len(x)
	var mk string
	for mk = range x {
		n += wire.SizeBytes(len(mk))
	}
	return n
}

// _struct_putMapStringAny2 writes the encoding of x, a map[string]struct{},
// into the end of buf, which has room for it, and returns its length.
func _struct_putMapStringAny2(buf []byte, x map[string]struct{}) int {
	i := len(buf)
	var arr [16]string
	keys := arr[:0]
	for mk := range x {
		keys = append(keys, mk)
	}
	slices.Sort(keys)
	for k := len(keys) - 1; k >= 0; k-- {
		mk := keys[k]
		i = wire.PutUvarint(buf, i, 0)
		i = wire.PutRaw(buf, i, mk)
		i = wire.PutUvarint(buf, i, uint64(len(mk)))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _struct_putMapStringAny writes the encoding of x, a map[string]struct{A
// int32; B int32}, into the end of buf, which has room for it, and returns its
// length.
func _struct_putMapStringAny(buf []byte, x map[string]struct {
	A int32
	B int32
}) int {
	i := len(buf)
	var arr [16]string
	keys := arr[:0]
	for mk := range x {
		keys = append(keys, mk)
	}
	slices.Sort(keys)
	for k := len(keys) - 1; k >= 0; k-- {
		mk := keys[k]
		mv := x[mk]
		{
			w := _struct_putStructsAnonymValue(buf[:i], &mv)
			i -= w
			i = wire.PutUvarint(buf, i, uint64(w))
		}
		i = wire.PutRaw(buf, i, mk)
		i = wire.PutUvarint(buf, i, uint64(len(mk)))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _struct_putMapStringExternalPairStringInt32 writes the encoding of x, a
// map[string]external.Pair[string, int32], into the end of buf, which has room
// for it, and returns its length.
func _struct_putMapStringExternalPairStringInt32(buf []byte, x map[string]external.Pair[string, int32]) int {
	i := len(buf)
	var arr [16]string
	keys := arr[:0]
	for mk := range x {
		keys = append(keys, mk)
	}
	slices.Sort(keys)
	for k := len(keys) - 1; k >= 0; k-- {
		mk := keys[k]
		mv := x[mk]
		{
			w := _struct_putExternalPairStringInt32(buf[:i], &mv)
			i -= w
			i = wire.PutUvarint(buf, i, uint64(w))
		}
		i = wire.PutRaw(buf, i, mk)
		i = wire.PutUvarint(buf, i, uint64(len(mk)))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _struct_putMapStringExternalRemote writes the encoding of x, a
// map[string]external.Remote, into the end of buf, which has room for it, and
// returns its length.
func _struct_putMapStringExternalRemote(buf []byte, x map[string]external.Remote) int {
	i := len(buf)
	var arr [16]string
	keys := arr[:0]
	for mk := range x {
		keys = append(keys, mk)
	}
	slices.Sort(keys)
	for k := len(keys) - 1; k >= 0; k-- {
		mk := keys[k]
		mv := x[mk]
		{
			w := _struct_putExternalRemote(buf[:i], &mv)
			i -= w
			i = wire.PutUvarint(buf, i, uint64(w))
		}
		i = wire.PutRaw(buf, i, mk)
		i = wire.PutUvarint(buf, i, uint64(len(mk)))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _struct_putMapStringLoose writes the encoding of x, a map[string]Loose, into
// the end of buf, which has room for it, and returns its length.
func _struct_putMapStringLoose(buf []byte, x map[string]Loose) int {
	i := len(buf)
	var arr [16]string
	keys := arr[:0]
	for mk := range x {
		keys = append(keys, mk)
	}
	slices.Sort(keys)
	for k := len(keys) - 1; k >= 0; k-- {
		mk := keys[k]
		mv := x[mk]
		{
			w := _struct_putLoose(buf[:i], &mv)
			i -= w
			i = wire.PutUvarint(buf, i, uint64(w))
		}
		i = wire.PutRaw(buf, i, mk)
		i = wire.PutUvarint(buf, i, uint64(len(mk)))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _struct_putMapStringExternalLabel writes the encoding of x, a
// map[string]external.Label, into the end of buf, which has room for it, and
// returns its length. It fails for a value that fails to encode, which loc and
// num locate.
func _struct_putMapStringExternalLabel(buf []byte, x map[string]external.Label, loc string, num int) (int, error) {
	i := len(buf)
	var arr [16]string
	keys := arr[:0]
	for mk := range x {
		keys = append(keys, mk)
	}
	slices.Sort(keys)
	for k := len(keys) - 1; k >= 0; k-- {
		mk := keys[k]
		mv := x[mk]
		{
			w, err := mv.EncodeKanon(buf[:i])
			if err != nil {
				return 0, err
			}
			i -= w
			i = wire.PutUvarint(buf, i, uint64(w))
		}
		i = wire.PutRaw(buf, i, mk)
		i = wire.PutUvarint(buf, i, uint64(len(mk)))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, nil
}

// _struct_putMapStringInner writes the encoding of x, a map[string]Inner, into
// the end of buf, which has room for it, and returns its length.
func _struct_putMapStringInner(buf []byte, x map[string]Inner) int {
	i := len(buf)
	var arr [16]string
	keys := arr[:0]
	for mk := range x {
		keys = append(keys, mk)
	}
	slices.Sort(keys)
	for k := len(keys) - 1; k >= 0; k-- {
		mk := keys[k]
		mv := x[mk]
		{
			w, _ := mv.encodeKanon(buf[:i])
			i -= w
			i = wire.PutUvarint(buf, i, uint64(w))
		}
		i = wire.PutRaw(buf, i, mk)
		i = wire.PutUvarint(buf, i, uint64(len(mk)))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _struct_readMapStringInner adds the entries that data encodes, a
// map[string]Inner without its length, to *dst. With collect set, it clears
// *dst first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _struct_readMapStringInner(dst *map[string]Inner, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string]Inner)
		*dst = x
	}
	var mk string
	var mv Inner
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("Inner", 0, off+i)
			}
			if err := mv.decodeKanon(data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _struct_readMapStringExternalLabel adds the entries that data encodes, a
// map[string]external.Label without its length, to *dst. With collect set, it
// clears *dst first, and the entries reuse the memory of up to 16 of its
// values. data starts at offset off of slab, and the decode enters depth levels
// below the value at most. loc and num locate the field in errors.
func _struct_readMapStringExternalLabel(dst *map[string]external.Label, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string]external.Label)
		*dst = x
	}
	var mk string
	var mv external.Label
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("external.Label", 0, off+i)
			}
			if err := mv.DecodeKanon(data[i:i+int(l)], wire.Nested(slab, off+i, depth-1)); err != nil {
				return err
			}
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _struct_readMapStringLoose adds the entries that data encodes, a
// map[string]Loose without its length, to *dst. With collect set, it clears
// *dst first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _struct_readMapStringLoose(dst *map[string]Loose, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string]Loose)
		*dst = x
	}
	var mk string
	var mv Loose
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("Loose", 0, off+i)
			}
			if err := _struct_readLoose(&mv, data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _struct_readMapStringExternalRemote adds the entries that data encodes, a
// map[string]external.Remote without its length, to *dst. With collect set, it
// clears *dst first, and the entries reuse the memory of up to 16 of its
// values. data starts at offset off of slab, and the decode enters depth levels
// below the value at most. loc and num locate the field in errors.
func _struct_readMapStringExternalRemote(dst *map[string]external.Remote, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string]external.Remote)
		*dst = x
	}
	var mk string
	var mv external.Remote
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("external.Remote", 0, off+i)
			}
			if err := _struct_readExternalRemote(&mv, data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _struct_readMapStringExternalPairStringInt32 adds the entries that data
// encodes, a map[string]external.Pair[string, int32] without its length, to
// *dst. With collect set, it clears *dst first, and the entries reuse the
// memory of up to 16 of its values. data starts at offset off of slab, and the
// decode enters depth levels below the value at most. loc and num locate the
// field in errors.
func _struct_readMapStringExternalPairStringInt32(dst *map[string]external.Pair[string, int32], data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string]external.Pair[string, int32])
		*dst = x
	}
	var mk string
	var mv external.Pair[string, int32]
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("external.Pair[string, int32]", 0, off+i)
			}
			if err := _struct_readExternalPairStringInt32(&mv, data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _struct_readMapStringAny adds the entries that data encodes, a
// map[string]struct{A int32; B int32} without its length, to *dst. With collect
// set, it clears *dst first, and the entries reuse the memory of up to 16 of
// its values. data starts at offset off of slab, and the decode enters depth
// levels below the value at most. loc and num locate the field in errors.
func _struct_readMapStringAny(dst *map[string]struct {
	A int32
	B int32
}, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string]struct {
			A int32
			B int32
		})
		*dst = x
	}
	var mk string
	var mv struct {
		A int32
		B int32
	}
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("Structs.Anonym[value]", 0, off+i)
			}
			if err := _struct_readStructsAnonymValue(&mv, data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _struct_readMapStringAny2 adds the entries that data encodes, a
// map[string]struct{} without its length, to *dst. With collect set, it clears
// *dst first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _struct_readMapStringAny2(dst *map[string]struct{}, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[string]struct{})
		*dst = x
	}
	var mk string
	var mv struct{}
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("Structs.Nothing[value]", 0, off+i)
			}
			if err := _struct_readStructsNothingValue(&mv, data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _struct_cloneMapStringInner returns a copy of x, a map[string]Inner, and nil
// for a nil x.
func _struct_cloneMapStringInner(x map[string]Inner) map[string]Inner {
	if x == nil {
		return nil
	}
	c := make(map[string]Inner, len(x))
	for mk, mv := range x {
		var cv Inner
		mv.cloneKanon(&cv)
		c[strings.Clone(mk)] = cv
	}
	return c
}

// _struct_cloneMapStringExternalLabel returns a copy of x, a
// map[string]external.Label, and nil for a nil x.
func _struct_cloneMapStringExternalLabel(x map[string]external.Label) map[string]external.Label {
	if x == nil {
		return nil
	}
	c := make(map[string]external.Label, len(x))
	for mk, mv := range x {
		c[strings.Clone(mk)] = *mv.CloneKanon()
	}
	return c
}

// _struct_cloneMapStringLoose returns a copy of x, a map[string]Loose, and nil
// for a nil x.
func _struct_cloneMapStringLoose(x map[string]Loose) map[string]Loose {
	if x == nil {
		return nil
	}
	c := make(map[string]Loose, len(x))
	for mk, mv := range x {
		var cv Loose
		_struct_cloneLoose(&cv, &mv)
		c[strings.Clone(mk)] = cv
	}
	return c
}

// _struct_cloneMapStringExternalRemote returns a copy of x, a
// map[string]external.Remote, and nil for a nil x.
func _struct_cloneMapStringExternalRemote(x map[string]external.Remote) map[string]external.Remote {
	if x == nil {
		return nil
	}
	c := make(map[string]external.Remote, len(x))
	for mk, mv := range x {
		var cv external.Remote
		_struct_cloneExternalRemote(&cv, &mv)
		c[strings.Clone(mk)] = cv
	}
	return c
}

// _struct_cloneMapStringExternalPairStringInt32 returns a copy of x, a
// map[string]external.Pair[string, int32], and nil for a nil x.
func _struct_cloneMapStringExternalPairStringInt32(x map[string]external.Pair[string, int32]) map[string]external.Pair[string, int32] {
	if x == nil {
		return nil
	}
	c := make(map[string]external.Pair[string, int32], len(x))
	for mk, mv := range x {
		var cv external.Pair[string, int32]
		_struct_cloneExternalPairStringInt32(&cv, &mv)
		c[strings.Clone(mk)] = cv
	}
	return c
}

// _struct_cloneMapStringAny returns a copy of x, a map[string]struct{A int32; B
// int32}, and nil for a nil x.
func _struct_cloneMapStringAny(x map[string]struct {
	A int32
	B int32
}) map[string]struct {
	A int32
	B int32
} {
	if x == nil {
		return nil
	}
	c := make(map[string]struct {
		A int32
		B int32
	}, len(x))
	for mk, mv := range x {
		c[strings.Clone(mk)] = mv
	}
	return c
}

// _struct_cloneMapStringAny2 returns a copy of x, a map[string]struct{}, and
// nil for a nil x.
func _struct_cloneMapStringAny2(x map[string]struct{}) map[string]struct{} {
	if x == nil {
		return nil
	}
	c := make(map[string]struct{}, len(x))
	for mk, mv := range x {
		c[strings.Clone(mk)] = mv
	}
	return c
}

// _struct_sizeLoose returns the length of the encoding of the Loose that m
// points at.
func _struct_sizeLoose(m *Loose) int {
	n := 0
	if m.Note != "" {
		n += 1 + wire.SizeBytes(len(m.Note))
	}
	if m.Size != 0 {
		n += 1 + wire.SizeUvarint(uint64(m.Size))
	}
	return n
}

// _struct_sizeExternalRemote returns the length of the encoding of the
// external.Remote that m points at.
func _struct_sizeExternalRemote(m *external.Remote) int {
	n := 0
	if m.Name != "" {
		n += 1 + wire.SizeBytes(len(m.Name))
	}
	if m.Count != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.Count)))
	}
	if s := _struct_sizeExternalRemoteMeta(&m.Meta); s > 0 {
		n += 1 + wire.SizeBytes(s)
	}
	return n
}

// _struct_sizeExternalPairStringInt32 returns the length of the encoding of the
// external.Pair[string, int32] that m points at.
func _struct_sizeExternalPairStringInt32(m *external.Pair[string, int32]) int {
	n := 0
	if m.Key != "" {
		n += 1 + wire.SizeBytes(len(m.Key))
	}
	if m.Val != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.Val)))
	}
	return n
}

// _struct_sizeStructsAnonymValue returns the length of the encoding of the
// Structs.Anonym[value] that m points at.
func _struct_sizeStructsAnonymValue(m *struct {
	A int32
	B int32
}) int {
	n := 0
	if m.A != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.A)))
	}
	if m.B != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.B)))
	}
	return n
}

// _struct_putStructsAnonymValue writes the encoding of the
// Structs.Anonym[value] that m points at into the end of buf, which has room
// for it, and returns its length.
func _struct_putStructsAnonymValue(buf []byte, m *struct {
	A int32
	B int32
}) int {
	i := len(buf)
	if m.B != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.B)))
		i = wire.PutTag(buf, i, 2<<3|wire.Varint)
	}
	if m.A != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.A)))
		i = wire.PutTag(buf, i, 1<<3|wire.Varint)
	}
	return len(buf) - i
}

// _struct_putExternalPairStringInt32 writes the encoding of the
// external.Pair[string, int32] that m points at into the end of buf, which has
// room for it, and returns its length.
func _struct_putExternalPairStringInt32(buf []byte, m *external.Pair[string, int32]) int {
	i := len(buf)
	if m.Val != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.Val)))
		i = wire.PutTag(buf, i, 2<<3|wire.Varint)
	}
	if m.Key != "" {
		i = wire.PutRaw(buf, i, m.Key)
		i = wire.PutUvarint(buf, i, uint64(len(m.Key)))
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i
}

// _struct_putExternalRemote writes the encoding of the external.Remote that m
// points at into the end of buf, which has room for it, and returns its length.
func _struct_putExternalRemote(buf []byte, m *external.Remote) int {
	i := len(buf)
	if w := _struct_putExternalRemoteMeta(buf[:i], &m.Meta); w > 0 {
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
		i = wire.PutTag(buf, i, 3<<3|wire.Bytes)
	}
	if m.Count != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.Count)))
		i = wire.PutTag(buf, i, 2<<3|wire.Varint)
	}
	if m.Name != "" {
		i = wire.PutRaw(buf, i, m.Name)
		i = wire.PutUvarint(buf, i, uint64(len(m.Name)))
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i
}

// _struct_putLoose writes the encoding of the Loose that m points at into the
// end of buf, which has room for it, and returns its length.
func _struct_putLoose(buf []byte, m *Loose) int {
	i := len(buf)
	if m.Size != 0 {
		i = wire.PutUvarint(buf, i, uint64(m.Size))
		i = wire.PutTag(buf, i, 2<<3|wire.Varint)
	}
	if m.Note != "" {
		i = wire.PutRaw(buf, i, m.Note)
		i = wire.PutUvarint(buf, i, uint64(len(m.Note)))
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i
}

// _struct_readLoose sets the Loose that m points at to the value encoded in
// data and reuses its memory, as DecodeKanon does. data starts at offset off of
// slab, and the decode enters depth levels below the value at most.
func _struct_readLoose(m *Loose, data []byte, slab string, off, depth int) error {
	m.Note = ""
	m.Size = 0
	return _struct_mergeLoose(m, data, slab, off, depth)
}

// _struct_readExternalRemote sets the external.Remote that m points at to the
// value encoded in data and reuses its memory, as DecodeKanon does. data starts
// at offset off of slab, and the decode enters depth levels below the value at
// most.
func _struct_readExternalRemote(m *external.Remote, data []byte, slab string, off, depth int) error {
	m.Name = ""
	m.Count = 0
	seen, err := _struct_fieldsExternalRemote(m, data, slab, off, depth, [1]uint64{})
	if seen[0]&(1<<0) == 0 {
		_struct_resetExternalRemoteMeta(&m.Meta)
	}
	return err
}

// _struct_readExternalPairStringInt32 sets the external.Pair[string, int32]
// that m points at to the value encoded in data and reuses its memory, as
// DecodeKanon does. data starts at offset off of slab, and the decode enters
// depth levels below the value at most.
func _struct_readExternalPairStringInt32(m *external.Pair[string, int32], data []byte, slab string, off, depth int) error {
	m.Key = ""
	m.Val = 0
	return _struct_mergeExternalPairStringInt32(m, data, slab, off, depth)
}

// _struct_readStructsAnonymValue sets the Structs.Anonym[value] that m points
// at to the value encoded in data and reuses its memory, as DecodeKanon does.
// data starts at offset off of slab, and the decode enters depth levels below
// the value at most.
func _struct_readStructsAnonymValue(m *struct {
	A int32
	B int32
}, data []byte, slab string, off, depth int) error {
	m.A = 0
	m.B = 0
	return _struct_mergeStructsAnonymValue(m, data, slab, off, depth)
}

// _struct_readStructsNothingValue sets the Structs.Nothing[value] that m points
// at to the value encoded in data and reuses its memory, as DecodeKanon does.
// data starts at offset off of slab, and the decode enters depth levels below
// the value at most.
func _struct_readStructsNothingValue(m *struct{}, data []byte, slab string, off, depth int) error {
	return _struct_mergeStructsNothingValue(m, data, slab, off, depth)
}

// _struct_cloneLoose copies the Loose that src points at into the one that dst
// points at, as CloneKanon does.
func _struct_cloneLoose(dst, src *Loose) {
	dst.Note = strings.Clone(src.Note)
	dst.Size = src.Size
}

// _struct_cloneExternalRemote copies the external.Remote that src points at
// into the one that dst points at, as CloneKanon does.
func _struct_cloneExternalRemote(dst, src *external.Remote) {
	dst.Name = strings.Clone(src.Name)
	dst.Count = src.Count
	_struct_cloneExternalRemoteMeta(&dst.Meta, &src.Meta)
}

// _struct_cloneExternalPairStringInt32 copies the external.Pair[string, int32]
// that src points at into the one that dst points at, as CloneKanon does.
func _struct_cloneExternalPairStringInt32(dst, src *external.Pair[string, int32]) {
	dst.Key = strings.Clone(src.Key)
	dst.Val = src.Val
}

// _struct_sizeExternalRemoteMeta returns the length of the encoding of the
// external.Remote.Meta that m points at.
func _struct_sizeExternalRemoteMeta(m *struct {
	Tag  string
	Rank external.Rank
}) int {
	n := 0
	if m.Tag != "" {
		n += 1 + wire.SizeBytes(len(m.Tag))
	}
	if m.Rank != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.Rank)))
	}
	return n
}

// _struct_putExternalRemoteMeta writes the encoding of the external.Remote.Meta
// that m points at into the end of buf, which has room for it, and returns its
// length.
func _struct_putExternalRemoteMeta(buf []byte, m *struct {
	Tag  string
	Rank external.Rank
}) int {
	i := len(buf)
	if m.Rank != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.Rank)))
		i = wire.PutTag(buf, i, 2<<3|wire.Varint)
	}
	if m.Tag != "" {
		i = wire.PutRaw(buf, i, m.Tag)
		i = wire.PutUvarint(buf, i, uint64(len(m.Tag)))
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i
}

// _struct_mergeLoose merges the encoding in data, which starts at offset off of
// slab, into the Loose that m points at, as MergeKanon does. The decode enters
// depth levels below m at most.
func _struct_mergeLoose(m *Loose, data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "Loose", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Loose.Note", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Loose.Note", 1, off+i)
			}
			i += n
			m.Note = slab[off+i : off+i+int(l)]
			i += int(l)
		case 2:
			if tag != 2<<3|wire.Varint {
				return wire.FormatError(tag, wire.Varint, "Loose.Size", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, "Loose.Size", 2, off+i)
			}
			if u != uint64(uint16(u)) {
				return wire.RangeError(u, "uint16", "Loose.Size", 2, off+i)
			}
			m.Size = uint16(u)
			i += n
		default:
			n, err := wire.Skip(data[i:], tag, "Loose", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

// _struct_fieldsExternalRemote decodes the fields in data into m for the decode
// and the merge of external.Remote. The first occurrence of a tracked field
// whose bit in seen is clear decodes into the memory of the field, and every
// other occurrence merges. _struct_fieldsExternalRemote returns seen with the
// bits of the tracked fields that data contains.
func _struct_fieldsExternalRemote(m *external.Remote, data []byte, slab string, off, depth int, seen [1]uint64) ([1]uint64, error) {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return seen, wire.ReadError(n, "external.Remote", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "external.Remote.Name", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "external.Remote.Name", 1, off+i)
			}
			i += n
			m.Name = slab[off+i : off+i+int(l)]
			i += int(l)
		case 2:
			if tag != 2<<3|wire.Varint {
				return seen, wire.FormatError(tag, wire.Varint, "external.Remote.Count", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "external.Remote.Count", 2, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int32(s)) {
				return seen, wire.RangeError(s, "int32", "external.Remote.Count", 2, off+i)
			}
			m.Count = int32(s)
			i += n
		case 3:
			if tag != 3<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "external.Remote.Meta", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "external.Remote.Meta", 3, off+i)
			}
			i += n
			if depth < 1 {
				return seen, wire.DepthError("external.Remote.Meta", 0, off+i)
			}
			var err error
			if seen[0]&(1<<0) == 0 {
				seen[0] |= 1 << 0
				err = _struct_readExternalRemoteMeta(&m.Meta, data[i:i+int(l)], slab, off+i, depth-1)
			} else {
				err = _struct_mergeExternalRemoteMeta(&m.Meta, data[i:i+int(l)], slab, off+i, depth-1)
			}
			if err != nil {
				return seen, err
			}
			i += int(l)
		default:
			n, err := wire.Skip(data[i:], tag, "external.Remote", 0, off+at)
			if err != nil {
				return seen, err
			}
			i += n
		}
	}
	return seen, nil
}

// _struct_resetExternalRemoteMeta clears the external.Remote.Meta that m points
// at and keeps the memory that a decode reuses, as Reset does.
func _struct_resetExternalRemoteMeta(m *struct {
	Tag  string
	Rank external.Rank
}) {
	m.Tag = ""
	m.Rank = 0
}

// _struct_mergeExternalPairStringInt32 merges the encoding in data, which
// starts at offset off of slab, into the external.Pair[string, int32] that m
// points at, as MergeKanon does. The decode enters depth levels below m at
// most.
func _struct_mergeExternalPairStringInt32(m *external.Pair[string, int32], data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "external.Pair[string, int32]", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "external.Pair[string, int32].Key", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "external.Pair[string, int32].Key", 1, off+i)
			}
			i += n
			m.Key = slab[off+i : off+i+int(l)]
			i += int(l)
		case 2:
			if tag != 2<<3|wire.Varint {
				return wire.FormatError(tag, wire.Varint, "external.Pair[string, int32].Val", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, "external.Pair[string, int32].Val", 2, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int32(s)) {
				return wire.RangeError(s, "int32", "external.Pair[string, int32].Val", 2, off+i)
			}
			m.Val = int32(s)
			i += n
		default:
			n, err := wire.Skip(data[i:], tag, "external.Pair[string, int32]", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

// _struct_mergeStructsAnonymValue merges the encoding in data, which starts at
// offset off of slab, into the Structs.Anonym[value] that m points at, as
// MergeKanon does. The decode enters depth levels below m at most.
func _struct_mergeStructsAnonymValue(m *struct {
	A int32
	B int32
}, data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "Structs.Anonym[value]", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Varint {
				return wire.FormatError(tag, wire.Varint, "Structs.Anonym[value].A", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, "Structs.Anonym[value].A", 1, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int32(s)) {
				return wire.RangeError(s, "int32", "Structs.Anonym[value].A", 1, off+i)
			}
			m.A = int32(s)
			i += n
		case 2:
			if tag != 2<<3|wire.Varint {
				return wire.FormatError(tag, wire.Varint, "Structs.Anonym[value].B", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, "Structs.Anonym[value].B", 2, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int32(s)) {
				return wire.RangeError(s, "int32", "Structs.Anonym[value].B", 2, off+i)
			}
			m.B = int32(s)
			i += n
		default:
			n, err := wire.Skip(data[i:], tag, "Structs.Anonym[value]", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

// _struct_mergeStructsNothingValue merges the encoding in data, which starts at
// offset off of slab, into the Structs.Nothing[value] that m points at, as
// MergeKanon does. The decode enters depth levels below m at most.
func _struct_mergeStructsNothingValue(m *struct{}, data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "Structs.Nothing[value]", 0, off+i)
		}
		i += n
		n, err := wire.Skip(data[i:], tag, "Structs.Nothing[value]", 0, off+at)
		if err != nil {
			return err
		}
		i += n
	}
	return nil
}

// _struct_cloneExternalRemoteMeta copies the external.Remote.Meta that src
// points at into the one that dst points at, as CloneKanon does.
func _struct_cloneExternalRemoteMeta(dst, src *struct {
	Tag  string
	Rank external.Rank
}) {
	dst.Tag = strings.Clone(src.Tag)
	dst.Rank = src.Rank
}

// _struct_readExternalRemoteMeta sets the external.Remote.Meta that m points at
// to the value encoded in data and reuses its memory, as DecodeKanon does. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most.
func _struct_readExternalRemoteMeta(m *struct {
	Tag  string
	Rank external.Rank
}, data []byte, slab string, off, depth int) error {
	m.Tag = ""
	m.Rank = 0
	return _struct_mergeExternalRemoteMeta(m, data, slab, off, depth)
}

// _struct_mergeExternalRemoteMeta merges the encoding in data, which starts at
// offset off of slab, into the external.Remote.Meta that m points at, as
// MergeKanon does. The decode enters depth levels below m at most.
func _struct_mergeExternalRemoteMeta(m *struct {
	Tag  string
	Rank external.Rank
}, data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "external.Remote.Meta", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "external.Remote.Meta.Tag", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "external.Remote.Meta.Tag", 1, off+i)
			}
			i += n
			m.Tag = slab[off+i : off+i+int(l)]
			i += int(l)
		case 2:
			if tag != 2<<3|wire.Varint {
				return wire.FormatError(tag, wire.Varint, "external.Remote.Meta.Rank", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, "external.Remote.Meta.Rank", 2, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int32(s)) {
				return wire.RangeError(s, "int32", "external.Remote.Meta.Rank", 2, off+i)
			}
			m.Rank = external.Rank(s)
			i += n
		default:
			n, err := wire.Skip(data[i:], tag, "external.Remote.Meta", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}
