// Code generated by kanon. DO NOT EDIT.
// source: choice.go

package stream

import (
	"io"
	"testing"

	"go.thesmos.sh/kanon"
	"go.thesmos.sh/kanon/internal/fixture/external"
	"go.thesmos.sh/kanon/kanontest"
)

// kanonSpecChoice describes Choice to the conformance suite.
var kanonSpecChoice = kanontest.Spec[Choice]{
	Fields: []kanontest.Field{
		{Name: "Small", Number: 1, Union: "Kind", Case: ChoiceKindSmall},
		{Name: "Items", Number: 2, Stream: true},
		{Name: "Large", Number: 3, Union: "Kind", Case: ChoiceKindLarge},
		{Name: "Tail", Number: 4},
	},
	Canonical: true,
	Stream: func(r io.Reader, size int64, m *Choice, opts kanon.StreamOptions) kanontest.Stream[Choice] {
		return kanonStreamChoice{NewChoiceStream(r, size, m, opts)}
	},
}

// TestKanonChoice runs the conformance suite on Choice.
func TestKanonChoice(t *testing.T) {
	kanontest.Run(t, kanonSpecChoice)
}

// BenchmarkKanonChoice measures the codec of Choice.
func BenchmarkKanonChoice(b *testing.B) {
	kanontest.Bench(b, kanonSpecChoice)
}

// FuzzKanonChoice fuzzes the decode of Choice.
func FuzzKanonChoice(f *testing.F) {
	kanontest.Fuzz(f, kanonSpecChoice)
}

// kanonStreamChoice adapts a ChoiceStream to kanontest.Stream.
type kanonStreamChoice struct {
	*ChoiceStream
}

// Next returns the number of the next streamed field of Choice.
func (s kanonStreamChoice) Next() (int, error) {
	f, err := s.ChoiceStream.Next()
	return int(f), err
}

// Decode decodes the next element of the streamed slice of Choice with the
// number num into e, a pointer to an element.
func (s kanonStreamChoice) Decode(num int, e any) error {
	switch num {
	case 2:
		return s.DecodeItems(e.(*Inner))
	}
	return io.EOF
}

// kanonSpecPick describes Pick to the conformance suite.
var kanonSpecPick = kanontest.Spec[Pick]{
	Fields: []kanontest.Field{
		{Name: "Number", Number: 1, Union: "Kind", Case: PickKindNumber},
		{Name: "Data", Number: 2, Stream: true},
		{Name: "Word", Number: 3, Union: "Kind", Case: PickKindWord},
		{Name: "Proofs", Number: 4, Stream: true},
	},
	Canonical: true,
	Stream: func(r io.Reader, size int64, m *Pick, opts kanon.StreamOptions) kanontest.Stream[Pick] {
		return kanonStreamPick{NewPickStream(r, size, m, opts)}
	},
}

// TestKanonPick runs the conformance suite on Pick.
func TestKanonPick(t *testing.T) {
	kanontest.Run(t, kanonSpecPick)
}

// BenchmarkKanonPick measures the codec of Pick.
func BenchmarkKanonPick(b *testing.B) {
	kanontest.Bench(b, kanonSpecPick)
}

// FuzzKanonPick fuzzes the decode of Pick.
func FuzzKanonPick(f *testing.F) {
	kanontest.Fuzz(f, kanonSpecPick)
}

// kanonStreamPick adapts a PickStream to kanontest.Stream.
type kanonStreamPick struct {
	*PickStream
}

// Next returns the number of the next streamed field of Pick.
func (s kanonStreamPick) Next() (int, error) {
	f, err := s.PickStream.Next()
	return int(f), err
}

// Decode decodes the next element of the streamed slice of Pick with the number
// num into e, a pointer to an element.
func (s kanonStreamPick) Decode(num int, e any) error {
	switch num {
	case 4:
		return s.DecodeProofs(e.(*external.Proof))
	}
	return io.EOF
}
