// Code generated by kanon. DO NOT EDIT.
// source: era.go

package validate

import (
	"go.thesmos.sh/kanon"
)

// The file compiles against a runtime that supports version 3 of the generator.
const (
	_ = kanon.EnforceVersion(3 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 3)
)

// ValidateKanon returns nil, since every value of Era is valid. kanon encodes a
// value of Era as a value of its underlying type uint64, ahead of the binary
// methods of Era, and does not call ValidateKanon on a value of Era that it
// encodes or decodes.
func (Era) ValidateKanon() error {
	return nil
}
