// Code generated by kanon. DO NOT EDIT.
// source: values.go

//kanon:numbers Values Level=1 Amount=2 Tick=3 Code=4 Ratio=5 Tags=6 Scores=7 Hash=8 Blob=9 Span=10 Port=25 Weight=12 Wave=13 Phase=14 Grade=15 Next=16 Codes=17 Pair=18 Index=19 Text=20 Count=21 Flag=11 Any=22 Checked=23 Fixed=24 Era=26
//kanon:numbers Values.Any Level=1 Tags=2
//kanon:numbers Values.Checked Grade=1

package validate

import (
	"io"
	"math"
	"slices"
	"strings"

	"go.thesmos.sh/kanon"
	"go.thesmos.sh/kanon/wire"
)

// The file compiles against a runtime that supports version 2 of the generator.
const (
	_ = kanon.EnforceVersion(2 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 2)
)

// The generated types implement kanon.Cloner.
var (
	_ kanon.Cloner[Values] = (*Values)(nil)
)

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Values) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Level != 0 {
		n += 1 + wire.SizeUvarint(uint64(m.Level))
	}
	if m.Amount != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.Amount)))
	}
	if m.Tick != 0 {
		n += 1 + wire.SizeUvarint(uint64(m.Tick))
	}
	if m.Code != "" {
		n += 1 + wire.SizeBytes(len(m.Code))
	}
	if math.Float64bits(float64(m.Ratio)) != 0 {
		n += 9
	}
	if len(m.Tags) > 0 {
		n += 1 + wire.SizeBytes(_values_sizeTags(m.Tags))
	}
	if len(m.Scores) > 0 {
		n += 1 + wire.SizeBytes(_values_sizeScores(m.Scores))
	}
	if m.Hash != (Hash{}) {
		n += 6
	}
	if len(m.Blob) > 0 {
		n += 1 + wire.SizeBytes(len(m.Blob))
	}
	if m.Span != (Span{}) {
		n += 1 + wire.SizeBytes(_values_sizeSpan(&m.Span))
	}
	if m.Port != 0 {
		n += 2 + wire.SizeUvarint(uint64(m.Port))
	}
	if math.Float32bits(float32(m.Weight)) != 0 {
		n += 5
	}
	if math.Float32bits(real(m.Wave))|math.Float32bits(imag(m.Wave)) != 0 {
		n += 9
	}
	if math.Float64bits(real(m.Phase))|math.Float64bits(imag(m.Phase)) != 0 {
		n += 18
	}
	if m.Grade != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.Grade)))
	}
	if m.Next != nil {
		n += 2 + wire.SizeUvarint(uint64(*m.Next))
	}
	if len(m.Codes) > 0 {
		n += 2 + wire.SizeBytes(_values_sizeSliceCode(m.Codes))
	}
	if m.Pair != ([2]Amount{}) {
		n += 2 + wire.SizeBytes(_values_sizeArray2Amount(&m.Pair))
	}
	if len(m.Index) > 0 {
		n += 2 + wire.SizeBytes(_values_sizeMapCodeLevel(m.Index))
	}
	switch m.Kind {
	case KindText:
		n += 2 + wire.SizeBytes(len(m.Text))
	case KindCount:
		n += 2 + wire.SizeUvarint(uint64(m.Count))
	case KindFlag:
		n += 2
	}
	if m.Any != nil {
		n += 2 + wire.SizeBytes(_values_sizeAny(m.Any))
	}
	if m.Checked != nil {
		n += 2 + wire.SizeBytes(_values_sizeValid(m.Checked))
	}
	if m.Fixed != 0 {
		n += 10
	}
	if m.Era != 0 {
		n += 2 + wire.SizeUvarint(uint64(m.Era))
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer. It
// fails when the value of a field fails to encode: a type that encodes itself
// returns an error, ValidateKanon of a type rejects a value, an interface
// stores a type that the tag option types of its field does not list, or a map
// has a key with a NaN component or two keys of one projection.
func (m *Values) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. It fails when the value of a field
// fails to encode: a type that encodes itself returns an error, ValidateKanon
// of a type rejects a value, an interface stores a type that the tag option
// types of its field does not list, or a map has a key with a NaN component or
// two keys of one projection.
func (m *Values) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if m.Era != 0 {
		i = wire.PutUvarint(buf, i, uint64(m.Era))
		i = wire.PutTag(buf, i, 26<<3|wire.Varint)
	}
	if m.Port != 0 {
		if err := m.Port.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Port", 25)
		}
		i = wire.PutUvarint(buf, i, uint64(m.Port))
		i = wire.PutTag(buf, i, 25<<3|wire.Varint)
	}
	if m.Fixed != 0 {
		if err := m.Fixed.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Fixed", 24)
		}
		i = wire.PutUint64(buf, i, uint64(m.Fixed))
		i = wire.PutTag(buf, i, 24<<3|wire.Fixed64)
	}
	if m.Checked != nil {
		end := i
		w, err := _values_putValid(buf[:i], m.Checked, "Values.Checked", 23)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutUvarint(buf, i, uint64(end-i))
		i = wire.PutTag(buf, i, 23<<3|wire.Bytes)
	}
	if m.Any != nil {
		end := i
		w, err := _values_putAny(buf[:i], m.Any, "Values.Any", 22)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutUvarint(buf, i, uint64(end-i))
		i = wire.PutTag(buf, i, 22<<3|wire.Bytes)
	}
	switch m.Kind {
	case KindText:
		if err := m.Text.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Text", 20)
		}
		i = wire.PutRaw(buf, i, m.Text)
		i = wire.PutUvarint(buf, i, uint64(len(m.Text)))
		i = wire.PutTag(buf, i, 20<<3|wire.Bytes)
	case KindCount:
		if err := m.Count.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Count", 21)
		}
		i = wire.PutUvarint(buf, i, uint64(m.Count))
		i = wire.PutTag(buf, i, 21<<3|wire.Varint)
	}
	if len(m.Index) > 0 {
		w, err := _values_putMapCodeLevel(buf[:i], m.Index, "Values.Index", 19)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 19<<3|wire.Bytes)
	}
	if m.Pair != ([2]Amount{}) {
		w, err := _values_putArray2Amount(buf[:i], &m.Pair, "Values.Pair", 18)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 18<<3|wire.Bytes)
	}
	if len(m.Codes) > 0 {
		w, err := _values_putSliceCode(buf[:i], m.Codes, "Values.Codes", 17)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 17<<3|wire.Bytes)
	}
	if m.Next != nil {
		if err := m.Next.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Next", 16)
		}
		i = wire.PutUvarint(buf, i, uint64(*m.Next))
		i = wire.PutTag(buf, i, 16<<3|wire.Varint)
	}
	if m.Grade != 0 {
		if err := m.Grade.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Grade", 15)
		}
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.Grade)))
		i = wire.PutTag(buf, i, 15<<3|wire.Varint)
	}
	if math.Float64bits(real(m.Phase))|math.Float64bits(imag(m.Phase)) != 0 {
		if err := m.Phase.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Phase", 14)
		}
		i = wire.PutUint64(buf, i, math.Float64bits(imag(m.Phase)))
		i = wire.PutUint64(buf, i, math.Float64bits(real(m.Phase)))
		i = wire.PutUvarint(buf, i, 16)
		i = wire.PutTag(buf, i, 14<<3|wire.Bytes)
	}
	if math.Float32bits(real(m.Wave))|math.Float32bits(imag(m.Wave)) != 0 {
		if err := m.Wave.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Wave", 13)
		}
		i = wire.PutUint32(buf, i, math.Float32bits(imag(m.Wave)))
		i = wire.PutUint32(buf, i, math.Float32bits(real(m.Wave)))
		i = wire.PutTag(buf, i, 13<<3|wire.Fixed64)
	}
	if math.Float32bits(float32(m.Weight)) != 0 {
		if err := m.Weight.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Weight", 12)
		}
		i = wire.PutUint32(buf, i, math.Float32bits(float32(m.Weight)))
		i = wire.PutTag(buf, i, 12<<3|wire.Fixed32)
	}
	if m.Kind == KindFlag {
		if err := m.Flag.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Flag", 11)
		}
		i = wire.PutBool(buf, i, bool(m.Flag))
		i = wire.PutTag(buf, i, 11<<3|wire.Varint)
	}
	if m.Span != (Span{}) {
		if err := m.Span.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Span", 10)
		}
		i -= _values_putSpan(buf[:i], &m.Span)
		i = wire.PutTag(buf, i, 10<<3|wire.Bytes)
	}
	if len(m.Blob) > 0 {
		if err := m.Blob.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Blob", 9)
		}
		i = wire.PutRaw(buf, i, m.Blob)
		i = wire.PutUvarint(buf, i, uint64(len(m.Blob)))
		i = wire.PutTag(buf, i, 9<<3|wire.Bytes)
	}
	if m.Hash != (Hash{}) {
		if err := m.Hash.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Hash", 8)
		}
		i = wire.PutRaw(buf, i, m.Hash[:])
		i = wire.PutUvarint(buf, i, uint64(len(m.Hash)))
		i = wire.PutTag(buf, i, 8<<3|wire.Bytes)
	}
	if len(m.Scores) > 0 {
		if err := m.Scores.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Scores", 7)
		}
		i -= _values_putScores(buf[:i], m.Scores)
		i = wire.PutTag(buf, i, 7<<3|wire.Bytes)
	}
	if len(m.Tags) > 0 {
		if err := m.Tags.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Tags", 6)
		}
		i -= _values_putTags(buf[:i], m.Tags)
		i = wire.PutTag(buf, i, 6<<3|wire.Bytes)
	}
	if math.Float64bits(float64(m.Ratio)) != 0 {
		if err := m.Ratio.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Ratio", 5)
		}
		i = wire.PutUint64(buf, i, math.Float64bits(float64(m.Ratio)))
		i = wire.PutTag(buf, i, 5<<3|wire.Fixed64)
	}
	if m.Code != "" {
		if err := m.Code.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Code", 4)
		}
		i = wire.PutRaw(buf, i, m.Code)
		i = wire.PutUvarint(buf, i, uint64(len(m.Code)))
		i = wire.PutTag(buf, i, 4<<3|wire.Bytes)
	}
	if m.Tick != 0 {
		if err := m.Tick.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Tick", 3)
		}
		i = wire.PutUvarint(buf, i, uint64(m.Tick))
		i = wire.PutTag(buf, i, 3<<3|wire.Varint)
	}
	if m.Amount != 0 {
		if err := m.Amount.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Amount", 2)
		}
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.Amount)))
		i = wire.PutTag(buf, i, 2<<3|wire.Varint)
	}
	if m.Level != 0 {
		if err := m.Level.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Values.Level", 1)
		}
		i = wire.PutUvarint(buf, i, uint64(m.Level))
		i = wire.PutTag(buf, i, 1<<3|wire.Varint)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. It fails
// when the value of a field fails to encode: a type that encodes itself returns
// an error, ValidateKanon of a type rejects a value, an interface stores a type
// that the tag option types of its field does not list, or a map has a key with
// a NaN component or two keys of one projection.
func (m *Values) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	if _, err := m.encodeKanon(out); err != nil {
		return b, err
	}
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. It fails when the value of a field fails to encode: a type that
// encodes itself returns an error, ValidateKanon of a type rejects a value, an
// interface stores a type that the tag option types of its field does not list,
// or a map has a key with a NaN component or two keys of one projection.
func (m *Values) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which copy data once.
func (m *Values) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Values) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Values) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Values
// call it.
func (m *Values) decodeKanon(data []byte, slab string, off, depth int) error {
	m.Level = 0
	m.Amount = 0
	m.Tick = 0
	m.Code = ""
	m.Ratio = 0
	m.Tags = m.Tags[:0]
	m.Hash = Hash{}
	m.Blob = m.Blob[:0]
	m.Span = Span{}
	m.Port = 0
	m.Weight = 0
	m.Wave = 0
	m.Phase = 0
	m.Grade = 0
	m.Codes = m.Codes[:0]
	m.Pair = [2]Amount{}
	m.Text = ""
	m.Count = 0
	m.Flag = false
	m.Fixed = 0
	m.Era = 0
	m.Kind = 0
	seen, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{})
	if seen[0]&(1<<0) == 0 {
		clear(m.Scores)
	}
	if seen[0]&(1<<1) == 0 {
		m.Next = nil
	}
	if seen[0]&(1<<2) == 0 {
		clear(m.Index)
	}
	if seen[0]&(1<<3) == 0 {
		m.Any = nil
	}
	if seen[0]&(1<<4) == 0 {
		m.Checked = nil
	}
	return err
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Values
// call it.
func (m *Values) mergeKanon(data []byte, slab string, off, depth int) error {
	_, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{^uint64(0)})
	return err
}

// fieldsKanon decodes the fields in data into m for decodeKanon and mergeKanon.
// The first occurrence of a tracked field whose bit in seen is clear decodes
// into the memory of the field, and every other occurrence merges. fieldsKanon
// returns seen with the bits of the tracked fields that data contains.
func (m *Values) fieldsKanon(data []byte, slab string, off, depth int, seen [1]uint64) ([1]uint64, error) {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return seen, wire.ReadError(n, "Values", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Varint {
				return seen, wire.FormatError(tag, wire.Varint, "Values.Level", off+at)
			}
			from := off + i
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Values.Level", 1, off+i)
			}
			if u != uint64(uint8(u)) {
				return seen, wire.RangeError(u, "uint8", "Values.Level", 1, off+i)
			}
			m.Level = Level(u)
			i += n
			if err := m.Level.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Level", 1, from)
			}
		case 2:
			if tag != 2<<3|wire.Varint {
				return seen, wire.FormatError(tag, wire.Varint, "Values.Amount", off+at)
			}
			from := off + i
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Values.Amount", 2, off+i)
			}
			m.Amount = Amount(wire.Unzigzag(u))
			i += n
			if err := m.Amount.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Amount", 2, from)
			}
		case 3:
			if tag != 3<<3|wire.Varint {
				return seen, wire.FormatError(tag, wire.Varint, "Values.Tick", off+at)
			}
			from := off + i
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Values.Tick", 3, off+i)
			}
			m.Tick = Tick(u)
			i += n
			if err := m.Tick.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Tick", 3, from)
			}
		case 4:
			if tag != 4<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Values.Code", off+at)
			}
			from := off + i
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Values.Code", 4, off+i)
			}
			i += n
			m.Code = Code(slab[off+i : off+i+int(l)])
			i += int(l)
			if err := m.Code.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Code", 4, from)
			}
		case 5:
			if tag != 5<<3|wire.Fixed64 {
				return seen, wire.FormatError(tag, wire.Fixed64, "Values.Ratio", off+at)
			}
			from := off + i
			u, n := wire.Uint64(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Values.Ratio", 5, off+i)
			}
			m.Ratio = Ratio(math.Float64frombits(u))
			i += n
			if err := m.Ratio.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Ratio", 5, from)
			}
		case 6:
			if tag != 6<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Values.Tags", off+at)
			}
			from := off + i
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Values.Tags", 6, off+i)
			}
			i += n
			if err := _values_readTags(&m.Tags, data[i:i+int(l)], slab, off+i, depth-1, "Values.Tags", 6); err != nil {
				return seen, err
			}
			i += int(l)
			if err := m.Tags.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Tags", 6, from)
			}
		case 7:
			if tag != 7<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Values.Scores", off+at)
			}
			from := off + i
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Values.Scores", 7, off+i)
			}
			i += n
			if err := _values_readScores(&m.Scores, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<0) == 0, "Values.Scores", 7); err != nil {
				return seen, err
			}
			i += int(l)
			if err := m.Scores.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Scores", 7, from)
			}
			seen[0] |= 1 << 0
		case 8:
			if tag != 8<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Values.Hash", off+at)
			}
			from := off + i
			l, n := wire.Uvarint(data[i:])
			if n > 0 && l != 4 {
				return seen, wire.LengthError(l, 4, "Values.Hash", 8, off+i)
			}
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Values.Hash", 8, off+i)
			}
			i += n
			i += copy(m.Hash[:], data[i:])
			if err := m.Hash.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Hash", 8, from)
			}
		case 9:
			if tag != 9<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Values.Blob", off+at)
			}
			from := off + i
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Values.Blob", 9, off+i)
			}
			i += n
			m.Blob = append(m.Blob[:0], data[i:i+int(l)]...)
			i += int(l)
			if err := m.Blob.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Blob", 9, from)
			}
		case 10:
			if tag != 10<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Values.Span", off+at)
			}
			from := off + i
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Values.Span", 10, off+i)
			}
			i += n
			if err := _values_readSpan(&m.Span, data[i:i+int(l)], slab, off+i, depth-1, "Values.Span", 10); err != nil {
				return seen, err
			}
			i += int(l)
			if err := m.Span.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Span", 10, from)
			}
		case 25:
			if tag != 25<<3|wire.Varint {
				return seen, wire.FormatError(tag, wire.Varint, "Values.Port", off+at)
			}
			from := off + i
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Values.Port", 25, off+i)
			}
			if u != uint64(uint16(u)) {
				return seen, wire.RangeError(u, "uint16", "Values.Port", 25, off+i)
			}
			m.Port = Port(u)
			i += n
			if err := m.Port.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Port", 25, from)
			}
		case 12:
			if tag != 12<<3|wire.Fixed32 {
				return seen, wire.FormatError(tag, wire.Fixed32, "Values.Weight", off+at)
			}
			from := off + i
			u, n := wire.Uint32(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Values.Weight", 12, off+i)
			}
			m.Weight = Weight(math.Float32frombits(u))
			i += n
			if err := m.Weight.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Weight", 12, from)
			}
		case 13:
			if tag != 13<<3|wire.Fixed64 {
				return seen, wire.FormatError(tag, wire.Fixed64, "Values.Wave", off+at)
			}
			from := off + i
			u, n := wire.Uint64(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Values.Wave", 13, off+i)
			}
			m.Wave = Wave(complex(math.Float32frombits(uint32(u)), math.Float32frombits(uint32(u>>32))))
			i += n
			if err := m.Wave.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Wave", 13, from)
			}
		case 14:
			if tag != 14<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Values.Phase", off+at)
			}
			from := off + i
			l, n := wire.Uvarint(data[i:])
			if n > 0 && l != 16 {
				return seen, wire.LengthError(l, 16, "Values.Phase", 14, off+i)
			}
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Values.Phase", 14, off+i)
			}
			i += n
			re, _ := wire.Uint64(data[i:])
			im, _ := wire.Uint64(data[i+8:])
			m.Phase = Phase(complex(math.Float64frombits(re), math.Float64frombits(im)))
			i += 16
			if err := m.Phase.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Phase", 14, from)
			}
		case 15:
			if tag != 15<<3|wire.Varint {
				return seen, wire.FormatError(tag, wire.Varint, "Values.Grade", off+at)
			}
			from := off + i
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Values.Grade", 15, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int16(s)) {
				return seen, wire.RangeError(s, "int16", "Values.Grade", 15, off+i)
			}
			m.Grade = Grade(s)
			i += n
			if err := m.Grade.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Grade", 15, from)
			}
		case 16:
			if tag != 16<<3|wire.Varint {
				return seen, wire.FormatError(tag, wire.Varint, "Values.Next", off+at)
			}
			if depth < 1 {
				return seen, wire.DepthError("Values.Next", 16, off+i)
			}
			if m.Next == nil {
				m.Next = new(Level)
			}
			from := off + i
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Values.Next", 16, off+i)
			}
			if u != uint64(uint8(u)) {
				return seen, wire.RangeError(u, "uint8", "Values.Next", 16, off+i)
			}
			*m.Next = Level(u)
			i += n
			if err := m.Next.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Next", 16, from)
			}
			seen[0] |= 1 << 1
		case 17:
			if tag != 17<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Values.Codes", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Values.Codes", 17, off+i)
			}
			i += n
			if err := _values_readSliceCode(&m.Codes, data[i:i+int(l)], slab, off+i, depth-1, "Values.Codes", 17); err != nil {
				return seen, err
			}
			i += int(l)
		case 18:
			if tag != 18<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Values.Pair", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Values.Pair", 18, off+i)
			}
			i += n
			if err := _values_readArray2Amount(&m.Pair, data[i:i+int(l)], slab, off+i, depth-1, "Values.Pair", 18); err != nil {
				return seen, err
			}
			i += int(l)
		case 19:
			if tag != 19<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Values.Index", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Values.Index", 19, off+i)
			}
			i += n
			if err := _values_readMapCodeLevel(&m.Index, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<2) == 0, "Values.Index", 19); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 2
		case 20:
			if tag != 20<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Values.Text", off+at)
			}
			if m.Kind != KindText {
				_values_deselectValuesKind(m)
				m.Kind = KindText
			}
			from := off + i
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Values.Text", 20, off+i)
			}
			i += n
			m.Text = Code(slab[off+i : off+i+int(l)])
			i += int(l)
			if err := m.Text.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Text", 20, from)
			}
		case 21:
			if tag != 21<<3|wire.Varint {
				return seen, wire.FormatError(tag, wire.Varint, "Values.Count", off+at)
			}
			if m.Kind != KindCount {
				_values_deselectValuesKind(m)
				m.Kind = KindCount
			}
			from := off + i
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Values.Count", 21, off+i)
			}
			if u != uint64(uint8(u)) {
				return seen, wire.RangeError(u, "uint8", "Values.Count", 21, off+i)
			}
			m.Count = Level(u)
			i += n
			if err := m.Count.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Count", 21, from)
			}
		case 11:
			if tag != 11<<3|wire.Varint {
				return seen, wire.FormatError(tag, wire.Varint, "Values.Flag", off+at)
			}
			if m.Kind != KindFlag {
				_values_deselectValuesKind(m)
				m.Kind = KindFlag
			}
			from := off + i
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Values.Flag", 11, off+i)
			}
			m.Flag = Flag(u != 0)
			i += n
			if err := m.Flag.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Flag", 11, from)
			}
		case 22:
			if tag != 22<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Values.Any", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Values.Any", 22, off+i)
			}
			i += n
			used, err := _values_readAny(&m.Any, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<3) != 0, "Values.Any", 22)
			if err != nil {
				return seen, err
			}
			if used != int(l) {
				return seen, wire.TrailingError(int(l)-used, "Values.Any", 22, off+i+used)
			}
			i += int(l)
			seen[0] |= 1 << 3
		case 23:
			if tag != 23<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Values.Checked", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Values.Checked", 23, off+i)
			}
			i += n
			used, err := _values_readValid(&m.Checked, data[i:i+int(l)], slab, off+i, depth-1, "Values.Checked", 23)
			if err != nil {
				return seen, err
			}
			if used != int(l) {
				return seen, wire.TrailingError(int(l)-used, "Values.Checked", 23, off+i+used)
			}
			i += int(l)
			seen[0] |= 1 << 4
		case 24:
			if tag != 24<<3|wire.Fixed64 {
				return seen, wire.FormatError(tag, wire.Fixed64, "Values.Fixed", off+at)
			}
			from := off + i
			u, n := wire.Uint64(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Values.Fixed", 24, off+i)
			}
			m.Fixed = Tick(u)
			i += n
			if err := m.Fixed.ValidateKanon(); err != nil {
				return seen, wire.UnmarshalError(err, "Values.Fixed", 24, from)
			}
		case 26:
			if tag != 26<<3|wire.Varint {
				return seen, wire.FormatError(tag, wire.Varint, "Values.Era", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Values.Era", 26, off+i)
			}
			m.Era = Era(u)
			i += n
		default:
			n, err := wire.Skip(data[i:], tag, "Values", 0, off+at)
			if err != nil {
				return seen, err
			}
			i += n
		}
	}
	return seen, nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded content remains
// in m or in the storage that it keeps.
func (m *Values) Reset() {
	if m == nil {
		return
	}
	m.Level = 0
	m.Amount = 0
	m.Tick = 0
	m.Code = ""
	m.Ratio = 0
	clear(m.Tags[:cap(m.Tags)])
	m.Tags = m.Tags[:0]
	clear(m.Scores)
	m.Hash = Hash{}
	clear(m.Blob[:cap(m.Blob)])
	m.Blob = m.Blob[:0]
	m.Span = Span{}
	m.Port = 0
	m.Weight = 0
	m.Wave = 0
	m.Phase = 0
	m.Grade = 0
	m.Next = nil
	clear(m.Codes[:cap(m.Codes)])
	m.Codes = m.Codes[:0]
	m.Pair = [2]Amount{}
	clear(m.Index)
	m.Text = ""
	m.Count = 0
	m.Flag = false
	m.Any = nil
	m.Checked = nil
	m.Fixed = 0
	m.Era = 0
	m.Kind = 0
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Values) CloneKanon() *Values {
	if m == nil {
		return nil
	}
	c := new(Values)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Values call it.
func (m *Values) cloneKanon(c *Values) {
	c.Level = m.Level
	c.Amount = m.Amount
	c.Tick = m.Tick
	c.Code = Code(strings.Clone(string(m.Code)))
	c.Ratio = m.Ratio
	c.Tags = _values_cloneTags(m.Tags)
	c.Scores = _values_cloneScores(m.Scores)
	c.Hash = m.Hash
	c.Blob = slices.Clone(m.Blob)
	c.Span = m.Span
	c.Port = m.Port
	c.Weight = m.Weight
	c.Wave = m.Wave
	c.Phase = m.Phase
	c.Grade = m.Grade
	c.Next = _values_clonePtrLevel(m.Next)
	c.Codes = _values_cloneSliceCode(m.Codes)
	c.Pair = m.Pair
	c.Index = _values_cloneMapCodeLevel(m.Index)
	c.Text = Code(strings.Clone(string(m.Text)))
	c.Count = m.Count
	c.Flag = m.Flag
	c.Any = _values_cloneAny(m.Any)
	c.Checked = _values_cloneValid(m.Checked)
	c.Fixed = m.Fixed
	c.Era = m.Era
	c.Kind = m.Kind
}

// ValuesView is the encoding of a Values. Each method reads one field by
// scanning the encoding, without decoding the rest, and returns the zero value
// when the encoding has no such field, and the last value when it has several.
// A method of a struct fails with kanon.ErrRepeatedView for a second occurrence
// instead, since a decode merges the occurrences. The bytes that a method
// returns for a string, a byte slice and a struct alias the view. A value of a
// type that encodes itself decodes with the method of its type, and the offsets
// of the errors of a method are offsets in the view. IndexKanon reads the
// fields of the view with one scan.
type ValuesView []byte

// Level returns the value of the field Level of the encoding in v. It returns
// the error of ValidateKanon for a value that the method rejects.
func (v ValuesView) Level() (Level, error) {
	i, err := wire.Find(v, 1<<3|wire.Varint, "Values.Level")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uvarint(v[i:])
	if u != uint64(uint8(u)) {
		return 0, wire.RangeError(u, "uint8", "Values.Level", 1, i)
	}
	x := Level(u)
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Level", 1, i)
	}
	return x, nil
}

// Amount returns the value of the field Amount of the encoding in v. It returns
// the error of ValidateKanon for a value that the method rejects.
func (v ValuesView) Amount() (Amount, error) {
	i, err := wire.Find(v, 2<<3|wire.Varint, "Values.Amount")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uvarint(v[i:])
	x := Amount(wire.Unzigzag(u))
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Amount", 2, i)
	}
	return x, nil
}

// Tick returns the value of the field Tick of the encoding in v. It returns the
// error of ValidateKanon for a value that the method rejects.
func (v ValuesView) Tick() (Tick, error) {
	i, err := wire.Find(v, 3<<3|wire.Varint, "Values.Tick")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uvarint(v[i:])
	x := Tick(u)
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Tick", 3, i)
	}
	return x, nil
}

// Code returns the value of the field Code of the encoding in v. It returns the
// error of ValidateKanon for a value that the method rejects.
func (v ValuesView) Code() (Code, error) {
	i, err := wire.Find(v, 4<<3|wire.Bytes, "Values.Code")
	if err != nil || i < 0 {
		return "", err
	}
	l, n := wire.Uvarint(v[i:])
	x := Code(v[i+n : i+n+int(l)])
	if err := x.ValidateKanon(); err != nil {
		return "", wire.UnmarshalError(err, "Values.Code", 4, i)
	}
	return x, nil
}

// Ratio returns the value of the field Ratio of the encoding in v. It returns
// the error of ValidateKanon for a value that the method rejects.
func (v ValuesView) Ratio() (Ratio, error) {
	i, err := wire.Find(v, 5<<3|wire.Fixed64, "Values.Ratio")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uint64(v[i:])
	x := Ratio(math.Float64frombits(u))
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Ratio", 5, i)
	}
	return x, nil
}

// Hash returns the value of the field Hash of the encoding in v. It returns the
// error of ValidateKanon for a value that the method rejects.
func (v ValuesView) Hash() (Hash, error) {
	i, err := wire.Find(v, 8<<3|wire.Bytes, "Values.Hash")
	if err != nil || i < 0 {
		return Hash{}, err
	}
	l, n := wire.Uvarint(v[i:])
	if l != 4 {
		return Hash{}, wire.LengthError(l, 4, "Values.Hash", 8, i)
	}
	var x Hash
	copy(x[:], v[i+n:])
	if err := x.ValidateKanon(); err != nil {
		return Hash{}, wire.UnmarshalError(err, "Values.Hash", 8, i)
	}
	return x, nil
}

// Blob returns the value of the field Blob of the encoding in v. It returns the
// error of ValidateKanon for a value that the method rejects.
func (v ValuesView) Blob() (Blob, error) {
	i, err := wire.Find(v, 9<<3|wire.Bytes, "Values.Blob")
	if err != nil || i < 0 {
		return nil, err
	}
	l, n := wire.Uvarint(v[i:])
	x := Blob(v[i+n : i+n+int(l)])
	if err := x.ValidateKanon(); err != nil {
		return nil, wire.UnmarshalError(err, "Values.Blob", 9, i)
	}
	return x, nil
}

// Port returns the value of the field Port of the encoding in v. It returns the
// error of ValidateKanon for a value that the method rejects.
func (v ValuesView) Port() (Port, error) {
	i, err := wire.Find(v, 25<<3|wire.Varint, "Values.Port")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uvarint(v[i:])
	if u != uint64(uint16(u)) {
		return 0, wire.RangeError(u, "uint16", "Values.Port", 25, i)
	}
	x := Port(u)
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Port", 25, i)
	}
	return x, nil
}

// Weight returns the value of the field Weight of the encoding in v. It returns
// the error of ValidateKanon for a value that the method rejects.
func (v ValuesView) Weight() (Weight, error) {
	i, err := wire.Find(v, 12<<3|wire.Fixed32, "Values.Weight")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uint32(v[i:])
	x := Weight(math.Float32frombits(u))
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Weight", 12, i)
	}
	return x, nil
}

// Wave returns the value of the field Wave of the encoding in v. It returns the
// error of ValidateKanon for a value that the method rejects.
func (v ValuesView) Wave() (Wave, error) {
	i, err := wire.Find(v, 13<<3|wire.Fixed64, "Values.Wave")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uint64(v[i:])
	x := Wave(complex(math.Float32frombits(uint32(u)), math.Float32frombits(uint32(u>>32))))
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Wave", 13, i)
	}
	return x, nil
}

// Phase returns the value of the field Phase of the encoding in v. It returns
// the error of ValidateKanon for a value that the method rejects.
func (v ValuesView) Phase() (Phase, error) {
	i, err := wire.Find(v, 14<<3|wire.Bytes, "Values.Phase")
	if err != nil || i < 0 {
		return 0, err
	}
	l, n := wire.Uvarint(v[i:])
	if l != 16 {
		return 0, wire.LengthError(l, 16, "Values.Phase", 14, i)
	}
	re, _ := wire.Uint64(v[i+n:])
	im, _ := wire.Uint64(v[i+n+8:])
	x := Phase(complex(math.Float64frombits(re), math.Float64frombits(im)))
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Phase", 14, i)
	}
	return x, nil
}

// Grade returns the value of the field Grade of the encoding in v. It returns
// the error of ValidateKanon for a value that the method rejects.
func (v ValuesView) Grade() (Grade, error) {
	i, err := wire.Find(v, 15<<3|wire.Varint, "Values.Grade")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uvarint(v[i:])
	s := wire.Unzigzag(u)
	if s != int64(int16(s)) {
		return 0, wire.RangeError(s, "int16", "Values.Grade", 15, i)
	}
	x := Grade(s)
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Grade", 15, i)
	}
	return x, nil
}

// Next returns the value of the field Next of the encoding in v. It returns the
// error of ValidateKanon for a value that the method rejects.
func (v ValuesView) Next() (Level, error) {
	i, err := wire.Find(v, 16<<3|wire.Varint, "Values.Next")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uvarint(v[i:])
	if u != uint64(uint8(u)) {
		return 0, wire.RangeError(u, "uint8", "Values.Next", 16, i)
	}
	x := Level(u)
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Next", 16, i)
	}
	return x, nil
}

// Fixed returns the value of the field Fixed of the encoding in v. It returns
// the error of ValidateKanon for a value that the method rejects.
func (v ValuesView) Fixed() (Tick, error) {
	i, err := wire.Find(v, 24<<3|wire.Fixed64, "Values.Fixed")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uint64(v[i:])
	x := Tick(u)
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Fixed", 24, i)
	}
	return x, nil
}

// Era returns the value of the field Era of the encoding in v.
func (v ValuesView) Era() (Era, error) {
	i, err := wire.Find(v, 26<<3|wire.Varint, "Values.Era")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uvarint(v[i:])
	return Era(u), nil
}

// ValuesIndex is the index of a ValuesView: the view and the offsets of the
// values of the fields that its methods read, which IndexKanon records in one
// scan. Each method of ValuesIndex returns what the method of ValuesView of the
// same name returns, without a scan.
type ValuesIndex struct {
	v ValuesView
	// at records, per method, 1 + the offset of the value of the last
	// occurrence of its field, and 0 when the encoding has none.
	at [15]int
}

// IndexKanon returns the index of the encoding in v, from one scan of the
// encoding. It fails where a method of ValuesView fails before it reads a
// value: at a malformed tag or value, at an occurrence of a field that a method
// reads with another wire format, and at the second occurrence of a struct
// field.
func (v ValuesView) IndexKanon() (ValuesIndex, error) {
	ix := ValuesIndex{v: v}
	for i := 0; i < len(v); {
		at := i
		tag, n := wire.Uvarint(v[i:])
		if n <= 0 {
			return ValuesIndex{}, wire.ReadError(n, "Values", 0, i)
		}
		i += n
		skipped, err := wire.Skip(v[i:], tag, "Values", 0, at)
		if err != nil {
			return ValuesIndex{}, err
		}
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Varint {
				return ValuesIndex{}, wire.FormatError(tag, wire.Varint, "Values.Level", at)
			}
			ix.at[0] = i + 1
		case 2:
			if tag != 2<<3|wire.Varint {
				return ValuesIndex{}, wire.FormatError(tag, wire.Varint, "Values.Amount", at)
			}
			ix.at[1] = i + 1
		case 3:
			if tag != 3<<3|wire.Varint {
				return ValuesIndex{}, wire.FormatError(tag, wire.Varint, "Values.Tick", at)
			}
			ix.at[2] = i + 1
		case 4:
			if tag != 4<<3|wire.Bytes {
				return ValuesIndex{}, wire.FormatError(tag, wire.Bytes, "Values.Code", at)
			}
			ix.at[3] = i + 1
		case 5:
			if tag != 5<<3|wire.Fixed64 {
				return ValuesIndex{}, wire.FormatError(tag, wire.Fixed64, "Values.Ratio", at)
			}
			ix.at[4] = i + 1
		case 8:
			if tag != 8<<3|wire.Bytes {
				return ValuesIndex{}, wire.FormatError(tag, wire.Bytes, "Values.Hash", at)
			}
			ix.at[5] = i + 1
		case 9:
			if tag != 9<<3|wire.Bytes {
				return ValuesIndex{}, wire.FormatError(tag, wire.Bytes, "Values.Blob", at)
			}
			ix.at[6] = i + 1
		case 25:
			if tag != 25<<3|wire.Varint {
				return ValuesIndex{}, wire.FormatError(tag, wire.Varint, "Values.Port", at)
			}
			ix.at[7] = i + 1
		case 12:
			if tag != 12<<3|wire.Fixed32 {
				return ValuesIndex{}, wire.FormatError(tag, wire.Fixed32, "Values.Weight", at)
			}
			ix.at[8] = i + 1
		case 13:
			if tag != 13<<3|wire.Fixed64 {
				return ValuesIndex{}, wire.FormatError(tag, wire.Fixed64, "Values.Wave", at)
			}
			ix.at[9] = i + 1
		case 14:
			if tag != 14<<3|wire.Bytes {
				return ValuesIndex{}, wire.FormatError(tag, wire.Bytes, "Values.Phase", at)
			}
			ix.at[10] = i + 1
		case 15:
			if tag != 15<<3|wire.Varint {
				return ValuesIndex{}, wire.FormatError(tag, wire.Varint, "Values.Grade", at)
			}
			ix.at[11] = i + 1
		case 16:
			if tag != 16<<3|wire.Varint {
				return ValuesIndex{}, wire.FormatError(tag, wire.Varint, "Values.Next", at)
			}
			ix.at[12] = i + 1
		case 24:
			if tag != 24<<3|wire.Fixed64 {
				return ValuesIndex{}, wire.FormatError(tag, wire.Fixed64, "Values.Fixed", at)
			}
			ix.at[13] = i + 1
		case 26:
			if tag != 26<<3|wire.Varint {
				return ValuesIndex{}, wire.FormatError(tag, wire.Varint, "Values.Era", at)
			}
			ix.at[14] = i + 1
		}
		i += skipped
	}
	return ix, nil
}

// Level returns the value of the field Level, as ValuesView.Level returns it,
// at the offset that the index records.
func (ix ValuesIndex) Level() (Level, error) {
	v, i := ix.v, ix.at[0]-1
	if i < 0 {
		return 0, nil
	}
	u, _ := wire.Uvarint(v[i:])
	if u != uint64(uint8(u)) {
		return 0, wire.RangeError(u, "uint8", "Values.Level", 1, i)
	}
	x := Level(u)
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Level", 1, i)
	}
	return x, nil
}

// Amount returns the value of the field Amount, as ValuesView.Amount returns
// it, at the offset that the index records.
func (ix ValuesIndex) Amount() (Amount, error) {
	v, i := ix.v, ix.at[1]-1
	if i < 0 {
		return 0, nil
	}
	u, _ := wire.Uvarint(v[i:])
	x := Amount(wire.Unzigzag(u))
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Amount", 2, i)
	}
	return x, nil
}

// Tick returns the value of the field Tick, as ValuesView.Tick returns it, at
// the offset that the index records.
func (ix ValuesIndex) Tick() (Tick, error) {
	v, i := ix.v, ix.at[2]-1
	if i < 0 {
		return 0, nil
	}
	u, _ := wire.Uvarint(v[i:])
	x := Tick(u)
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Tick", 3, i)
	}
	return x, nil
}

// Code returns the value of the field Code, as ValuesView.Code returns it, at
// the offset that the index records.
func (ix ValuesIndex) Code() (Code, error) {
	v, i := ix.v, ix.at[3]-1
	if i < 0 {
		return "", nil
	}
	l, n := wire.Uvarint(v[i:])
	x := Code(v[i+n : i+n+int(l)])
	if err := x.ValidateKanon(); err != nil {
		return "", wire.UnmarshalError(err, "Values.Code", 4, i)
	}
	return x, nil
}

// Ratio returns the value of the field Ratio, as ValuesView.Ratio returns it,
// at the offset that the index records.
func (ix ValuesIndex) Ratio() (Ratio, error) {
	v, i := ix.v, ix.at[4]-1
	if i < 0 {
		return 0, nil
	}
	u, _ := wire.Uint64(v[i:])
	x := Ratio(math.Float64frombits(u))
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Ratio", 5, i)
	}
	return x, nil
}

// Hash returns the value of the field Hash, as ValuesView.Hash returns it, at
// the offset that the index records.
func (ix ValuesIndex) Hash() (Hash, error) {
	v, i := ix.v, ix.at[5]-1
	if i < 0 {
		return Hash{}, nil
	}
	l, n := wire.Uvarint(v[i:])
	if l != 4 {
		return Hash{}, wire.LengthError(l, 4, "Values.Hash", 8, i)
	}
	var x Hash
	copy(x[:], v[i+n:])
	if err := x.ValidateKanon(); err != nil {
		return Hash{}, wire.UnmarshalError(err, "Values.Hash", 8, i)
	}
	return x, nil
}

// Blob returns the value of the field Blob, as ValuesView.Blob returns it, at
// the offset that the index records.
func (ix ValuesIndex) Blob() (Blob, error) {
	v, i := ix.v, ix.at[6]-1
	if i < 0 {
		return nil, nil
	}
	l, n := wire.Uvarint(v[i:])
	x := Blob(v[i+n : i+n+int(l)])
	if err := x.ValidateKanon(); err != nil {
		return nil, wire.UnmarshalError(err, "Values.Blob", 9, i)
	}
	return x, nil
}

// Port returns the value of the field Port, as ValuesView.Port returns it, at
// the offset that the index records.
func (ix ValuesIndex) Port() (Port, error) {
	v, i := ix.v, ix.at[7]-1
	if i < 0 {
		return 0, nil
	}
	u, _ := wire.Uvarint(v[i:])
	if u != uint64(uint16(u)) {
		return 0, wire.RangeError(u, "uint16", "Values.Port", 25, i)
	}
	x := Port(u)
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Port", 25, i)
	}
	return x, nil
}

// Weight returns the value of the field Weight, as ValuesView.Weight returns
// it, at the offset that the index records.
func (ix ValuesIndex) Weight() (Weight, error) {
	v, i := ix.v, ix.at[8]-1
	if i < 0 {
		return 0, nil
	}
	u, _ := wire.Uint32(v[i:])
	x := Weight(math.Float32frombits(u))
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Weight", 12, i)
	}
	return x, nil
}

// Wave returns the value of the field Wave, as ValuesView.Wave returns it, at
// the offset that the index records.
func (ix ValuesIndex) Wave() (Wave, error) {
	v, i := ix.v, ix.at[9]-1
	if i < 0 {
		return 0, nil
	}
	u, _ := wire.Uint64(v[i:])
	x := Wave(complex(math.Float32frombits(uint32(u)), math.Float32frombits(uint32(u>>32))))
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Wave", 13, i)
	}
	return x, nil
}

// Phase returns the value of the field Phase, as ValuesView.Phase returns it,
// at the offset that the index records.
func (ix ValuesIndex) Phase() (Phase, error) {
	v, i := ix.v, ix.at[10]-1
	if i < 0 {
		return 0, nil
	}
	l, n := wire.Uvarint(v[i:])
	if l != 16 {
		return 0, wire.LengthError(l, 16, "Values.Phase", 14, i)
	}
	re, _ := wire.Uint64(v[i+n:])
	im, _ := wire.Uint64(v[i+n+8:])
	x := Phase(complex(math.Float64frombits(re), math.Float64frombits(im)))
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Phase", 14, i)
	}
	return x, nil
}

// Grade returns the value of the field Grade, as ValuesView.Grade returns it,
// at the offset that the index records.
func (ix ValuesIndex) Grade() (Grade, error) {
	v, i := ix.v, ix.at[11]-1
	if i < 0 {
		return 0, nil
	}
	u, _ := wire.Uvarint(v[i:])
	s := wire.Unzigzag(u)
	if s != int64(int16(s)) {
		return 0, wire.RangeError(s, "int16", "Values.Grade", 15, i)
	}
	x := Grade(s)
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Grade", 15, i)
	}
	return x, nil
}

// Next returns the value of the field Next, as ValuesView.Next returns it, at
// the offset that the index records.
func (ix ValuesIndex) Next() (Level, error) {
	v, i := ix.v, ix.at[12]-1
	if i < 0 {
		return 0, nil
	}
	u, _ := wire.Uvarint(v[i:])
	if u != uint64(uint8(u)) {
		return 0, wire.RangeError(u, "uint8", "Values.Next", 16, i)
	}
	x := Level(u)
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Next", 16, i)
	}
	return x, nil
}

// Fixed returns the value of the field Fixed, as ValuesView.Fixed returns it,
// at the offset that the index records.
func (ix ValuesIndex) Fixed() (Tick, error) {
	v, i := ix.v, ix.at[13]-1
	if i < 0 {
		return 0, nil
	}
	u, _ := wire.Uint64(v[i:])
	x := Tick(u)
	if err := x.ValidateKanon(); err != nil {
		return 0, wire.UnmarshalError(err, "Values.Fixed", 24, i)
	}
	return x, nil
}

// Era returns the value of the field Era, as ValuesView.Era returns it, at the
// offset that the index records.
func (ix ValuesIndex) Era() (Era, error) {
	v, i := ix.v, ix.at[14]-1
	if i < 0 {
		return 0, nil
	}
	u, _ := wire.Uvarint(v[i:])
	return Era(u), nil
}

// _values_sizeTags returns the length of the encoding of the elements of x, a
// Tags.
func _values_sizeTags(x Tags) int {
	n := 0
	for k := range x {
		n += wire.SizeBytes(len(x[k]))
	}
	return n
}

// _values_sizeScores returns the length of the encoding of the keys and values
// of x, a Scores.
func _values_sizeScores(x Scores) int {
	n := 0
	var mk string
	var mv int32
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + wire.SizeUvarint(wire.Zigzag(int64(mv)))
	}
	return n
}

// _values_sizeSpan returns the length of the encoding of the elements of x, a
// Span.
func _values_sizeSpan(x *Span) int {
	n := 0
	for k := range x {
		n += wire.SizeUvarint(wire.Zigzag(int64(x[k])))
	}
	return n
}

// _values_sizeSliceCode returns the length of the encoding of the elements of
// x, a []Code.
func _values_sizeSliceCode(x []Code) int {
	n := 0
	for k := range x {
		n += wire.SizeBytes(len(x[k]))
	}
	return n
}

// _values_sizeArray2Amount returns the length of the encoding of the elements
// of x, a [2]Amount.
func _values_sizeArray2Amount(x *[2]Amount) int {
	n := 0
	for k := range x {
		n += wire.SizeUvarint(wire.Zigzag(int64(x[k])))
	}
	return n
}

// _values_sizeMapCodeLevel returns the length of the encoding of the keys and
// values of x, a map[Code]Level.
func _values_sizeMapCodeLevel(x map[Code]Level) int {
	n := 0
	var mk Code
	var mv Level
	for mk, mv = range x {
		n += wire.SizeBytes(len(mk)) + wire.SizeUvarint(uint64(mv))
	}
	return n
}

// _values_sizeAny returns the length of the encoding of x, a any: the number of
// its concrete type and its value. It returns 0 for a concrete type that the
// tag option types does not list, whose encode fails.
func _values_sizeAny(x any) int {
	switch x := x.(type) {
	case Level:
		return 1 + wire.SizeUvarint(uint64(x))
	case Tags:
		return 1 + wire.SizeBytes(_values_sizeTags(x))
	default:
		return 0
	}
}

// _values_sizeValid returns the length of the encoding of x, a Valid: the
// number of its concrete type and its value. It returns 0 for a concrete type
// that the tag option types does not list, whose encode fails.
func _values_sizeValid(x Valid) int {
	switch x := x.(type) {
	case Grade:
		return 1 + wire.SizeUvarint(wire.Zigzag(int64(x)))
	default:
		return 0
	}
}

// _values_putValid writes the encoding of x, a Valid, into the end of buf,
// which has room for it, and returns its length. It fails for a value that
// fails to encode, which loc and num locate.
func _values_putValid(buf []byte, x Valid, loc string, num int) (int, error) {
	i := len(buf)
	switch x := x.(type) {
	case Grade:
		if err := x.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, loc, num)
		}
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(x)))
		i = wire.PutUvarint(buf, i, 1)
	default:
		return 0, wire.UnlistedError(x, loc, num)
	}
	return len(buf) - i, nil
}

// _values_putAny writes the encoding of x, a any, into the end of buf, which
// has room for it, and returns its length. It fails for a value that fails to
// encode, which loc and num locate.
func _values_putAny(buf []byte, x any, loc string, num int) (int, error) {
	i := len(buf)
	switch x := x.(type) {
	case Level:
		if err := x.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, loc, num)
		}
		i = wire.PutUvarint(buf, i, uint64(x))
		i = wire.PutUvarint(buf, i, 1)
	case Tags:
		if err := x.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, loc, num)
		}
		i -= _values_putTags(buf[:i], x)
		i = wire.PutUvarint(buf, i, 2)
	default:
		return 0, wire.UnlistedError(x, loc, num)
	}
	return len(buf) - i, nil
}

// _values_putMapCodeLevel writes the encoding of x, a map[Code]Level, into the
// end of buf, which has room for it, and returns its length. It fails for a
// value that fails to encode, which loc and num locate.
func _values_putMapCodeLevel(buf []byte, x map[Code]Level, loc string, num int) (int, error) {
	i := len(buf)
	if len(x) <= 16 {
		type pair = wire.Pair[Code, Level]
		var arr [16]pair
		pairs := arr[:0]
		for mk, mv := range x {
			pairs = append(pairs, pair{Key: mk, Value: mv})
		}
		wire.SortPairs(pairs)
		for k := len(pairs) - 1; k >= 0; k-- {
			{
				if err := pairs[k].Value.ValidateKanon(); err != nil {
					return 0, wire.MarshalError(err, loc, num)
				}
				i = wire.PutUvarint(buf, i, uint64(pairs[k].Value))
			}
			{
				if err := pairs[k].Key.ValidateKanon(); err != nil {
					return 0, wire.MarshalError(err, loc, num)
				}
				i = wire.PutRaw(buf, i, pairs[k].Key)
				i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Key)))
			}
		}
	} else {
		keys := make([]Code, 0, len(x))
		for mk := range x {
			keys = append(keys, mk)
		}
		slices.Sort(keys)
		for k := len(keys) - 1; k >= 0; k-- {
			mk := keys[k]
			mv := x[mk]
			{
				if err := mv.ValidateKanon(); err != nil {
					return 0, wire.MarshalError(err, loc, num)
				}
				i = wire.PutUvarint(buf, i, uint64(mv))
			}
			{
				if err := mk.ValidateKanon(); err != nil {
					return 0, wire.MarshalError(err, loc, num)
				}
				i = wire.PutRaw(buf, i, mk)
				i = wire.PutUvarint(buf, i, uint64(len(mk)))
			}
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, nil
}

// _values_putArray2Amount writes the encoding of x, a [2]Amount, into the end
// of buf, which has room for it, and returns its length. It fails for a value
// that fails to encode, which loc and num locate.
func _values_putArray2Amount(buf []byte, x *[2]Amount, loc string, num int) (int, error) {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		if err := x[k].ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, loc, num)
		}
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(x[k])))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, nil
}

// _values_putSliceCode writes the encoding of x, a []Code, into the end of buf,
// which has room for it, and returns its length. It fails for a value that
// fails to encode, which loc and num locate.
func _values_putSliceCode(buf []byte, x []Code, loc string, num int) (int, error) {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		if err := x[k].ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, loc, num)
		}
		i = wire.PutRaw(buf, i, x[k])
		i = wire.PutUvarint(buf, i, uint64(len(x[k])))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, nil
}

// _values_putSpan writes the encoding of x, a Span, into the end of buf, which
// has room for it, and returns its length.
func _values_putSpan(buf []byte, x *Span) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(x[k])))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _values_putScores writes the encoding of x, a Scores, into the end of buf,
// which has room for it, and returns its length.
func _values_putScores(buf []byte, x Scores) int {
	i := len(buf)
	if len(x) <= 16 {
		type pair = wire.Pair[string, int32]
		var arr [16]pair
		pairs := arr[:0]
		for mk, mv := range x {
			pairs = append(pairs, pair{Key: mk, Value: mv})
		}
		wire.SortPairs(pairs)
		for k := len(pairs) - 1; k >= 0; k-- {
			i = wire.PutUvarint(buf, i, wire.Zigzag(int64(pairs[k].Value)))
			i = wire.PutRaw(buf, i, pairs[k].Key)
			i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Key)))
		}
	} else {
		keys := make([]string, 0, len(x))
		for mk := range x {
			keys = append(keys, mk)
		}
		slices.Sort(keys)
		for k := len(keys) - 1; k >= 0; k-- {
			mk := keys[k]
			mv := x[mk]
			i = wire.PutUvarint(buf, i, wire.Zigzag(int64(mv)))
			i = wire.PutRaw(buf, i, mk)
			i = wire.PutUvarint(buf, i, uint64(len(mk)))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _values_putTags writes the encoding of x, a Tags, into the end of buf, which
// has room for it, and returns its length.
func _values_putTags(buf []byte, x Tags) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutRaw(buf, i, x[k])
		i = wire.PutUvarint(buf, i, uint64(len(x[k])))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _values_readTags appends the elements that data encodes, a Tags without its
// length, to *dst. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _values_readTags(dst *Tags, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make(Tags, 0, wire.CountValues(data))
	}
	for i := 0; i < len(data); {
		x = append(x, "")
		last := len(x) - 1
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		x[last] = slab[off+i : off+i+int(l)]
		i += int(l)
	}
	*dst = x
	return nil
}

// _values_readScores adds the entries that data encodes, a Scores without its
// length, to *dst. With collect set, it clears *dst first, and the entries
// reuse the memory of up to 16 of its values. data starts at offset off of
// slab, and the decode enters depth levels below the value at most. loc and num
// locate the field in errors.
func _values_readScores(dst *Scores, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(Scores)
		*dst = x
	}
	var mk string
	var mv int32
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		{
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, loc, num, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int32(s)) {
				return wire.RangeError(s, "int32", loc, num, off+i)
			}
			mv = int32(s)
			i += n
		}
		x[mk] = mv
	}
	return nil
}

// _values_readSpan decodes the elements that data encodes, a Span without its
// length, into *dst. It fails unless data encodes exactly 2 elements. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _values_readSpan(dst *Span, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		u, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, loc, num, off+i)
		}
		s := wire.Unzigzag(u)
		if s != int64(int32(s)) {
			return wire.RangeError(s, "int32", loc, num, off+i)
		}
		dst[k] = int32(s)
		i += n
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}

// _values_readSliceCode appends the elements that data encodes, a []Code
// without its length, to *dst. data starts at offset off of slab, and the
// decode enters depth levels below the value at most. loc and num locate the
// field in errors.
func _values_readSliceCode(dst *[]Code, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]Code, 0, wire.CountValues(data))
	}
	for i := 0; i < len(data); {
		x = append(x, "")
		last := len(x) - 1
		from := off + i
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		x[last] = Code(slab[off+i : off+i+int(l)])
		i += int(l)
		if err := x[last].ValidateKanon(); err != nil {
			return wire.UnmarshalError(err, loc, num, from)
		}
	}
	*dst = x
	return nil
}

// _values_readArray2Amount decodes the elements that data encodes, a [2]Amount
// without its length, into *dst. It fails unless data encodes exactly 2
// elements. data starts at offset off of slab, and the decode enters depth
// levels below the value at most. loc and num locate the field in errors.
func _values_readArray2Amount(dst *[2]Amount, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		from := off + i
		u, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, loc, num, off+i)
		}
		dst[k] = Amount(wire.Unzigzag(u))
		i += n
		if err := dst[k].ValidateKanon(); err != nil {
			return wire.UnmarshalError(err, loc, num, from)
		}
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}

// _values_readMapCodeLevel adds the entries that data encodes, a map[Code]Level
// without its length, to *dst. With collect set, it clears *dst first, and the
// entries reuse the memory of up to 16 of its values. data starts at offset off
// of slab, and the decode enters depth levels below the value at most. loc and
// num locate the field in errors.
func _values_readMapCodeLevel(dst *map[Code]Level, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[Code]Level)
		*dst = x
	}
	var mk Code
	var mv Level
	for i := 0; i < len(data); {
		{
			from := off + i
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mk = Code(slab[off+i : off+i+int(l)])
			i += int(l)
			if err := mk.ValidateKanon(); err != nil {
				return wire.UnmarshalError(err, loc, num, from)
			}
		}
		{
			from := off + i
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, loc, num, off+i)
			}
			if u != uint64(uint8(u)) {
				return wire.RangeError(u, "uint8", loc, num, off+i)
			}
			mv = Level(u)
			i += n
			if err := mv.ValidateKanon(); err != nil {
				return wire.UnmarshalError(err, loc, num, from)
			}
		}
		x[mk] = mv
	}
	return nil
}

// _values_deselectValuesKind zeroes the member of the union of Values.Kind that
// the discriminator selects.
func _values_deselectValuesKind(m *Values) {
	switch m.Kind {
	case KindText:
		m.Text = ""
	case KindCount:
		m.Count = 0
	case KindFlag:
		m.Flag = false
	}
}

// _values_readAny decodes the any at the start of data into *dst and returns
// the length of its encoding: the number of its concrete type and the value of
// that type, into the value that *dst stores when it has that type. It fails
// for a type number that the list does not name. With merge set, a value of the
// concrete type that *dst stores merges into it when the type merges, as a
// repeated field merges. data starts at offset off of slab, and the decode
// enters depth levels below the value at most. loc and num locate the field in
// errors.
func _values_readAny(dst *any, data []byte, slab string, off, depth int, merge bool, loc string, num int) (int, error) {
	if depth < 0 {
		return 0, wire.DepthError(loc, num, off)
	}
	t, i := wire.Uvarint(data)
	if i <= 0 {
		return 0, wire.ReadError(i, loc, num, off)
	}
	switch t {
	case 0:
		*dst = nil
	case 1:
		var x Level
		from := off + i
		u, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return 0, wire.ReadError(n, loc, num, off+i)
		}
		if u != uint64(uint8(u)) {
			return 0, wire.RangeError(u, "uint8", loc, num, off+i)
		}
		x = Level(u)
		i += n
		if err := x.ValidateKanon(); err != nil {
			return 0, wire.UnmarshalError(err, loc, num, from)
		}
		*dst = x
	case 2:
		x, _ := (*dst).(Tags)
		from := off + i
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return 0, wire.ReadError(n, loc, num, off+i)
		}
		i += n
		if !merge {
			x = x[:0]
		}
		if err := _values_readTags(&x, data[i:i+int(l)], slab, off+i, depth-1, loc, num); err != nil {
			return 0, err
		}
		i += int(l)
		if err := x.ValidateKanon(); err != nil {
			return 0, wire.UnmarshalError(err, loc, num, from)
		}
		*dst = x
	default:
		return 0, wire.TypeError(t, loc, num, off)
	}
	return i, nil
}

// _values_readValid decodes the Valid at the start of data into *dst and
// returns the length of its encoding: the number of its concrete type and the
// value of that type, into the value that *dst stores when it has that type. It
// fails for a type number that the list does not name. data starts at offset
// off of slab, and the decode enters depth levels below the value at most. loc
// and num locate the field in errors.
func _values_readValid(dst *Valid, data []byte, slab string, off, depth int, loc string, num int) (int, error) {
	if depth < 0 {
		return 0, wire.DepthError(loc, num, off)
	}
	t, i := wire.Uvarint(data)
	if i <= 0 {
		return 0, wire.ReadError(i, loc, num, off)
	}
	switch t {
	case 0:
		*dst = nil
	case 1:
		var x Grade
		from := off + i
		u, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return 0, wire.ReadError(n, loc, num, off+i)
		}
		s := wire.Unzigzag(u)
		if s != int64(int16(s)) {
			return 0, wire.RangeError(s, "int16", loc, num, off+i)
		}
		x = Grade(s)
		i += n
		if err := x.ValidateKanon(); err != nil {
			return 0, wire.UnmarshalError(err, loc, num, from)
		}
		*dst = x
	default:
		return 0, wire.TypeError(t, loc, num, off)
	}
	return i, nil
}

// _values_cloneTags returns a copy of x, a Tags, and nil for a nil x.
func _values_cloneTags(x Tags) Tags {
	if x == nil {
		return nil
	}
	c := make(Tags, len(x))
	for k := range x {
		c[k] = strings.Clone(x[k])
	}
	return c
}

// _values_cloneScores returns a copy of x, a Scores, and nil for a nil x.
func _values_cloneScores(x Scores) Scores {
	if x == nil {
		return nil
	}
	c := make(Scores, len(x))
	for mk, mv := range x {
		c[strings.Clone(mk)] = mv
	}
	return c
}

// _values_clonePtrLevel returns a pointer to a copy of the value that x, a
// *Level, points at, and nil for a nil x.
func _values_clonePtrLevel(x *Level) *Level {
	if x == nil {
		return nil
	}
	return new(*x)
}

// _values_cloneSliceCode returns a copy of x, a []Code, and nil for a nil x.
func _values_cloneSliceCode(x []Code) []Code {
	if x == nil {
		return nil
	}
	c := make([]Code, len(x))
	for k := range x {
		c[k] = Code(strings.Clone(string(x[k])))
	}
	return c
}

// _values_cloneMapCodeLevel returns a copy of x, a map[Code]Level, and nil for
// a nil x.
func _values_cloneMapCodeLevel(x map[Code]Level) map[Code]Level {
	if x == nil {
		return nil
	}
	c := make(map[Code]Level, len(x))
	for mk, mv := range x {
		c[Code(strings.Clone(string(mk)))] = mv
	}
	return c
}

// _values_cloneAny returns a copy of the value that x, a any, stores. A value
// of a type that the tag option types does not list, whose encode fails, is not
// copied.
func _values_cloneAny(x any) any {
	switch x := x.(type) {
	case Level:
		return x
	case Tags:
		return _values_cloneTags(x)
	default:
		return x
	}
}

// _values_cloneValid returns a copy of the value that x, a Valid, stores. A
// value of a type that the tag option types does not list, whose encode fails,
// is not copied.
func _values_cloneValid(x Valid) Valid {
	switch x := x.(type) {
	case Grade:
		return x
	default:
		return x
	}
}
