// Code generated by kanon. DO NOT EDIT.
// source: bytes.go

//kanon:numbers ByteArrays Byte0=1 Byte1=2 Byte32=3 Byte127=4 Byte128=5 Digest=6

package array

import (
	"io"
	"slices"

	"go.thesmos.sh/kanon"
	"go.thesmos.sh/kanon/wire"
)

// The file compiles against a runtime that supports version 1 of the generator.
const (
	_ = kanon.EnforceVersion(1 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 1)
)

// The generated types implement kanon.Cloner.
var (
	_ kanon.Cloner[ByteArrays] = (*ByteArrays)(nil)
)

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *ByteArrays) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Byte1 != ([2][1]byte{}) {
		n += 6
	}
	if m.Byte32 != ([2][32]byte{}) {
		n += 68
	}
	if m.Byte127 != ([2][127]byte{}) {
		n += 259
	}
	if m.Byte128 != ([2][128]byte{}) {
		n += 263
	}
	if m.Digest != ([2]Digest{}) {
		n += 68
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer.
// The error is always nil.
func (m *ByteArrays) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. The error is always nil.
func (m *ByteArrays) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if m.Digest != ([2]Digest{}) {
		i -= _bytes_putArray2Digest(buf[:i], &m.Digest)
		i = wire.PutTag(buf, i, 6<<3|wire.Bytes)
	}
	if m.Byte128 != ([2][128]byte{}) {
		i -= _bytes_putArray2Array128Byte(buf[:i], &m.Byte128)
		i = wire.PutTag(buf, i, 5<<3|wire.Bytes)
	}
	if m.Byte127 != ([2][127]byte{}) {
		i -= _bytes_putArray2Array127Byte(buf[:i], &m.Byte127)
		i = wire.PutTag(buf, i, 4<<3|wire.Bytes)
	}
	if m.Byte32 != ([2][32]byte{}) {
		i -= _bytes_putArray2Array32Byte(buf[:i], &m.Byte32)
		i = wire.PutTag(buf, i, 3<<3|wire.Bytes)
	}
	if m.Byte1 != ([2][1]byte{}) {
		i -= _bytes_putArray2Array1Byte(buf[:i], &m.Byte1)
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. The error
// is always nil.
func (m *ByteArrays) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	m.encodeKanon(out)
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. The error is always nil.
func (m *ByteArrays) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which do not copy data, since ByteArrays contains no
// string.
func (m *ByteArrays) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *ByteArrays) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := "", opts.Offset
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *ByteArrays) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := "", opts.Offset
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain
// ByteArrays call it.
func (m *ByteArrays) decodeKanon(data []byte, slab string, off, depth int) error {
	m.Byte1 = [2][1]byte{}
	m.Byte32 = [2][32]byte{}
	m.Byte127 = [2][127]byte{}
	m.Byte128 = [2][128]byte{}
	m.Digest = [2]Digest{}
	return m.mergeKanon(data, slab, off, depth)
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain
// ByteArrays call it.
func (m *ByteArrays) mergeKanon(data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "ByteArrays", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "ByteArrays.Byte0", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "ByteArrays.Byte0", 1, off+i)
			}
			i += n
			if err := _bytes_readArray2Array0Byte(&m.Byte0, data[i:i+int(l)], slab, off+i, depth-1, "ByteArrays.Byte0", 1); err != nil {
				return err
			}
			i += int(l)
		case 2:
			if tag != 2<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "ByteArrays.Byte1", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "ByteArrays.Byte1", 2, off+i)
			}
			i += n
			if err := _bytes_readArray2Array1Byte(&m.Byte1, data[i:i+int(l)], slab, off+i, depth-1, "ByteArrays.Byte1", 2); err != nil {
				return err
			}
			i += int(l)
		case 3:
			if tag != 3<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "ByteArrays.Byte32", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "ByteArrays.Byte32", 3, off+i)
			}
			i += n
			if err := _bytes_readArray2Array32Byte(&m.Byte32, data[i:i+int(l)], slab, off+i, depth-1, "ByteArrays.Byte32", 3); err != nil {
				return err
			}
			i += int(l)
		case 4:
			if tag != 4<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "ByteArrays.Byte127", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "ByteArrays.Byte127", 4, off+i)
			}
			i += n
			if err := _bytes_readArray2Array127Byte(&m.Byte127, data[i:i+int(l)], slab, off+i, depth-1, "ByteArrays.Byte127", 4); err != nil {
				return err
			}
			i += int(l)
		case 5:
			if tag != 5<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "ByteArrays.Byte128", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "ByteArrays.Byte128", 5, off+i)
			}
			i += n
			if err := _bytes_readArray2Array128Byte(&m.Byte128, data[i:i+int(l)], slab, off+i, depth-1, "ByteArrays.Byte128", 5); err != nil {
				return err
			}
			i += int(l)
		case 6:
			if tag != 6<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "ByteArrays.Digest", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "ByteArrays.Digest", 6, off+i)
			}
			i += n
			if err := _bytes_readArray2Digest(&m.Digest, data[i:i+int(l)], slab, off+i, depth-1, "ByteArrays.Digest", 6); err != nil {
				return err
			}
			i += int(l)
		default:
			n, err := wire.Skip(data[i:], tag, "ByteArrays", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded data stays
// reachable through m.
func (m *ByteArrays) Reset() {
	if m == nil {
		return
	}
	m.Byte1 = [2][1]byte{}
	m.Byte32 = [2][32]byte{}
	m.Byte127 = [2][127]byte{}
	m.Byte128 = [2][128]byte{}
	m.Digest = [2]Digest{}
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *ByteArrays) CloneKanon() *ByteArrays {
	if m == nil {
		return nil
	}
	c := new(ByteArrays)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain ByteArrays call it.
func (m *ByteArrays) cloneKanon(c *ByteArrays) {
	c.Byte0 = m.Byte0
	c.Byte1 = m.Byte1
	c.Byte32 = m.Byte32
	c.Byte127 = m.Byte127
	c.Byte128 = m.Byte128
	c.Digest = m.Digest
}

// _bytes_putArray2Digest writes the encoding of x, a [2]Digest, into the end of
// buf, which has room for it, and returns its length.
func _bytes_putArray2Digest(buf []byte, x *[2]Digest) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutRaw(buf, i, x[k][:])
		i = wire.PutUvarint(buf, i, uint64(len(x[k])))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _bytes_putArray2Array128Byte writes the encoding of x, a [2][128]byte, into
// the end of buf, which has room for it, and returns its length.
func _bytes_putArray2Array128Byte(buf []byte, x *[2][128]byte) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutRaw(buf, i, x[k][:])
		i = wire.PutUvarint(buf, i, uint64(len(x[k])))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _bytes_putArray2Array127Byte writes the encoding of x, a [2][127]byte, into
// the end of buf, which has room for it, and returns its length.
func _bytes_putArray2Array127Byte(buf []byte, x *[2][127]byte) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutRaw(buf, i, x[k][:])
		i = wire.PutUvarint(buf, i, uint64(len(x[k])))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _bytes_putArray2Array32Byte writes the encoding of x, a [2][32]byte, into the
// end of buf, which has room for it, and returns its length.
func _bytes_putArray2Array32Byte(buf []byte, x *[2][32]byte) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutRaw(buf, i, x[k][:])
		i = wire.PutUvarint(buf, i, uint64(len(x[k])))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _bytes_putArray2Array1Byte writes the encoding of x, a [2][1]byte, into the
// end of buf, which has room for it, and returns its length.
func _bytes_putArray2Array1Byte(buf []byte, x *[2][1]byte) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutRaw(buf, i, x[k][:])
		i = wire.PutUvarint(buf, i, uint64(len(x[k])))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _bytes_readArray2Array0Byte decodes the elements that data encodes, a
// [2][0]byte without its length, into *dst. It fails unless data encodes
// exactly 2 elements. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _bytes_readArray2Array0Byte(dst *[2][0]byte, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		l, n := wire.Uvarint(data[i:])
		if n > 0 && l != 0 {
			return wire.LengthError(l, 0, loc, num, off+i)
		}
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		i += copy(dst[k][:], data[i:])
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}

// _bytes_readArray2Array1Byte decodes the elements that data encodes, a
// [2][1]byte without its length, into *dst. It fails unless data encodes
// exactly 2 elements. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _bytes_readArray2Array1Byte(dst *[2][1]byte, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		l, n := wire.Uvarint(data[i:])
		if n > 0 && l != 1 {
			return wire.LengthError(l, 1, loc, num, off+i)
		}
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		i += copy(dst[k][:], data[i:])
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}

// _bytes_readArray2Array32Byte decodes the elements that data encodes, a
// [2][32]byte without its length, into *dst. It fails unless data encodes
// exactly 2 elements. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _bytes_readArray2Array32Byte(dst *[2][32]byte, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		l, n := wire.Uvarint(data[i:])
		if n > 0 && l != 32 {
			return wire.LengthError(l, 32, loc, num, off+i)
		}
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		i += copy(dst[k][:], data[i:])
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}

// _bytes_readArray2Array127Byte decodes the elements that data encodes, a
// [2][127]byte without its length, into *dst. It fails unless data encodes
// exactly 2 elements. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _bytes_readArray2Array127Byte(dst *[2][127]byte, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		l, n := wire.Uvarint(data[i:])
		if n > 0 && l != 127 {
			return wire.LengthError(l, 127, loc, num, off+i)
		}
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		i += copy(dst[k][:], data[i:])
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}

// _bytes_readArray2Array128Byte decodes the elements that data encodes, a
// [2][128]byte without its length, into *dst. It fails unless data encodes
// exactly 2 elements. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _bytes_readArray2Array128Byte(dst *[2][128]byte, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		l, n := wire.Uvarint(data[i:])
		if n > 0 && l != 128 {
			return wire.LengthError(l, 128, loc, num, off+i)
		}
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		i += copy(dst[k][:], data[i:])
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}

// _bytes_readArray2Digest decodes the elements that data encodes, a [2]Digest
// without its length, into *dst. It fails unless data encodes exactly 2
// elements. data starts at offset off of slab, and the decode enters depth
// levels below the value at most. loc and num locate the field in errors.
func _bytes_readArray2Digest(dst *[2]Digest, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		l, n := wire.Uvarint(data[i:])
		if n > 0 && l != 32 {
			return wire.LengthError(l, 32, loc, num, off+i)
		}
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		i += copy(dst[k][:], data[i:])
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}
