// Code generated by kanon. DO NOT EDIT.
// source: codec.go

//kanon:numbers Codecs Token=1 Ticket=2 Grade=3 Word=4 Stamp=5 Code=6

package array

import (
	"io"
	"slices"

	"go.thesmos.sh/kanon"
	"go.thesmos.sh/kanon/internal/fixture/codec"
	"go.thesmos.sh/kanon/internal/fixture/external"
	"go.thesmos.sh/kanon/wire"
)

// The file compiles against a runtime that supports version 2 of the generator.
const (
	_ = kanon.EnforceVersion(2 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 2)
)

// The generated types implement kanon.Cloner.
var (
	_ kanon.Cloner[Codecs] = (*Codecs)(nil)
)

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Codecs) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Token != ([2]codec.Token{}) {
		n += 1 + wire.SizeBytes(_codec_sizeArray2CodecToken(&m.Token))
	}
	if m.Ticket != ([2]codec.Ticket{}) {
		n += 1 + wire.SizeBytes(_codec_sizeArray2CodecTicket(&m.Ticket))
	}
	if m.Grade != ([2]codec.Grade{}) {
		n += 1 + wire.SizeBytes(_codec_sizeArray2CodecGrade(&m.Grade))
	}
	if m.Word != ([2]codec.Word{}) {
		n += 1 + wire.SizeBytes(_codec_sizeArray2CodecWord(&m.Word))
	}
	if m.Stamp != ([2]codec.Stamp{}) {
		n += 1 + wire.SizeBytes(_codec_sizeArray2CodecStamp(&m.Stamp))
	}
	if m.Code != ([2]external.Code{}) {
		n += 1 + wire.SizeBytes(_codec_sizeArray2ExternalCode(&m.Code))
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer. It
// fails when the value of a field fails to encode: a type that encodes itself
// returns an error, ValidateKanon of a type rejects a value, an interface
// stores a type that the tag option types of its field does not list, or a map
// has a key with a NaN component or two keys of one projection.
func (m *Codecs) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. It fails when the value of a field
// fails to encode: a type that encodes itself returns an error, ValidateKanon
// of a type rejects a value, an interface stores a type that the tag option
// types of its field does not list, or a map has a key with a NaN component or
// two keys of one projection.
func (m *Codecs) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if m.Code != ([2]external.Code{}) {
		w, err := _codec_putArray2ExternalCode(buf[:i], &m.Code, "Codecs.Code", 6)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 6<<3|wire.Bytes)
	}
	if m.Stamp != ([2]codec.Stamp{}) {
		w, err := _codec_putArray2CodecStamp(buf[:i], &m.Stamp, "Codecs.Stamp", 5)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 5<<3|wire.Bytes)
	}
	if m.Word != ([2]codec.Word{}) {
		w, err := _codec_putArray2CodecWord(buf[:i], &m.Word, "Codecs.Word", 4)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 4<<3|wire.Bytes)
	}
	if m.Grade != ([2]codec.Grade{}) {
		w, err := _codec_putArray2CodecGrade(buf[:i], &m.Grade, "Codecs.Grade", 3)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 3<<3|wire.Bytes)
	}
	if m.Ticket != ([2]codec.Ticket{}) {
		w, err := _codec_putArray2CodecTicket(buf[:i], &m.Ticket, "Codecs.Ticket", 2)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if m.Token != ([2]codec.Token{}) {
		w, err := _codec_putArray2CodecToken(buf[:i], &m.Token, "Codecs.Token", 1)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. It fails
// when the value of a field fails to encode: a type that encodes itself returns
// an error, ValidateKanon of a type rejects a value, an interface stores a type
// that the tag option types of its field does not list, or a map has a key with
// a NaN component or two keys of one projection.
func (m *Codecs) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	if _, err := m.encodeKanon(out); err != nil {
		return b, err
	}
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. It fails when the value of a field fails to encode: a type that
// encodes itself returns an error, ValidateKanon of a type rejects a value, an
// interface stores a type that the tag option types of its field does not list,
// or a map has a key with a NaN component or two keys of one projection.
func (m *Codecs) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which do not copy data, since Codecs contains no string.
func (m *Codecs) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Codecs) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := "", opts.Offset
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Codecs) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := "", opts.Offset
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Codecs
// call it.
func (m *Codecs) decodeKanon(data []byte, slab string, off, depth int) error {
	m.Token = [2]codec.Token{}
	m.Ticket = [2]codec.Ticket{}
	m.Grade = [2]codec.Grade{}
	m.Word = [2]codec.Word{}
	m.Stamp = [2]codec.Stamp{}
	m.Code = [2]external.Code{}
	return m.mergeKanon(data, slab, off, depth)
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Codecs
// call it.
func (m *Codecs) mergeKanon(data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "Codecs", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Codecs.Token", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Codecs.Token", 1, off+i)
			}
			i += n
			if err := _codec_readArray2CodecToken(&m.Token, data[i:i+int(l)], slab, off+i, depth-1, "Codecs.Token", 1); err != nil {
				return err
			}
			i += int(l)
		case 2:
			if tag != 2<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Codecs.Ticket", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Codecs.Ticket", 2, off+i)
			}
			i += n
			if err := _codec_readArray2CodecTicket(&m.Ticket, data[i:i+int(l)], slab, off+i, depth-1, "Codecs.Ticket", 2); err != nil {
				return err
			}
			i += int(l)
		case 3:
			if tag != 3<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Codecs.Grade", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Codecs.Grade", 3, off+i)
			}
			i += n
			if err := _codec_readArray2CodecGrade(&m.Grade, data[i:i+int(l)], slab, off+i, depth-1, "Codecs.Grade", 3); err != nil {
				return err
			}
			i += int(l)
		case 4:
			if tag != 4<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Codecs.Word", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Codecs.Word", 4, off+i)
			}
			i += n
			if err := _codec_readArray2CodecWord(&m.Word, data[i:i+int(l)], slab, off+i, depth-1, "Codecs.Word", 4); err != nil {
				return err
			}
			i += int(l)
		case 5:
			if tag != 5<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Codecs.Stamp", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Codecs.Stamp", 5, off+i)
			}
			i += n
			if err := _codec_readArray2CodecStamp(&m.Stamp, data[i:i+int(l)], slab, off+i, depth-1, "Codecs.Stamp", 5); err != nil {
				return err
			}
			i += int(l)
		case 6:
			if tag != 6<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Codecs.Code", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Codecs.Code", 6, off+i)
			}
			i += n
			if err := _codec_readArray2ExternalCode(&m.Code, data[i:i+int(l)], slab, off+i, depth-1, "Codecs.Code", 6); err != nil {
				return err
			}
			i += int(l)
		default:
			n, err := wire.Skip(data[i:], tag, "Codecs", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded content remains
// in m or in the storage that it keeps.
func (m *Codecs) Reset() {
	if m == nil {
		return
	}
	m.Token = [2]codec.Token{}
	m.Ticket = [2]codec.Ticket{}
	m.Grade = [2]codec.Grade{}
	m.Word = [2]codec.Word{}
	m.Stamp = [2]codec.Stamp{}
	m.Code = [2]external.Code{}
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Codecs) CloneKanon() *Codecs {
	if m == nil {
		return nil
	}
	c := new(Codecs)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Codecs call it.
func (m *Codecs) cloneKanon(c *Codecs) {
	c.Token = m.Token
	c.Ticket = m.Ticket
	c.Grade = m.Grade
	_codec_cloneArray2CodecWord(&c.Word, &m.Word)
	c.Stamp = m.Stamp
	c.Code = m.Code
}

// _codec_sizeArray2CodecToken returns the length of the encoding of the
// elements of x, a [2]codec.Token.
func _codec_sizeArray2CodecToken(x *[2]codec.Token) int {
	n := 0
	for k := range x {
		n += wire.SizeBytes(_codec_sizeCodecToken(&x[k]))
	}
	return n
}

// _codec_sizeArray2CodecTicket returns the length of the encoding of the
// elements of x, a [2]codec.Ticket.
func _codec_sizeArray2CodecTicket(x *[2]codec.Ticket) int {
	n := 0
	for k := range x {
		n += wire.SizeBytes(_codec_sizeCodecTicket(&x[k]))
	}
	return n
}

// _codec_sizeArray2CodecGrade returns the length of the encoding of the
// elements of x, a [2]codec.Grade.
func _codec_sizeArray2CodecGrade(x *[2]codec.Grade) int {
	n := 0
	for k := range x {
		n += wire.SizeBytes(_codec_sizeCodecGrade(&x[k]))
	}
	return n
}

// _codec_sizeArray2CodecWord returns the length of the encoding of the elements
// of x, a [2]codec.Word.
func _codec_sizeArray2CodecWord(x *[2]codec.Word) int {
	n := 0
	for k := range x {
		n += wire.SizeBytes(_codec_sizeCodecWord(&x[k]))
	}
	return n
}

// _codec_sizeArray2CodecStamp returns the length of the encoding of the
// elements of x, a [2]codec.Stamp.
func _codec_sizeArray2CodecStamp(x *[2]codec.Stamp) int {
	n := 0
	for k := range x {
		n += wire.SizeBytes(_codec_sizeCodecStamp(&x[k]))
	}
	return n
}

// _codec_sizeArray2ExternalCode returns the length of the encoding of the
// elements of x, a [2]external.Code.
func _codec_sizeArray2ExternalCode(x *[2]external.Code) int {
	n := 0
	for k := range x {
		n += wire.SizeBytes(_codec_sizeExternalCode(&x[k]))
	}
	return n
}

// _codec_putArray2ExternalCode writes the encoding of x, a [2]external.Code,
// into the end of buf, which has room for it, and returns its length. It fails
// for a value that fails to encode, which loc and num locate.
func _codec_putArray2ExternalCode(buf []byte, x *[2]external.Code, loc string, num int) (int, error) {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		w, err := _codec_putExternalCode(buf[:i], &x[k], loc, num)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, nil
}

// _codec_putArray2CodecStamp writes the encoding of x, a [2]codec.Stamp, into
// the end of buf, which has room for it, and returns its length. It fails for a
// value that fails to encode, which loc and num locate.
func _codec_putArray2CodecStamp(buf []byte, x *[2]codec.Stamp, loc string, num int) (int, error) {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		w, err := _codec_putCodecStamp(buf[:i], &x[k], loc, num)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, nil
}

// _codec_putArray2CodecWord writes the encoding of x, a [2]codec.Word, into the
// end of buf, which has room for it, and returns its length. It fails for a
// value that fails to encode, which loc and num locate.
func _codec_putArray2CodecWord(buf []byte, x *[2]codec.Word, loc string, num int) (int, error) {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		w, err := _codec_putCodecWord(buf[:i], &x[k], loc, num)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, nil
}

// _codec_putArray2CodecGrade writes the encoding of x, a [2]codec.Grade, into
// the end of buf, which has room for it, and returns its length. It fails for a
// value that fails to encode, which loc and num locate.
func _codec_putArray2CodecGrade(buf []byte, x *[2]codec.Grade, loc string, num int) (int, error) {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		w, err := _codec_putCodecGrade(buf[:i], &x[k], loc, num)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, nil
}

// _codec_putArray2CodecTicket writes the encoding of x, a [2]codec.Ticket, into
// the end of buf, which has room for it, and returns its length. It fails for a
// value that fails to encode, which loc and num locate.
func _codec_putArray2CodecTicket(buf []byte, x *[2]codec.Ticket, loc string, num int) (int, error) {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		w, err := _codec_putCodecTicket(buf[:i], &x[k], loc, num)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, nil
}

// _codec_putArray2CodecToken writes the encoding of x, a [2]codec.Token, into
// the end of buf, which has room for it, and returns its length. It fails for a
// value that fails to encode, which loc and num locate.
func _codec_putArray2CodecToken(buf []byte, x *[2]codec.Token, loc string, num int) (int, error) {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		w, err := _codec_putCodecToken(buf[:i], &x[k], loc, num)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, nil
}

// _codec_readArray2CodecToken decodes the elements that data encodes, a
// [2]codec.Token without its length, into *dst. It fails unless data encodes
// exactly 2 elements. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _codec_readArray2CodecToken(dst *[2]codec.Token, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		dst[k] = 0
		if err := dst[k].UnmarshalBinary(data[i : i+int(l)]); err != nil {
			return wire.UnmarshalError(err, loc, num, off+i)
		}
		i += int(l)
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}

// _codec_readArray2CodecTicket decodes the elements that data encodes, a
// [2]codec.Ticket without its length, into *dst. It fails unless data encodes
// exactly 2 elements. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _codec_readArray2CodecTicket(dst *[2]codec.Ticket, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		dst[k] = 0
		if err := dst[k].GobDecode(data[i : i+int(l)]); err != nil {
			return wire.UnmarshalError(err, loc, num, off+i)
		}
		i += int(l)
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}

// _codec_readArray2CodecGrade decodes the elements that data encodes, a
// [2]codec.Grade without its length, into *dst. It fails unless data encodes
// exactly 2 elements. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _codec_readArray2CodecGrade(dst *[2]codec.Grade, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		dst[k] = 0
		if err := dst[k].UnmarshalText(data[i : i+int(l)]); err != nil {
			return wire.UnmarshalError(err, loc, num, off+i)
		}
		i += int(l)
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}

// _codec_readArray2CodecWord decodes the elements that data encodes, a
// [2]codec.Word without its length, into *dst. It fails unless data encodes
// exactly 2 elements. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _codec_readArray2CodecWord(dst *[2]codec.Word, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		dst[k] = codec.Word{}
		if err := dst[k].UnmarshalText(data[i : i+int(l)]); err != nil {
			return wire.UnmarshalError(err, loc, num, off+i)
		}
		i += int(l)
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}

// _codec_readArray2CodecStamp decodes the elements that data encodes, a
// [2]codec.Stamp without its length, into *dst. It fails unless data encodes
// exactly 2 elements. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _codec_readArray2CodecStamp(dst *[2]codec.Stamp, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		dst[k] = codec.Stamp{}
		if err := dst[k].UnmarshalBinary(data[i : i+int(l)]); err != nil {
			return wire.UnmarshalError(err, loc, num, off+i)
		}
		i += int(l)
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}

// _codec_readArray2ExternalCode decodes the elements that data encodes, a
// [2]external.Code without its length, into *dst. It fails unless data encodes
// exactly 2 elements. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _codec_readArray2ExternalCode(dst *[2]external.Code, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		dst[k] = 0
		if err := dst[k].UnmarshalBinary(data[i : i+int(l)]); err != nil {
			return wire.UnmarshalError(err, loc, num, off+i)
		}
		i += int(l)
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}

// _codec_cloneArray2CodecWord copies the [2]codec.Word that src points at into
// the one that dst points at, element by element.
func _codec_cloneArray2CodecWord(dst, src *[2]codec.Word) {
	for k := range src {
		_codec_cloneCodecWord(&dst[k], &src[k])
	}
}

// _codec_sizeCodecToken returns the length of the encoding of the codec.Token
// that x points at, and 1 when x fails to encode itself, so that the value is
// present and its encode reports the failure.
func _codec_sizeCodecToken(x *codec.Token) int {
	var scratch [128]byte
	enc, err := x.AppendBinary(scratch[:0])
	if err != nil {
		return 1
	}
	return len(enc)
}

// _codec_sizeCodecTicket returns the length of the encoding of the codec.Ticket
// that x points at, and 1 when x fails to encode itself, so that the value is
// present and its encode reports the failure.
func _codec_sizeCodecTicket(x *codec.Ticket) int {
	enc, err := x.GobEncode()
	if err != nil {
		return 1
	}
	return len(enc)
}

// _codec_sizeCodecGrade returns the length of the encoding of the codec.Grade
// that x points at, and 1 when x fails to encode itself, so that the value is
// present and its encode reports the failure.
func _codec_sizeCodecGrade(x *codec.Grade) int {
	var scratch [128]byte
	enc, err := x.AppendText(scratch[:0])
	if err != nil {
		return 1
	}
	return len(enc)
}

// _codec_sizeCodecWord returns the length of the encoding of the codec.Word
// that x points at, and 1 when x fails to encode itself, so that the value is
// present and its encode reports the failure.
func _codec_sizeCodecWord(x *codec.Word) int {
	enc, err := x.MarshalText()
	if err != nil {
		return 1
	}
	return len(enc)
}

// _codec_sizeCodecStamp returns the length of the encoding of the codec.Stamp
// that x points at, and 1 when x fails to encode itself, so that the value is
// present and its encode reports the failure.
func _codec_sizeCodecStamp(x *codec.Stamp) int {
	var scratch [128]byte
	enc, err := x.AppendBinary(scratch[:0])
	if err != nil {
		return 1
	}
	return len(enc)
}

// _codec_sizeExternalCode returns the length of the encoding of the
// external.Code that x points at, and 1 when x fails to encode itself, so that
// the value is present and its encode reports the failure.
func _codec_sizeExternalCode(x *external.Code) int {
	enc, err := x.MarshalBinary()
	if err != nil {
		return 1
	}
	return len(enc)
}

// _codec_putExternalCode writes the encoding of the external.Code that x points
// at into the end of buf, which has room for it, and returns its length. It
// fails when x fails to encode itself.
func _codec_putExternalCode(buf []byte, x *external.Code, loc string, num int) (int, error) {
	enc, err := x.MarshalBinary()
	if err != nil {
		return 0, wire.MarshalError(err, loc, num)
	}
	return copy(buf[len(buf)-len(enc):], enc), nil
}

// _codec_putCodecStamp writes the encoding of the codec.Stamp that x points at
// into the end of buf, which has room for it, and returns its length. It fails
// when x fails to encode itself.
func _codec_putCodecStamp(buf []byte, x *codec.Stamp, loc string, num int) (int, error) {
	var scratch [128]byte
	enc, err := x.AppendBinary(scratch[:0])
	if err != nil {
		return 0, wire.MarshalError(err, loc, num)
	}
	return copy(buf[len(buf)-len(enc):], enc), nil
}

// _codec_putCodecWord writes the encoding of the codec.Word that x points at
// into the end of buf, which has room for it, and returns its length. It fails
// when x fails to encode itself.
func _codec_putCodecWord(buf []byte, x *codec.Word, loc string, num int) (int, error) {
	enc, err := x.MarshalText()
	if err != nil {
		return 0, wire.MarshalError(err, loc, num)
	}
	return copy(buf[len(buf)-len(enc):], enc), nil
}

// _codec_putCodecGrade writes the encoding of the codec.Grade that x points at
// into the end of buf, which has room for it, and returns its length. It fails
// when x fails to encode itself.
func _codec_putCodecGrade(buf []byte, x *codec.Grade, loc string, num int) (int, error) {
	var scratch [128]byte
	enc, err := x.AppendText(scratch[:0])
	if err != nil {
		return 0, wire.MarshalError(err, loc, num)
	}
	return copy(buf[len(buf)-len(enc):], enc), nil
}

// _codec_putCodecTicket writes the encoding of the codec.Ticket that x points
// at into the end of buf, which has room for it, and returns its length. It
// fails when x fails to encode itself.
func _codec_putCodecTicket(buf []byte, x *codec.Ticket, loc string, num int) (int, error) {
	enc, err := x.GobEncode()
	if err != nil {
		return 0, wire.MarshalError(err, loc, num)
	}
	return copy(buf[len(buf)-len(enc):], enc), nil
}

// _codec_putCodecToken writes the encoding of the codec.Token that x points at
// into the end of buf, which has room for it, and returns its length. It fails
// when x fails to encode itself.
func _codec_putCodecToken(buf []byte, x *codec.Token, loc string, num int) (int, error) {
	var scratch [128]byte
	enc, err := x.AppendBinary(scratch[:0])
	if err != nil {
		return 0, wire.MarshalError(err, loc, num)
	}
	return copy(buf[len(buf)-len(enc):], enc), nil
}

// _codec_cloneCodecWord copies the codec.Word that src points at into dst
// through its encode and decode methods, and by assignment when they fail.
func _codec_cloneCodecWord(dst, src *codec.Word) {
	*dst = *src
	enc, err := src.MarshalText()
	if err != nil {
		return
	}
	var c codec.Word
	if c.UnmarshalText(enc) == nil {
		*dst = c
	}
}
