// Code generated by kanon. DO NOT EDIT.
// source: nested.go

package array

import (
	"testing"

	"go.thesmos.sh/kanon/kanontest"
)

// kanonSpecNested describes Nested to the conformance suite.
var kanonSpecNested = kanontest.Spec[Nested]{
	Fields: []kanontest.Field{
		{Name: "Empty", Number: 1},
		{Name: "Grid", Number: 2},
		{Name: "Voids", Number: 3},
		{Name: "Lists", Number: 4},
		{Name: "Maps", Number: 5},
		{Name: "Corners", Number: 6},
		{Name: "Numbers", Number: 7},
		{Name: "Deep", Number: 8},
	},
}

// TestKanonNested runs the conformance suite on Nested.
func TestKanonNested(t *testing.T) {
	kanontest.Run(t, kanonSpecNested)
}

// BenchmarkKanonNested measures the codec of Nested.
func BenchmarkKanonNested(b *testing.B) {
	kanontest.Bench(b, kanonSpecNested)
}

// FuzzKanonNested fuzzes the decode of Nested.
func FuzzKanonNested(f *testing.F) {
	kanontest.Fuzz(f, kanonSpecNested)
}
