// Code generated by kanon. DO NOT EDIT.
// source: key.go

package canonical

import (
	"reflect"
	"testing"

	"go.thesmos.sh/kanon/kanontest"
)

// kanonSpecLookups describes Lookups to the conformance suite.
var kanonSpecLookups = kanontest.Spec[Lookups]{
	Fields: []kanontest.Field{
		{Name: "Bools", Number: 1},
		{Name: "Int8s", Number: 2},
		{Name: "Uints", Number: 3},
		{Name: "Ints", Number: 4},
		{Name: "Floats", Number: 5},
		{Name: "Ratios", Number: 6},
		{Name: "Complex64", Number: 7},
		{Name: "Complex128", Number: 8},
		{Name: "Pairs", Number: 9},
		{Name: "Pointers", Number: 10},
		{Name: "Coords", Number: 11},
		{Name: "Anys", Number: 12, Types: []kanontest.ConcreteType{{Type: reflect.TypeFor[float64](), Number: 1}, {Type: reflect.TypeFor[string](), Number: 2}}},
		{Name: "Units", Number: 13},
		{Name: "Voids", Number: 14},
		{Name: "Times", Number: 15},
		{Name: "Stamps", Number: 16},
		{Name: "Counts", Number: 17},
		{Name: "Texts", Number: 18},
		{Name: "Keys", Number: 19},
		{Name: "Nested", Number: 20},
	},
	Structs: []kanontest.Struct{
		{
			Type: reflect.TypeFor[Coord](),
			Name: "Coord",
			Fields: []kanontest.Field{
				{Name: "Lat", Number: 1},
				{Name: "Lon", Number: 2},
			},
		},
		{
			Type:   reflect.TypeFor[struct{}](),
			Name:   "Lookups.Units[key]",
			Fields: []kanontest.Field{},
		},
	},
	Canonical: true,
}

// TestKanonLookups runs the conformance suite on Lookups.
func TestKanonLookups(t *testing.T) {
	kanontest.Run(t, kanonSpecLookups)
}

// BenchmarkKanonLookups measures the codec of Lookups.
func BenchmarkKanonLookups(b *testing.B) {
	kanontest.Bench(b, kanonSpecLookups)
}

// FuzzKanonLookups fuzzes the decode of Lookups.
func FuzzKanonLookups(f *testing.F) {
	kanontest.Fuzz(f, kanonSpecLookups)
}
