// Code generated by kanon. DO NOT EDIT.
// source: feed.go

//kanon:numbers Entry Name=1
//kanon:numbers Feed Title=1 Entries=2

package bound

import (
	"io"
	"slices"
	"strings"

	"go.thesmos.sh/kanon"
	"go.thesmos.sh/kanon/wire"
)

// The file compiles against a runtime that supports version 4 of the generator.
const (
	_ = kanon.EnforceVersion(4 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 4)
)

// The generated types implement kanon.Cloner.
var (
	_ kanon.Cloner[Entry] = (*Entry)(nil)
	_ kanon.Cloner[Feed]  = (*Feed)(nil)
)

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Entry) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Name != "" {
		n += 1 + wire.SizeBytes(len(m.Name))
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer.
// The error is always nil.
func (m *Entry) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. The error is always nil.
func (m *Entry) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if m.Name != "" {
		i = wire.PutRaw(buf, i, m.Name)
		i = wire.PutUvarint(buf, i, uint64(len(m.Name)))
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. The error
// is always nil.
func (m *Entry) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	m.encodeKanon(out)
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. The error is always nil.
func (m *Entry) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which copy data once.
func (m *Entry) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Entry) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Entry) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Entry
// call it.
func (m *Entry) decodeKanon(data []byte, slab string, off, depth int) error {
	m.Name = ""
	return m.mergeKanon(data, slab, off, depth)
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Entry
// call it.
func (m *Entry) mergeKanon(data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "Entry", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Entry.Name", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Entry.Name", 1, off+i)
			}
			i += n
			m.Name = slab[off+i : off+i+int(l)]
			i += int(l)
		default:
			n, err := wire.Skip(data[i:], tag, "Entry", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded content remains
// in m or in the storage that it keeps.
func (m *Entry) Reset() {
	if m == nil {
		return
	}
	m.Name = ""
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Entry) CloneKanon() *Entry {
	if m == nil {
		return nil
	}
	c := new(Entry)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Entry call it.
func (m *Entry) cloneKanon(c *Entry) {
	c.Name = strings.Clone(m.Name)
}

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Feed) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Title != "" {
		n += 1 + wire.SizeBytes(len(m.Title))
	}
	if len(m.Entries) > 0 {
		n += 1 + wire.SizeBytes(_feed_sizeSliceEntry(m.Entries))
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer. It
// fails when the value of a field fails to encode: a type that encodes itself
// returns an error, ValidateKanon of a type rejects a value, an interface
// stores a type that the tag option types of its field does not list, a map has
// a key with a NaN component or two keys of one projection, or a slice or a map
// has more elements than the tag option max of its field allows.
func (m *Feed) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. It fails when the value of a field
// fails to encode: a type that encodes itself returns an error, ValidateKanon
// of a type rejects a value, an interface stores a type that the tag option
// types of its field does not list, a map has a key with a NaN component or two
// keys of one projection, or a slice or a map has more elements than the tag
// option max of its field allows.
func (m *Feed) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if len(m.Entries) > 0 {
		if len(m.Entries) > 2 {
			return 0, wire.MarshalError(kanon.ErrMax, "Feed.Entries", 2)
		}
		i -= _feed_putSliceEntry(buf[:i], m.Entries)
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if m.Title != "" {
		i = wire.PutRaw(buf, i, m.Title)
		i = wire.PutUvarint(buf, i, uint64(len(m.Title)))
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. It fails
// when the value of a field fails to encode: a type that encodes itself returns
// an error, ValidateKanon of a type rejects a value, an interface stores a type
// that the tag option types of its field does not list, a map has a key with a
// NaN component or two keys of one projection, or a slice or a map has more
// elements than the tag option max of its field allows.
func (m *Feed) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	if _, err := m.encodeKanon(out); err != nil {
		return b, err
	}
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. It fails when the value of a field fails to encode: a type that
// encodes itself returns an error, ValidateKanon of a type rejects a value, an
// interface stores a type that the tag option types of its field does not list,
// a map has a key with a NaN component or two keys of one projection, or a
// slice or a map has more elements than the tag option max of its field allows.
func (m *Feed) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which copy data once.
func (m *Feed) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Feed) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Feed) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Feed
// call it.
func (m *Feed) decodeKanon(data []byte, slab string, off, depth int) error {
	m.Title = ""
	m.Entries = m.Entries[:0]
	return m.mergeKanon(data, slab, off, depth)
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Feed
// call it.
func (m *Feed) mergeKanon(data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "Feed", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Feed.Title", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Feed.Title", 1, off+i)
			}
			i += n
			m.Title = slab[off+i : off+i+int(l)]
			i += int(l)
		case 2:
			if tag != 2<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Feed.Entries", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Feed.Entries", 2, off+i)
			}
			i += n
			if err := _feed_readSliceEntry(&m.Entries, data[i:i+int(l)], slab, off+i, depth-1, 2, "Feed.Entries", 2); err != nil {
				return err
			}
			i += int(l)
		default:
			n, err := wire.Skip(data[i:], tag, "Feed", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded content remains
// in m or in the storage that it keeps.
func (m *Feed) Reset() {
	if m == nil {
		return
	}
	m.Title = ""
	clear(m.Entries[:cap(m.Entries)])
	m.Entries = m.Entries[:0]
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Feed) CloneKanon() *Feed {
	if m == nil {
		return nil
	}
	c := new(Feed)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Feed call it.
func (m *Feed) cloneKanon(c *Feed) {
	c.Title = strings.Clone(m.Title)
	c.Entries = _feed_cloneSliceEntry(m.Entries)
}

// FeedField names a streamed field of Feed, which FeedStream.Next returns. Its
// value is the field number.
type FeedField int

// The streamed fields of Feed.
const (
	FeedFieldEntries FeedField = 2
)

// _feed_streamFeed describes Feed to the wire.Stream of its stream decoder.
var _feed_streamFeed = wire.StreamSchema{
	Loc: "Feed",
	Fields: []wire.StreamField{
		{Tag: 2<<3 | wire.Bytes, Loc: "Feed.Entries", Elem: "Entry", Max: 2},
	},
}

// FeedStream decodes the encoding of a Feed from a reader, one field at a time,
// in input order. It decodes each field without the tag option stream into the
// receiver that NewFeedStream takes, with the code of DecodeKanon, and stops at
// each field with the option: DecodeEntries decodes the elements of Entries.
// Once Next returns io.EOF, the receiver contains the value of the encoding,
// with Entries empty.
//
// # Checks
//
// The stream applies the checks of DecodeKanon to every byte, in the order of
// DecodeKanon, and returns the error that DecodeKanon returns for the same
// encoding: a *kanon.DecodeError whose Offset counts from the first byte of the
// encoding. It passes a streamed value to the caller before it has read the
// rest of the encoding, so an error can follow the bytes and the elements that
// the caller has read. A caller uses them only after Next returns io.EOF.
//
// # Limits
//
// The stream has in memory the decoded fields of the encoding together, one
// element, and a read buffer of 4096 bytes. A decoded field that would take the
// decoded fields past the Buffer of its kanon.StreamOptions, and an element
// longer than that Buffer, fail with a *kanon.DecodeError that wraps
// kanon.ErrLimit. An element of Entries past the bound of the tag option max of
// its field fails with a *kanon.DecodeError that wraps kanon.ErrMax. A reader
// that returns fewer than size bytes fails the call that needs the next byte
// with a *kanon.DecodeError that wraps io.ErrUnexpectedEOF, at the offset of
// that byte. The methods return any other error of the reader unchanged, and
// io.ErrNoProgress when the reader returns no byte and no error 100 times
// before the bytes that a call needs. After an error, every method returns that
// error.
//
// # Aliasing
//
// The strings of the receiver are substrings of the buffer of the decoded
// fields until the next call of Reset. The strings of an element are substrings
// of the buffers of the stream until the next call of Next, Element or a decode
// method. A caller that needs a value after that copies it with CloneKanon.
//
// # Allocation contract
//
// NewFeedStream allocates the stream, its read buffer of 4096 bytes and the
// counts of the elements of Entries. Next and the decode methods allocate
// nothing once the buffers of the stream have grown to the decoded fields and
// to the longest element of more than 4096 bytes, except where DecodeKanon
// allocates for the same values. Reset, Len and Element do not allocate.
//
// # Concurrency
//
// A FeedStream is not safe for concurrent use. It writes the receiver until
// Next returns io.EOF or an error, so no other goroutine reads the receiver
// before then.
type FeedStream struct {
	// s reads the encoding, and m is the receiver of the decoded fields.
	s wire.Stream
	m *Feed
	// skipEntries is the element into which Next decodes the elements of Entries
	// that the caller skips.
	skipEntries Entry
}

// NewFeedStream returns a FeedStream that reads the encoding of a Feed, size
// bytes, from r and decodes it into m, which Reset prepares as it states. opts
// sets the nesting limit and the buffer limit of the stream.
func NewFeedStream(r io.Reader, size int64, m *Feed, opts kanon.StreamOptions) *FeedStream {
	d := new(FeedStream)
	d.s.Init(&_feed_streamFeed, opts)
	d.Reset(r, size, m)
	return d
}

// Reset makes d read the encoding of a Feed, size bytes, from r into m, and
// reuses the buffers of d. It clears the fields of m that the encoding leaves
// out, and the fields that the decode does not track, the streamed fields among
// them, as DecodeKanon clears them. It reads at most size bytes from r. A size
// below 0, or above math.MaxInt, makes the first call of Next fail with
// kanon.ErrStreamSize. The strings that d decoded before are substrings of the
// buffers that it reuses.
func (d *FeedStream) Reset(r io.Reader, size int64, m *Feed) {
	d.s.Reset(r, size)
	d.m = m
	m.Title = ""
	m.Entries = m.Entries[:0]
}

// Next moves to the next streamed field of the encoding and returns it. It
// first moves past the rest of the current field: it discards the unread bytes
// of a byte slice or a string, and decodes the unread elements of a slice into
// an element of its own, so that their checks run. It then decodes the fields
// before the next streamed field into the receiver, and checks the tag and the
// length of the streamed field as DecodeKanon checks them. At the end of the
// encoding it finishes the decode of the receiver as DecodeKanon finishes it,
// and returns io.EOF. A streamed field that occurs twice in the encoding
// returns twice.
func (d *FeedStream) Next() (FeedField, error) {
	for d.s.More(2) {
		if err := d.DecodeEntries(&d.skipEntries); err != nil {
			return 0, err
		}
	}
	r, err := d.s.Next()
	if err != nil {
		return 0, err
	}
	if err := d.m.mergeKanon(r.Data, r.Slab(), 0, r.Depth); err != nil {
		return 0, d.s.Fail(err)
	}
	n, err := d.s.Open()
	return FeedField(n), err
}

// Len returns the declared length in bytes of the value of the current field,
// and 0 before the first call of Next and after Next returns io.EOF or an
// error.
func (d *FeedStream) Len() int64 {
	return d.s.Len()
}

// Element reads the length of the next element of the current field, when the
// current field is Entries, and returns it without reading the element. It
// returns the same length until a decode method decodes the element. It checks
// the length as DecodeKanon checks it, and returns io.EOF after the last
// element and when the current field is another field. It fails at an element
// of Entries past the bound of the tag option max of its field, before it reads
// the length, as DecodeKanon fails.
func (d *FeedStream) Element() (int64, error) {
	return d.s.Element()
}

// DecodeEntries decodes the next element of Entries into e, when Entries is the
// current field, with the code that DecodeKanon runs for an element of Entries,
// at the same depth. It reads the length of the element first when Element has
// not read it. It fails at an element past the bound of the tag option max of
// Entries, as Element fails. It returns io.EOF after the last element, and when
// the current field is another field. The strings of e are substrings of the
// buffers of d until the next call of Next, Element or a decode method.
func (d *FeedStream) DecodeEntries(e *Entry) error {
	r, err := d.s.Value(2)
	if err != nil {
		return err
	}
	if err := e.decodeKanon(r.Data, r.Slab(), 0, r.Depth); err != nil {
		return d.s.Fail(err)
	}
	return nil
}

// _feed_sizeSliceEntry returns the length of the encoding of the elements of x,
// a []Entry.
func _feed_sizeSliceEntry(x []Entry) int {
	n := 0
	for k := range x {
		n += wire.SizeBytes(x[k].SizeKanon())
	}
	return n
}

// _feed_putSliceEntry writes the encoding of x, a []Entry, into the end of buf,
// which has room for it, and returns its length.
func _feed_putSliceEntry(buf []byte, x []Entry) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		w, _ := x[k].encodeKanon(buf[:i])
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _feed_readSliceEntry appends the elements that data encodes, a []Entry
// without its length, to *dst. data starts at offset off of slab, and the
// decode enters depth levels below the value at most. It fails at an element
// that would take the slice past bound elements. loc and num locate the field
// in errors.
func _feed_readSliceEntry(dst *[]Entry, data []byte, slab string, off, depth, bound int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]Entry, 0, min(wire.SliceCap[Entry](wire.CountValues(data)), bound))
	}
	for i := 0; i < len(data); {
		if len(x) >= bound {
			return wire.MaxError(loc, num, off+i, bound)
		}
		x = append(x, Entry{})
		last := len(x) - 1
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		i += n
		if depth < 1 {
			return wire.DepthError("Entry", 0, off+i)
		}
		if err := x[last].decodeKanon(data[i:i+int(l)], slab, off+i, depth-1); err != nil {
			return err
		}
		i += int(l)
	}
	*dst = x
	return nil
}

// _feed_cloneSliceEntry returns a copy of x, a []Entry, and nil for a nil x.
func _feed_cloneSliceEntry(x []Entry) []Entry {
	if x == nil {
		return nil
	}
	c := make([]Entry, len(x))
	for k := range x {
		x[k].cloneKanon(&c[k])
	}
	return c
}
