// Code generated by kanon. DO NOT EDIT.
// source: page.go

package bound

import (
	"testing"

	"go.thesmos.sh/kanon/kanontest"
)

// kanonSpecPage describes Page to the conformance suite.
var kanonSpecPage = kanontest.Spec[Page]{
	Fields: []kanontest.Field{
		{Name: "Items", Number: 1, Max: 2},
		{Name: "Meta", Number: 2, Max: 1},
	},
	Canonical: true,
}

// TestKanonPage runs the conformance suite on Page.
func TestKanonPage(t *testing.T) {
	kanontest.Run(t, kanonSpecPage)
}

// BenchmarkKanonPage measures the codec of Page.
func BenchmarkKanonPage(b *testing.B) {
	kanontest.Bench(b, kanonSpecPage)
}

// FuzzKanonPage fuzzes the decode of Page.
func FuzzKanonPage(f *testing.F) {
	kanontest.Fuzz(f, kanonSpecPage)
}
