// Code generated by kanon. DO NOT EDIT.
// source: remote.go

package mapkey

import (
	"reflect"
	"testing"

	"go.thesmos.sh/kanon/internal/fixture/external"
	"go.thesmos.sh/kanon/kanontest"
)

// kanonSpecRemote describes Remote to the conformance suite.
var kanonSpecRemote = kanontest.Spec[Remote]{
	Fields: []kanontest.Field{
		{Name: "Rank", Number: 1},
		{Name: "Ident", Number: 2},
		{Name: "Badge", Number: 3},
	},
	Structs: []kanontest.Struct{
		{
			Type: reflect.TypeFor[external.Badge](),
			Name: "external.Badge",
			Fields: []kanontest.Field{
				{Name: "Name", Number: 1},
			},
		},
	},
}

// TestKanonRemote runs the conformance suite on Remote.
func TestKanonRemote(t *testing.T) {
	kanontest.Run(t, kanonSpecRemote)
}

// BenchmarkKanonRemote measures the codec of Remote.
func BenchmarkKanonRemote(b *testing.B) {
	kanontest.Bench(b, kanonSpecRemote)
}

// FuzzKanonRemote fuzzes the decode of Remote.
func FuzzKanonRemote(f *testing.F) {
	kanontest.Fuzz(f, kanonSpecRemote)
}
