// Code generated by kanon. DO NOT EDIT.
// source: struct.go

//kanon:numbers Point X=2 Y=1
//kanon:numbers Chain Next=1 Ends=2
//kanon:numbers Structs Point=1 Label=2 Spot=3 Cell=4 Pair=5 Link=6 Padded=7 Nothing=8 Unit=9 Mute=10 Chain=11
//kanon:numbers Spot Row=1 Col=2
//kanon:numbers Structs.Cell[key] Row=1 Col=2
//kanon:numbers go.thesmos.sh/kanon/internal/fixture/external.Pair Key=1 Val=2
//kanon:numbers Link N=1 Next=2
//kanon:numbers Padded N=1 Pad=2
//kanon:numbers Structs.Nothing[key]
//kanon:numbers Mute

package mapkey

import (
	"bytes"
	"cmp"
	"io"
	"maps"
	"slices"
	"strings"

	"go.thesmos.sh/kanon"
	"go.thesmos.sh/kanon/internal/fixture/external"
	"go.thesmos.sh/kanon/wire"
)

// The file compiles against a runtime that supports version 1 of the generator.
const (
	_ = kanon.EnforceVersion(1 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 1)
)

// The generated types implement kanon.Cloner.
var (
	_ kanon.Cloner[Point]   = (*Point)(nil)
	_ kanon.Cloner[Chain]   = (*Chain)(nil)
	_ kanon.Cloner[Structs] = (*Structs)(nil)
)

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Point) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.X != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.X)))
	}
	if m.Y != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.Y)))
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer.
// The error is always nil.
func (m *Point) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. The error is always nil.
func (m *Point) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if m.X != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.X)))
		i = wire.PutTag(buf, i, 2<<3|wire.Varint)
	}
	if m.Y != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.Y)))
		i = wire.PutTag(buf, i, 1<<3|wire.Varint)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. The error
// is always nil.
func (m *Point) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	m.encodeKanon(out)
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. The error is always nil.
func (m *Point) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which do not copy data, since Point contains no string.
func (m *Point) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Point) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := "", opts.Offset
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Point) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := "", opts.Offset
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Point
// call it.
func (m *Point) decodeKanon(data []byte, slab string, off, depth int) error {
	m.X = 0
	m.Y = 0
	return m.mergeKanon(data, slab, off, depth)
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Point
// call it.
func (m *Point) mergeKanon(data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "Point", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 2:
			if tag != 2<<3|wire.Varint {
				return wire.FormatError(tag, wire.Varint, "Point.X", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, "Point.X", 2, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int32(s)) {
				return wire.RangeError(s, "int32", "Point.X", 2, off+i)
			}
			m.X = int32(s)
			i += n
		case 1:
			if tag != 1<<3|wire.Varint {
				return wire.FormatError(tag, wire.Varint, "Point.Y", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, "Point.Y", 1, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int32(s)) {
				return wire.RangeError(s, "int32", "Point.Y", 1, off+i)
			}
			m.Y = int32(s)
			i += n
		default:
			n, err := wire.Skip(data[i:], tag, "Point", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded data stays
// reachable through m.
func (m *Point) Reset() {
	if m == nil {
		return
	}
	m.X = 0
	m.Y = 0
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Point) CloneKanon() *Point {
	if m == nil {
		return nil
	}
	c := new(Point)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Point call it.
func (m *Point) cloneKanon(c *Point) {
	c.X = m.X
	c.Y = m.Y
}

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Chain) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Next != nil {
		n += 1 + wire.SizeBytes(m.Next.SizeKanon())
	}
	if m.Ends != ([2]int32{}) {
		n += 1 + wire.SizeBytes(_struct_sizeArray2Int32(&m.Ends))
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer.
// The error is always nil.
func (m *Chain) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. The error is always nil.
func (m *Chain) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if m.Ends != ([2]int32{}) {
		i -= _struct_putArray2Int32(buf[:i], &m.Ends)
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if m.Next != nil {
		w, _ := m.Next.encodeKanon(buf[:i])
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. The error
// is always nil.
func (m *Chain) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	m.encodeKanon(out)
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. The error is always nil.
func (m *Chain) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which do not copy data, since Chain contains no string.
func (m *Chain) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Chain) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := "", opts.Offset
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Chain) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := "", opts.Offset
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Chain
// call it.
func (m *Chain) decodeKanon(data []byte, slab string, off, depth int) error {
	m.Ends = [2]int32{}
	seen, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{})
	if seen[0]&(1<<0) == 0 {
		m.Next = nil
	}
	return err
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Chain
// call it.
func (m *Chain) mergeKanon(data []byte, slab string, off, depth int) error {
	_, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{^uint64(0)})
	return err
}

// fieldsKanon decodes the fields in data into m for decodeKanon and mergeKanon.
// The first occurrence of a tracked field whose bit in seen is clear decodes
// into the memory of the field, and every other occurrence merges. fieldsKanon
// returns seen with the bits of the tracked fields that data contains.
func (m *Chain) fieldsKanon(data []byte, slab string, off, depth int, seen [1]uint64) ([1]uint64, error) {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return seen, wire.ReadError(n, "Chain", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Chain.Next", off+at)
			}
			if m.Next == nil {
				m.Next = new(Chain)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Chain.Next", 1, off+i)
			}
			i += n
			if depth < 2 {
				return seen, wire.DepthError("Chain", 0, off+i)
			}
			var err error
			if seen[0]&(1<<0) == 0 {
				seen[0] |= 1 << 0
				err = m.Next.decodeKanon(data[i:i+int(l)], slab, off+i, depth-2)
			} else {
				err = m.Next.mergeKanon(data[i:i+int(l)], slab, off+i, depth-2)
			}
			if err != nil {
				return seen, err
			}
			i += int(l)
		case 2:
			if tag != 2<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Chain.Ends", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Chain.Ends", 2, off+i)
			}
			i += n
			if err := _struct_readArray2Int32(&m.Ends, data[i:i+int(l)], slab, off+i, depth-1, "Chain.Ends", 2); err != nil {
				return seen, err
			}
			i += int(l)
		default:
			n, err := wire.Skip(data[i:], tag, "Chain", 0, off+at)
			if err != nil {
				return seen, err
			}
			i += n
		}
	}
	return seen, nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded data stays
// reachable through m.
func (m *Chain) Reset() {
	if m == nil {
		return
	}
	m.Next = nil
	m.Ends = [2]int32{}
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Chain) CloneKanon() *Chain {
	if m == nil {
		return nil
	}
	c := new(Chain)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Chain call it.
func (m *Chain) cloneKanon(c *Chain) {
	c.Next = _struct_clonePtrChain(m.Next)
	c.Ends = m.Ends
}

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Structs) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if len(m.Point) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapPointString(m.Point))
	}
	if len(m.Label) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapExternalLabelString(m.Label))
	}
	if len(m.Spot) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapSpotString(m.Spot))
	}
	if len(m.Cell) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapAnyString(m.Cell))
	}
	if len(m.Pair) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapExternalPairInt32StringString(m.Pair))
	}
	if len(m.Link) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapLinkString(m.Link))
	}
	if len(m.Padded) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapPaddedString(m.Padded))
	}
	if len(m.Nothing) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapAnyString2(m.Nothing))
	}
	if len(m.Unit) > 0 {
		n += 1 + wire.SizeBytes(len(m.Unit)*2)
	}
	if len(m.Mute) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapMuteString(m.Mute))
	}
	if len(m.Chain) > 0 {
		n += 1 + wire.SizeBytes(_struct_sizeMapChainString(m.Chain))
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer. It
// fails when the value of a field fails to encode: a type that encodes itself
// returns an error, ValidateKanon of a type rejects a value, an interface
// stores a type that the tag option types of its field does not list, or a map
// has a key with a NaN component or two keys of one projection.
func (m *Structs) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. It fails when the value of a field
// fails to encode: a type that encodes itself returns an error, ValidateKanon
// of a type rejects a value, an interface stores a type that the tag option
// types of its field does not list, or a map has a key with a NaN component or
// two keys of one projection.
func (m *Structs) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if len(m.Chain) > 0 {
		w, err := _struct_putMapChainString(buf[:i], m.Chain, "Structs.Chain", 11)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 11<<3|wire.Bytes)
	}
	if len(m.Mute) > 0 {
		w, err := _struct_putMapMuteString(buf[:i], m.Mute, "Structs.Mute", 10)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 10<<3|wire.Bytes)
	}
	if len(m.Unit) > 0 {
		i -= _struct_putMapAnyAny(buf[:i], m.Unit)
		i = wire.PutTag(buf, i, 9<<3|wire.Bytes)
	}
	if len(m.Nothing) > 0 {
		i -= _struct_putMapAnyString2(buf[:i], m.Nothing)
		i = wire.PutTag(buf, i, 8<<3|wire.Bytes)
	}
	if len(m.Padded) > 0 {
		i -= _struct_putMapPaddedString(buf[:i], m.Padded)
		i = wire.PutTag(buf, i, 7<<3|wire.Bytes)
	}
	if len(m.Link) > 0 {
		w, err := _struct_putMapLinkString(buf[:i], m.Link, "Structs.Link", 6)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 6<<3|wire.Bytes)
	}
	if len(m.Pair) > 0 {
		i -= _struct_putMapExternalPairInt32StringString(buf[:i], m.Pair)
		i = wire.PutTag(buf, i, 5<<3|wire.Bytes)
	}
	if len(m.Cell) > 0 {
		i -= _struct_putMapAnyString(buf[:i], m.Cell)
		i = wire.PutTag(buf, i, 4<<3|wire.Bytes)
	}
	if len(m.Spot) > 0 {
		w, err := _struct_putMapSpotString(buf[:i], m.Spot, "Structs.Spot", 3)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 3<<3|wire.Bytes)
	}
	if len(m.Label) > 0 {
		w, err := _struct_putMapExternalLabelString(buf[:i], m.Label, "Structs.Label", 2)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if len(m.Point) > 0 {
		i -= _struct_putMapPointString(buf[:i], m.Point)
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. It fails
// when the value of a field fails to encode: a type that encodes itself returns
// an error, ValidateKanon of a type rejects a value, an interface stores a type
// that the tag option types of its field does not list, or a map has a key with
// a NaN component or two keys of one projection.
func (m *Structs) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	if _, err := m.encodeKanon(out); err != nil {
		return b, err
	}
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. It fails when the value of a field fails to encode: a type that
// encodes itself returns an error, ValidateKanon of a type rejects a value, an
// interface stores a type that the tag option types of its field does not list,
// or a map has a key with a NaN component or two keys of one projection.
func (m *Structs) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which copy data once.
func (m *Structs) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Structs) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Structs) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Structs
// call it.
func (m *Structs) decodeKanon(data []byte, slab string, off, depth int) error {
	seen, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{})
	if seen[0]&(1<<0) == 0 {
		clear(m.Point)
	}
	if seen[0]&(1<<1) == 0 {
		clear(m.Label)
	}
	if seen[0]&(1<<2) == 0 {
		clear(m.Spot)
	}
	if seen[0]&(1<<3) == 0 {
		clear(m.Cell)
	}
	if seen[0]&(1<<4) == 0 {
		clear(m.Pair)
	}
	if seen[0]&(1<<5) == 0 {
		clear(m.Link)
	}
	if seen[0]&(1<<6) == 0 {
		clear(m.Padded)
	}
	if seen[0]&(1<<7) == 0 {
		clear(m.Nothing)
	}
	if seen[0]&(1<<8) == 0 {
		clear(m.Unit)
	}
	if seen[0]&(1<<9) == 0 {
		clear(m.Mute)
	}
	if seen[0]&(1<<10) == 0 {
		clear(m.Chain)
	}
	return err
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Structs
// call it.
func (m *Structs) mergeKanon(data []byte, slab string, off, depth int) error {
	_, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{^uint64(0)})
	return err
}

// fieldsKanon decodes the fields in data into m for decodeKanon and mergeKanon.
// The first occurrence of a tracked field whose bit in seen is clear decodes
// into the memory of the field, and every other occurrence merges. fieldsKanon
// returns seen with the bits of the tracked fields that data contains.
func (m *Structs) fieldsKanon(data []byte, slab string, off, depth int, seen [1]uint64) ([1]uint64, error) {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return seen, wire.ReadError(n, "Structs", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Point", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Point", 1, off+i)
			}
			i += n
			if err := _struct_readMapPointString(&m.Point, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<0) == 0, "Structs.Point", 1); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 0
		case 2:
			if tag != 2<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Label", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Label", 2, off+i)
			}
			i += n
			if err := _struct_readMapExternalLabelString(&m.Label, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<1) == 0, "Structs.Label", 2); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 1
		case 3:
			if tag != 3<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Spot", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Spot", 3, off+i)
			}
			i += n
			if err := _struct_readMapSpotString(&m.Spot, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<2) == 0, "Structs.Spot", 3); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 2
		case 4:
			if tag != 4<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Cell", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Cell", 4, off+i)
			}
			i += n
			if err := _struct_readMapAnyString(&m.Cell, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<3) == 0, "Structs.Cell", 4); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 3
		case 5:
			if tag != 5<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Pair", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Pair", 5, off+i)
			}
			i += n
			if err := _struct_readMapExternalPairInt32StringString(&m.Pair, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<4) == 0, "Structs.Pair", 5); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 4
		case 6:
			if tag != 6<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Link", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Link", 6, off+i)
			}
			i += n
			if err := _struct_readMapLinkString(&m.Link, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<5) == 0, "Structs.Link", 6); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 5
		case 7:
			if tag != 7<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Padded", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Padded", 7, off+i)
			}
			i += n
			if err := _struct_readMapPaddedString(&m.Padded, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<6) == 0, "Structs.Padded", 7); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 6
		case 8:
			if tag != 8<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Nothing", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Nothing", 8, off+i)
			}
			i += n
			if err := _struct_readMapAnyString2(&m.Nothing, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<7) == 0, "Structs.Nothing", 8); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 7
		case 9:
			if tag != 9<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Unit", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Unit", 9, off+i)
			}
			i += n
			if err := _struct_readMapAnyAny(&m.Unit, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<8) == 0, "Structs.Unit", 9); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 8
		case 10:
			if tag != 10<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Mute", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Mute", 10, off+i)
			}
			i += n
			if err := _struct_readMapMuteString(&m.Mute, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<9) == 0, "Structs.Mute", 10); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 9
		case 11:
			if tag != 11<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Structs.Chain", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Structs.Chain", 11, off+i)
			}
			i += n
			if err := _struct_readMapChainString(&m.Chain, data[i:i+int(l)], slab, off+i, depth-1, seen[0]&(1<<10) == 0, "Structs.Chain", 11); err != nil {
				return seen, err
			}
			i += int(l)
			seen[0] |= 1 << 10
		default:
			n, err := wire.Skip(data[i:], tag, "Structs", 0, off+at)
			if err != nil {
				return seen, err
			}
			i += n
		}
	}
	return seen, nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded data stays
// reachable through m.
func (m *Structs) Reset() {
	if m == nil {
		return
	}
	clear(m.Point)
	clear(m.Label)
	clear(m.Spot)
	clear(m.Cell)
	clear(m.Pair)
	clear(m.Link)
	clear(m.Padded)
	clear(m.Nothing)
	clear(m.Unit)
	clear(m.Mute)
	clear(m.Chain)
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Structs) CloneKanon() *Structs {
	if m == nil {
		return nil
	}
	c := new(Structs)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Structs call it.
func (m *Structs) cloneKanon(c *Structs) {
	c.Point = _struct_cloneMapPointString(m.Point)
	c.Label = _struct_cloneMapExternalLabelString(m.Label)
	c.Spot = _struct_cloneMapSpotString(m.Spot)
	c.Cell = _struct_cloneMapAnyString(m.Cell)
	c.Pair = _struct_cloneMapExternalPairInt32StringString(m.Pair)
	c.Link = _struct_cloneMapLinkString(m.Link)
	c.Padded = _struct_cloneMapPaddedString(m.Padded)
	c.Nothing = _struct_cloneMapAnyString2(m.Nothing)
	c.Unit = maps.Clone(m.Unit)
	c.Mute = _struct_cloneMapMuteString(m.Mute)
	c.Chain = _struct_cloneMapChainString(m.Chain)
}

// _struct_sizeArray2Int32 returns the length of the encoding of the elements of
// x, a [2]int32.
func _struct_sizeArray2Int32(x *[2]int32) int {
	n := 0
	for k := range x {
		n += wire.SizeUvarint(wire.Zigzag(int64(x[k])))
	}
	return n
}

// _struct_putArray2Int32 writes the encoding of x, a [2]int32, into the end of
// buf, which has room for it, and returns its length.
func _struct_putArray2Int32(buf []byte, x *[2]int32) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(x[k])))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _struct_readArray2Int32 decodes the elements that data encodes, a [2]int32
// without its length, into *dst. It fails unless data encodes exactly 2
// elements. data starts at offset off of slab, and the decode enters depth
// levels below the value at most. loc and num locate the field in errors.
func _struct_readArray2Int32(dst *[2]int32, data []byte, slab string, off, depth int, loc string, num int) error {
	i := 0
	for k := range dst {
		u, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, loc, num, off+i)
		}
		s := wire.Unzigzag(u)
		if s != int64(int32(s)) {
			return wire.RangeError(s, "int32", loc, num, off+i)
		}
		dst[k] = int32(s)
		i += n
	}
	if i != len(data) {
		return wire.TrailingError(len(data)-i, loc, num, off+i)
	}
	return nil
}

// _struct_clonePtrChain returns a pointer to a copy of the value that x, a
// *Chain, points at, and nil for a nil x.
func _struct_clonePtrChain(x *Chain) *Chain {
	if x == nil {
		return nil
	}
	return x.CloneKanon()
}

// _struct_sizeMapPointString returns the length of the encoding of the keys and
// values of x, a map[Point]string.
func _struct_sizeMapPointString(x map[Point]string) int {
	n := 0
	var mk Point
	var mv string
	for mk, mv = range x {
		n += wire.SizeBytes(mk.SizeKanon()) + wire.SizeBytes(len(mv))
	}
	return n
}

// _struct_sizeMapExternalLabelString returns the length of the encoding of the
// keys and values of x, a map[external.Label]string.
func _struct_sizeMapExternalLabelString(x map[external.Label]string) int {
	n := 0
	var mk external.Label
	var mv string
	for mk, mv = range x {
		n += wire.SizeBytes(mk.SizeKanon()) + wire.SizeBytes(len(mv))
	}
	return n
}

// _struct_sizeMapSpotString returns the length of the encoding of the keys and
// values of x, a map[Spot]string.
func _struct_sizeMapSpotString(x map[Spot]string) int {
	n := 0
	var mk Spot
	var mv string
	for mk, mv = range x {
		n += wire.SizeBytes(_struct_sizeSpot(&mk)) + wire.SizeBytes(len(mv))
	}
	return n
}

// _struct_sizeMapAnyString returns the length of the encoding of the keys and
// values of x, a map[struct{Row int8; Col int8}]string.
func _struct_sizeMapAnyString(x map[struct {
	Row int8
	Col int8
}]string) int {
	n := 0
	var mk struct {
		Row int8
		Col int8
	}
	var mv string
	for mk, mv = range x {
		n += wire.SizeBytes(_struct_sizeStructsCellKey(&mk)) + wire.SizeBytes(len(mv))
	}
	return n
}

// _struct_sizeMapExternalPairInt32StringString returns the length of the
// encoding of the keys and values of x, a map[external.Pair[int32,
// string]]string.
func _struct_sizeMapExternalPairInt32StringString(x map[external.Pair[int32, string]]string) int {
	n := 0
	var mk external.Pair[int32, string]
	var mv string
	for mk, mv = range x {
		n += wire.SizeBytes(_struct_sizeExternalPairInt32String(&mk)) + wire.SizeBytes(len(mv))
	}
	return n
}

// _struct_sizeMapLinkString returns the length of the encoding of the keys and
// values of x, a map[Link]string.
func _struct_sizeMapLinkString(x map[Link]string) int {
	n := 0
	var mk Link
	var mv string
	for mk, mv = range x {
		n += wire.SizeBytes(_struct_sizeLink(&mk)) + wire.SizeBytes(len(mv))
	}
	return n
}

// _struct_sizeMapPaddedString returns the length of the encoding of the keys
// and values of x, a map[Padded]string.
func _struct_sizeMapPaddedString(x map[Padded]string) int {
	n := 0
	var mk Padded
	var mv string
	for mk, mv = range x {
		n += wire.SizeBytes(_struct_sizePadded(&mk)) + wire.SizeBytes(len(mv))
	}
	return n
}

// _struct_sizeMapAnyString2 returns the length of the encoding of the keys and
// values of x, a map[struct{}]string.
func _struct_sizeMapAnyString2(x map[struct{}]string) int {
	n := len(x)
	var mv string
	for _, mv = range x {
		n += wire.SizeBytes(len(mv))
	}
	return n
}

// _struct_sizeMapMuteString returns the length of the encoding of the keys and
// values of x, a map[Mute]string.
func _struct_sizeMapMuteString(x map[Mute]string) int {
	n := len(x)
	var mv string
	for _, mv = range x {
		n += wire.SizeBytes(len(mv))
	}
	return n
}

// _struct_sizeMapChainString returns the length of the encoding of the keys and
// values of x, a map[Chain]string.
func _struct_sizeMapChainString(x map[Chain]string) int {
	n := 0
	var mk Chain
	var mv string
	for mk, mv = range x {
		n += wire.SizeBytes(mk.SizeKanon()) + wire.SizeBytes(len(mv))
	}
	return n
}

// _struct_putMapChainString writes the encoding of x, a map[Chain]string, into
// the end of buf, which has room for it, and returns its length. It fails for a
// value that fails to encode, a key with a NaN component and two keys of one
// projection, which loc and num locate.
func _struct_putMapChainString(buf []byte, x map[Chain]string, loc string, num int) (int, error) {
	i := len(buf)
	type pair = wire.Pair[Chain, string]
	var arr [16]pair
	pairs := arr[:0]
	for mk, mv := range x {
		pairs = append(pairs, pair{Key: mk, Value: mv})
	}
	slices.SortFunc(pairs, func(a, b pair) int {
		return _struct_compareChain(a.Key, b.Key)
	})
	err := wire.PairTies(pairs, _struct_compareChain, loc, num)
	for k := len(pairs) - 1; err == nil && k >= 0; k-- {
		i = wire.PutRaw(buf, i, pairs[k].Value)
		i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Value)))
		{
			w, _ := pairs[k].Key.encodeKanon(buf[:i])
			i -= w
			i = wire.PutUvarint(buf, i, uint64(w))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, err
}

// _struct_putMapMuteString writes the encoding of x, a map[Mute]string, into
// the end of buf, which has room for it, and returns its length. It fails for a
// value that fails to encode, a key with a NaN component and two keys of one
// projection, which loc and num locate.
func _struct_putMapMuteString(buf []byte, x map[Mute]string, loc string, num int) (int, error) {
	i := len(buf)
	err := wire.OneKey(len(x), loc, num)
	if err == nil {
		for _, mv := range x {
			i = wire.PutRaw(buf, i, mv)
			i = wire.PutUvarint(buf, i, uint64(len(mv)))
			i = wire.PutUvarint(buf, i, 0)
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, err
}

// _struct_putMapAnyAny writes the encoding of x, a map[struct{}]struct{}, into
// the end of buf, which has room for it, and returns its length.
func _struct_putMapAnyAny(buf []byte, x map[struct{}]struct{}) int {
	i := len(buf)
	for range x {
		i = wire.PutUvarint(buf, i, 0)
		i = wire.PutUvarint(buf, i, 0)
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _struct_putMapAnyString2 writes the encoding of x, a map[struct{}]string,
// into the end of buf, which has room for it, and returns its length.
func _struct_putMapAnyString2(buf []byte, x map[struct{}]string) int {
	i := len(buf)
	for _, mv := range x {
		i = wire.PutRaw(buf, i, mv)
		i = wire.PutUvarint(buf, i, uint64(len(mv)))
		i = wire.PutUvarint(buf, i, 0)
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _struct_putMapPaddedString writes the encoding of x, a map[Padded]string,
// into the end of buf, which has room for it, and returns its length.
func _struct_putMapPaddedString(buf []byte, x map[Padded]string) int {
	i := len(buf)
	type pair = wire.Pair[Padded, string]
	var arr [16]pair
	pairs := arr[:0]
	for mk, mv := range x {
		pairs = append(pairs, pair{Key: mk, Value: mv})
	}
	slices.SortFunc(pairs, func(a, b pair) int {
		return _struct_comparePadded(a.Key, b.Key)
	})
	for k := len(pairs) - 1; k >= 0; k-- {
		i = wire.PutRaw(buf, i, pairs[k].Value)
		i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Value)))
		{
			w := _struct_putPadded(buf[:i], &pairs[k].Key)
			i -= w
			i = wire.PutUvarint(buf, i, uint64(w))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _struct_putMapLinkString writes the encoding of x, a map[Link]string, into
// the end of buf, which has room for it, and returns its length. It fails for a
// value that fails to encode, a key with a NaN component and two keys of one
// projection, which loc and num locate.
func _struct_putMapLinkString(buf []byte, x map[Link]string, loc string, num int) (int, error) {
	i := len(buf)
	type pair = wire.Pair[Link, string]
	var arr [16]pair
	pairs := arr[:0]
	for mk, mv := range x {
		pairs = append(pairs, pair{Key: mk, Value: mv})
	}
	slices.SortFunc(pairs, func(a, b pair) int {
		return _struct_compareLink(a.Key, b.Key)
	})
	err := wire.PairTies(pairs, _struct_compareLink, loc, num)
	for k := len(pairs) - 1; err == nil && k >= 0; k-- {
		i = wire.PutRaw(buf, i, pairs[k].Value)
		i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Value)))
		{
			w := _struct_putLink(buf[:i], &pairs[k].Key)
			i -= w
			i = wire.PutUvarint(buf, i, uint64(w))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, err
}

// _struct_putMapExternalPairInt32StringString writes the encoding of x, a
// map[external.Pair[int32, string]]string, into the end of buf, which has room
// for it, and returns its length.
func _struct_putMapExternalPairInt32StringString(buf []byte, x map[external.Pair[int32, string]]string) int {
	i := len(buf)
	type pair = wire.Pair[external.Pair[int32, string], string]
	var arr [16]pair
	pairs := arr[:0]
	for mk, mv := range x {
		pairs = append(pairs, pair{Key: mk, Value: mv})
	}
	slices.SortFunc(pairs, func(a, b pair) int {
		return _struct_compareExternalPairInt32String(a.Key, b.Key)
	})
	for k := len(pairs) - 1; k >= 0; k-- {
		i = wire.PutRaw(buf, i, pairs[k].Value)
		i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Value)))
		{
			w := _struct_putExternalPairInt32String(buf[:i], &pairs[k].Key)
			i -= w
			i = wire.PutUvarint(buf, i, uint64(w))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _struct_putMapAnyString writes the encoding of x, a map[struct{Row int8; Col
// int8}]string, into the end of buf, which has room for it, and returns its
// length.
func _struct_putMapAnyString(buf []byte, x map[struct {
	Row int8
	Col int8
}]string) int {
	i := len(buf)
	type pair = wire.Pair[struct {
		Row int8
		Col int8
	}, string]
	var arr [16]pair
	pairs := arr[:0]
	for mk, mv := range x {
		pairs = append(pairs, pair{Key: mk, Value: mv})
	}
	slices.SortFunc(pairs, func(a, b pair) int {
		return _struct_compareStructsCellKey(a.Key, b.Key)
	})
	for k := len(pairs) - 1; k >= 0; k-- {
		i = wire.PutRaw(buf, i, pairs[k].Value)
		i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Value)))
		{
			w := _struct_putStructsCellKey(buf[:i], &pairs[k].Key)
			i -= w
			i = wire.PutUvarint(buf, i, uint64(w))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _struct_putMapSpotString writes the encoding of x, a map[Spot]string, into
// the end of buf, which has room for it, and returns its length. It fails for a
// value that fails to encode, a key with a NaN component and two keys of one
// projection, which loc and num locate.
func _struct_putMapSpotString(buf []byte, x map[Spot]string, loc string, num int) (int, error) {
	i := len(buf)
	type pair = wire.Pair[Spot, string]
	var arr [16]pair
	pairs := arr[:0]
	for mk, mv := range x {
		pairs = append(pairs, pair{Key: mk, Value: mv})
	}
	slices.SortFunc(pairs, func(a, b pair) int {
		return _struct_compareSpot(a.Key, b.Key)
	})
	err := wire.PairTies(pairs, _struct_compareSpot, loc, num)
	for k := len(pairs) - 1; err == nil && k >= 0; k-- {
		i = wire.PutRaw(buf, i, pairs[k].Value)
		i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Value)))
		{
			w := _struct_putSpot(buf[:i], &pairs[k].Key)
			i -= w
			i = wire.PutUvarint(buf, i, uint64(w))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, err
}

// _struct_putMapExternalLabelString writes the encoding of x, a
// map[external.Label]string, into the end of buf, which has room for it, and
// returns its length. It fails for a value that fails to encode, a key with a
// NaN component and two keys of one projection, which loc and num locate.
func _struct_putMapExternalLabelString(buf []byte, x map[external.Label]string, loc string, num int) (int, error) {
	i := len(buf)
	type pair = wire.Pair[external.Label, string]
	var arr [16]pair
	pairs := arr[:0]
	for mk, mv := range x {
		pairs = append(pairs, pair{Key: mk, Value: mv})
	}
	slices.SortFunc(pairs, func(a, b pair) int {
		return _struct_compareExternalLabel(a.Key, b.Key)
	})
	err := wire.PairTies(pairs, _struct_compareExternalLabel, loc, num)
	for k := len(pairs) - 1; err == nil && k >= 0; k-- {
		i = wire.PutRaw(buf, i, pairs[k].Value)
		i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Value)))
		{
			w, err := pairs[k].Key.EncodeKanon(buf[:i])
			if err != nil {
				return 0, err
			}
			i -= w
			i = wire.PutUvarint(buf, i, uint64(w))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, err
}

// _struct_putMapPointString writes the encoding of x, a map[Point]string, into
// the end of buf, which has room for it, and returns its length.
func _struct_putMapPointString(buf []byte, x map[Point]string) int {
	i := len(buf)
	type pair = wire.Pair[Point, string]
	var arr [16]pair
	pairs := arr[:0]
	for mk, mv := range x {
		pairs = append(pairs, pair{Key: mk, Value: mv})
	}
	slices.SortFunc(pairs, func(a, b pair) int {
		return _struct_comparePoint(a.Key, b.Key)
	})
	for k := len(pairs) - 1; k >= 0; k-- {
		i = wire.PutRaw(buf, i, pairs[k].Value)
		i = wire.PutUvarint(buf, i, uint64(len(pairs[k].Value)))
		{
			w, _ := pairs[k].Key.encodeKanon(buf[:i])
			i -= w
			i = wire.PutUvarint(buf, i, uint64(w))
		}
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _struct_readMapPointString adds the entries that data encodes, a
// map[Point]string without its length, to *dst. With collect set, it clears
// *dst first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _struct_readMapPointString(dst *map[Point]string, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[Point]string)
		*dst = x
	}
	var mk Point
	var mv string
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("Point", 0, off+i)
			}
			if err := mk.decodeKanon(data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mv = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _struct_readMapExternalLabelString adds the entries that data encodes, a
// map[external.Label]string without its length, to *dst. With collect set, it
// clears *dst first, and the entries reuse the memory of up to 16 of its
// values. data starts at offset off of slab, and the decode enters depth levels
// below the value at most. loc and num locate the field in errors.
func _struct_readMapExternalLabelString(dst *map[external.Label]string, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	var arr [16]external.Label
	keys := arr[:0]
	var err error
	if !collect {
		keys, err = wire.MergeKeys(x, keys, _struct_canonExternalLabel, _struct_compareExternalLabel, loc, num, off)
	}
	all := len(keys) != 0
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[external.Label]string)
		*dst = x
	}
	var mk external.Label
	var mv string
	for i := 0; err == nil && i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("external.Label", 0, off+i)
			}
			if err := mk.DecodeKanon(data[i:i+int(l)], wire.Nested(slab, off+i, depth-1)); err != nil {
				return err
			}
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mv = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		x[mk] = mv
		if all || !_struct_canonExternalLabel(mk) {
			keys = append(keys, mk)
		}
	}
	wire.KeepLastKeys(x, keys, _struct_compareExternalLabel)
	return err
}

// _struct_readMapSpotString adds the entries that data encodes, a
// map[Spot]string without its length, to *dst. With collect set, it clears *dst
// first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _struct_readMapSpotString(dst *map[Spot]string, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	var arr [16]Spot
	keys := arr[:0]
	var err error
	if !collect {
		keys, err = wire.MergeKeys(x, keys, _struct_canonSpot, _struct_compareSpot, loc, num, off)
	}
	all := len(keys) != 0
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[Spot]string)
		*dst = x
	}
	var mk Spot
	var mv string
	for i := 0; err == nil && i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("Spot", 0, off+i)
			}
			if err := _struct_readSpot(&mk, data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mv = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		x[mk] = mv
		if all || !_struct_canonSpot(mk) {
			keys = append(keys, mk)
		}
	}
	wire.KeepLastKeys(x, keys, _struct_compareSpot)
	return err
}

// _struct_readMapAnyString adds the entries that data encodes, a map[struct{Row
// int8; Col int8}]string without its length, to *dst. With collect set, it
// clears *dst first, and the entries reuse the memory of up to 16 of its
// values. data starts at offset off of slab, and the decode enters depth levels
// below the value at most. loc and num locate the field in errors.
func _struct_readMapAnyString(dst *map[struct {
	Row int8
	Col int8
}]string, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[struct {
			Row int8
			Col int8
		}]string)
		*dst = x
	}
	var mk struct {
		Row int8
		Col int8
	}
	var mv string
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("Structs.Cell[key]", 0, off+i)
			}
			if err := _struct_readStructsCellKey(&mk, data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mv = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _struct_readMapExternalPairInt32StringString adds the entries that data
// encodes, a map[external.Pair[int32, string]]string without its length, to
// *dst. With collect set, it clears *dst first, and the entries reuse the
// memory of up to 16 of its values. data starts at offset off of slab, and the
// decode enters depth levels below the value at most. loc and num locate the
// field in errors.
func _struct_readMapExternalPairInt32StringString(dst *map[external.Pair[int32, string]]string, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[external.Pair[int32, string]]string)
		*dst = x
	}
	var mk external.Pair[int32, string]
	var mv string
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("external.Pair[int32, string]", 0, off+i)
			}
			if err := _struct_readExternalPairInt32String(&mk, data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mv = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _struct_readMapLinkString adds the entries that data encodes, a
// map[Link]string without its length, to *dst. With collect set, it clears *dst
// first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _struct_readMapLinkString(dst *map[Link]string, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	var arr [16]Link
	keys := arr[:0]
	var err error
	if !collect {
		keys, err = wire.MergeKeys(x, keys, _struct_canonLink, _struct_compareLink, loc, num, off)
	}
	all := len(keys) != 0
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[Link]string)
		*dst = x
	}
	var mk Link
	var mv string
	for i := 0; err == nil && i < len(data); {
		mk = Link{}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("Link", 0, off+i)
			}
			if err := _struct_readLink(&mk, data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mv = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		x[mk] = mv
		if all || !_struct_canonLink(mk) {
			keys = append(keys, mk)
		}
	}
	wire.KeepLastKeys(x, keys, _struct_compareLink)
	return err
}

// _struct_readMapPaddedString adds the entries that data encodes, a
// map[Padded]string without its length, to *dst. With collect set, it clears
// *dst first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _struct_readMapPaddedString(dst *map[Padded]string, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[Padded]string)
		*dst = x
	}
	var mk Padded
	var mv string
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("Padded", 0, off+i)
			}
			if err := _struct_readPadded(&mk, data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mv = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _struct_readMapAnyString2 adds the entries that data encodes, a
// map[struct{}]string without its length, to *dst. With collect set, it clears
// *dst first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _struct_readMapAnyString2(dst *map[struct{}]string, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[struct{}]string)
		*dst = x
	}
	var mk struct{}
	var mv string
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("Structs.Nothing[key]", 0, off+i)
			}
			if err := _struct_readStructsNothingKey(&mk, data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mv = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _struct_readMapAnyAny adds the entries that data encodes, a
// map[struct{}]struct{} without its length, to *dst. With collect set, it
// clears *dst first, and the entries reuse the memory of up to 16 of its
// values. data starts at offset off of slab, and the decode enters depth levels
// below the value at most. loc and num locate the field in errors.
func _struct_readMapAnyAny(dst *map[struct{}]struct{}, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[struct{}]struct{})
		*dst = x
	}
	var mk struct{}
	var mv struct{}
	for i := 0; i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("Structs.Nothing[key]", 0, off+i)
			}
			if err := _struct_readStructsNothingKey(&mk, data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if err := _struct_readStructsNothingKey(&mv, data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		x[mk] = mv
	}
	return nil
}

// _struct_readMapMuteString adds the entries that data encodes, a
// map[Mute]string without its length, to *dst. With collect set, it clears *dst
// first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _struct_readMapMuteString(dst *map[Mute]string, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	var arr [16]Mute
	keys := arr[:0]
	var err error
	if !collect {
		keys, err = wire.MergeKeys(x, keys, _struct_canonMute, _struct_compareMute, loc, num, off)
	}
	all := len(keys) != 0
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[Mute]string)
		*dst = x
	}
	var mk Mute
	var mv string
	for i := 0; err == nil && i < len(data); {
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("Mute", 0, off+i)
			}
			if err := _struct_readMute(&mk, data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mv = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		x[mk] = mv
		if all || !_struct_canonMute(mk) {
			keys = append(keys, mk)
		}
	}
	wire.KeepLastKeys(x, keys, _struct_compareMute)
	return err
}

// _struct_readMapChainString adds the entries that data encodes, a
// map[Chain]string without its length, to *dst. With collect set, it clears
// *dst first, and the entries reuse the memory of up to 16 of its values. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most. loc and num locate the field in errors.
func _struct_readMapChainString(dst *map[Chain]string, data []byte, slab string, off, depth int, collect bool, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	var arr [16]Chain
	keys := arr[:0]
	var err error
	if !collect {
		keys, err = wire.MergeKeys(x, keys, _struct_canonChain, _struct_compareChain, loc, num, off)
	}
	all := len(keys) != 0
	if collect {
		clear(x)
	}
	if x == nil && len(data) > 0 {
		x = make(map[Chain]string)
		*dst = x
	}
	var mk Chain
	var mv string
	for i := 0; err == nil && i < len(data); {
		mk = Chain{}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			if depth < 1 {
				return wire.DepthError("Chain", 0, off+i)
			}
			if err := mk.decodeKanon(data[i:i+int(l)], slab, off+i, depth-1); err != nil {
				return err
			}
			i += int(l)
		}
		{
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, loc, num, off+i)
			}
			i += n
			mv = slab[off+i : off+i+int(l)]
			i += int(l)
		}
		x[mk] = mv
		if all || !_struct_canonChain(mk) {
			keys = append(keys, mk)
		}
	}
	wire.KeepLastKeys(x, keys, _struct_compareChain)
	return err
}

// _struct_cloneMapPointString returns a copy of x, a map[Point]string, and nil
// for a nil x.
func _struct_cloneMapPointString(x map[Point]string) map[Point]string {
	if x == nil {
		return nil
	}
	c := make(map[Point]string, len(x))
	for mk, mv := range x {
		c[mk] = strings.Clone(mv)
	}
	return c
}

// _struct_cloneMapExternalLabelString returns a copy of x, a
// map[external.Label]string, and nil for a nil x.
func _struct_cloneMapExternalLabelString(x map[external.Label]string) map[external.Label]string {
	if x == nil {
		return nil
	}
	c := make(map[external.Label]string, len(x))
	for mk, mv := range x {
		c[*mk.CloneKanon()] = strings.Clone(mv)
	}
	return c
}

// _struct_cloneMapSpotString returns a copy of x, a map[Spot]string, and nil
// for a nil x.
func _struct_cloneMapSpotString(x map[Spot]string) map[Spot]string {
	if x == nil {
		return nil
	}
	c := make(map[Spot]string, len(x))
	for mk, mv := range x {
		var ck Spot
		_struct_cloneSpot(&ck, &mk)
		c[ck] = strings.Clone(mv)
	}
	return c
}

// _struct_cloneMapAnyString returns a copy of x, a map[struct{Row int8; Col
// int8}]string, and nil for a nil x.
func _struct_cloneMapAnyString(x map[struct {
	Row int8
	Col int8
}]string) map[struct {
	Row int8
	Col int8
}]string {
	if x == nil {
		return nil
	}
	c := make(map[struct {
		Row int8
		Col int8
	}]string, len(x))
	for mk, mv := range x {
		c[mk] = strings.Clone(mv)
	}
	return c
}

// _struct_cloneMapExternalPairInt32StringString returns a copy of x, a
// map[external.Pair[int32, string]]string, and nil for a nil x.
func _struct_cloneMapExternalPairInt32StringString(x map[external.Pair[int32, string]]string) map[external.Pair[int32, string]]string {
	if x == nil {
		return nil
	}
	c := make(map[external.Pair[int32, string]]string, len(x))
	for mk, mv := range x {
		var ck external.Pair[int32, string]
		_struct_cloneExternalPairInt32String(&ck, &mk)
		c[ck] = strings.Clone(mv)
	}
	return c
}

// _struct_cloneMapLinkString returns a copy of x, a map[Link]string, and nil
// for a nil x.
func _struct_cloneMapLinkString(x map[Link]string) map[Link]string {
	if x == nil {
		return nil
	}
	c := make(map[Link]string, len(x))
	for mk, mv := range x {
		var ck Link
		_struct_cloneLink(&ck, &mk)
		c[ck] = strings.Clone(mv)
	}
	return c
}

// _struct_cloneMapPaddedString returns a copy of x, a map[Padded]string, and
// nil for a nil x.
func _struct_cloneMapPaddedString(x map[Padded]string) map[Padded]string {
	if x == nil {
		return nil
	}
	c := make(map[Padded]string, len(x))
	for mk, mv := range x {
		c[mk] = strings.Clone(mv)
	}
	return c
}

// _struct_cloneMapAnyString2 returns a copy of x, a map[struct{}]string, and
// nil for a nil x.
func _struct_cloneMapAnyString2(x map[struct{}]string) map[struct{}]string {
	if x == nil {
		return nil
	}
	c := make(map[struct{}]string, len(x))
	for mk, mv := range x {
		c[mk] = strings.Clone(mv)
	}
	return c
}

// _struct_cloneMapMuteString returns a copy of x, a map[Mute]string, and nil
// for a nil x.
func _struct_cloneMapMuteString(x map[Mute]string) map[Mute]string {
	if x == nil {
		return nil
	}
	c := make(map[Mute]string, len(x))
	for mk, mv := range x {
		var ck Mute
		_struct_cloneMute(&ck, &mk)
		c[ck] = strings.Clone(mv)
	}
	return c
}

// _struct_cloneMapChainString returns a copy of x, a map[Chain]string, and nil
// for a nil x.
func _struct_cloneMapChainString(x map[Chain]string) map[Chain]string {
	if x == nil {
		return nil
	}
	c := make(map[Chain]string, len(x))
	for mk, mv := range x {
		var ck Chain
		mk.cloneKanon(&ck)
		c[ck] = strings.Clone(mv)
	}
	return c
}

// _struct_sizeSpot returns the length of the encoding of the Spot that m points
// at.
func _struct_sizeSpot(m *Spot) int {
	n := 0
	if m.Row != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.Row)))
	}
	if m.Col != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.Col)))
	}
	return n
}

// _struct_sizeStructsCellKey returns the length of the encoding of the
// Structs.Cell[key] that m points at.
func _struct_sizeStructsCellKey(m *struct {
	Row int8
	Col int8
}) int {
	n := 0
	if m.Row != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.Row)))
	}
	if m.Col != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.Col)))
	}
	return n
}

// _struct_sizeExternalPairInt32String returns the length of the encoding of the
// external.Pair[int32, string] that m points at.
func _struct_sizeExternalPairInt32String(m *external.Pair[int32, string]) int {
	n := 0
	if m.Key != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.Key)))
	}
	if m.Val != "" {
		n += 1 + wire.SizeBytes(len(m.Val))
	}
	return n
}

// _struct_sizeLink returns the length of the encoding of the Link that m points
// at.
func _struct_sizeLink(m *Link) int {
	n := 0
	if m.N != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.N)))
	}
	if m.Next != nil {
		n += 1 + wire.SizeBytes(_struct_sizeLink(m.Next))
	}
	return n
}

// _struct_sizePadded returns the length of the encoding of the Padded that m
// points at.
func _struct_sizePadded(m *Padded) int {
	n := 0
	if m.N != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.N)))
	}
	return n
}

// _struct_compareChain returns -1, 0 or +1 as the map key a sorts before, with
// or after b, two keys of type Chain.
func _struct_compareChain(a, b Chain) int {
	if c := _struct_comparePtrChain(a.Next, b.Next); c != 0 {
		return c
	}
	return _struct_compareArray2Int32(a.Ends, b.Ends)
}

// _struct_comparePadded returns -1, 0 or +1 as the map key a sorts before, with
// or after b, two keys of type Padded.
func _struct_comparePadded(a, b Padded) int {
	return cmp.Compare(a.N, b.N)
}

// _struct_putPadded writes the encoding of the Padded that m points at into the
// end of buf, which has room for it, and returns its length.
func _struct_putPadded(buf []byte, m *Padded) int {
	i := len(buf)
	if m.N != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.N)))
		i = wire.PutTag(buf, i, 1<<3|wire.Varint)
	}
	return len(buf) - i
}

// _struct_compareLink returns -1, 0 or +1 as the map key a sorts before, with
// or after b, two keys of type Link.
func _struct_compareLink(a, b Link) int {
	if c := cmp.Compare(a.N, b.N); c != 0 {
		return c
	}
	return _struct_comparePtrLink(a.Next, b.Next)
}

// _struct_putLink writes the encoding of the Link that m points at into the end
// of buf, which has room for it, and returns its length.
func _struct_putLink(buf []byte, m *Link) int {
	i := len(buf)
	if m.Next != nil {
		w := _struct_putLink(buf[:i], m.Next)
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if m.N != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.N)))
		i = wire.PutTag(buf, i, 1<<3|wire.Varint)
	}
	return len(buf) - i
}

// _struct_compareExternalPairInt32String returns -1, 0 or +1 as the map key a
// sorts before, with or after b, two keys of type external.Pair[int32, string].
func _struct_compareExternalPairInt32String(a, b external.Pair[int32, string]) int {
	if c := cmp.Compare(a.Key, b.Key); c != 0 {
		return c
	}
	return cmp.Compare(a.Val, b.Val)
}

// _struct_putExternalPairInt32String writes the encoding of the
// external.Pair[int32, string] that m points at into the end of buf, which has
// room for it, and returns its length.
func _struct_putExternalPairInt32String(buf []byte, m *external.Pair[int32, string]) int {
	i := len(buf)
	if m.Val != "" {
		i = wire.PutRaw(buf, i, m.Val)
		i = wire.PutUvarint(buf, i, uint64(len(m.Val)))
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if m.Key != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.Key)))
		i = wire.PutTag(buf, i, 1<<3|wire.Varint)
	}
	return len(buf) - i
}

// _struct_compareStructsCellKey returns -1, 0 or +1 as the map key a sorts
// before, with or after b, two keys of type struct{Row int8; Col int8}.
func _struct_compareStructsCellKey(a, b struct {
	Row int8
	Col int8
}) int {
	if c := cmp.Compare(a.Row, b.Row); c != 0 {
		return c
	}
	return cmp.Compare(a.Col, b.Col)
}

// _struct_putStructsCellKey writes the encoding of the Structs.Cell[key] that m
// points at into the end of buf, which has room for it, and returns its length.
func _struct_putStructsCellKey(buf []byte, m *struct {
	Row int8
	Col int8
}) int {
	i := len(buf)
	if m.Col != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.Col)))
		i = wire.PutTag(buf, i, 2<<3|wire.Varint)
	}
	if m.Row != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.Row)))
		i = wire.PutTag(buf, i, 1<<3|wire.Varint)
	}
	return len(buf) - i
}

// _struct_compareSpot returns -1, 0 or +1 as the map key a sorts before, with
// or after b, two keys of type Spot.
func _struct_compareSpot(a, b Spot) int {
	if c := cmp.Compare(a.Row, b.Row); c != 0 {
		return c
	}
	return cmp.Compare(a.Col, b.Col)
}

// _struct_putSpot writes the encoding of the Spot that m points at into the end
// of buf, which has room for it, and returns its length.
func _struct_putSpot(buf []byte, m *Spot) int {
	i := len(buf)
	if m.Col != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.Col)))
		i = wire.PutTag(buf, i, 2<<3|wire.Varint)
	}
	if m.Row != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.Row)))
		i = wire.PutTag(buf, i, 1<<3|wire.Varint)
	}
	return len(buf) - i
}

// _struct_compareExternalLabel returns -1, 0 or +1 as the map key a sorts
// before, with or after b, two keys of type external.Label.
func _struct_compareExternalLabel(a, b external.Label) int {
	if c := cmp.Compare(a.Key, b.Key); c != 0 {
		return c
	}
	if c := cmp.Compare(a.Value, b.Value); c != 0 {
		return c
	}
	if c := cmp.Compare(a.Rank, b.Rank); c != 0 {
		return c
	}
	return _struct_compareExternalMark(a.Mark, b.Mark)
}

// _struct_comparePoint returns -1, 0 or +1 as the map key a sorts before, with
// or after b, two keys of type Point.
func _struct_comparePoint(a, b Point) int {
	if c := cmp.Compare(a.Y, b.Y); c != 0 {
		return c
	}
	return cmp.Compare(a.X, b.X)
}

// _struct_canonExternalLabel reports whether x, a map key of type
// external.Label, is the key that a decode of its projection yields, so that
// the map of a decode needs no other check to keep one entry for the keys of
// one projection.
func _struct_canonExternalLabel(x external.Label) bool {
	return false
}

// _struct_canonSpot reports whether x, a map key of type Spot, is the key that
// a decode of its projection yields, so that the map of a decode needs no other
// check to keep one entry for the keys of one projection.
func _struct_canonSpot(x Spot) bool {
	return x.Note == "" && x.Tags == ([2]int8{})
}

// _struct_readSpot sets the Spot that m points at to the value encoded in data
// and reuses its memory, as DecodeKanon does. data starts at offset off of
// slab, and the decode enters depth levels below the value at most.
func _struct_readSpot(m *Spot, data []byte, slab string, off, depth int) error {
	m.Note = ""
	m.Tags = [2]int8{}
	m.Row = 0
	m.Col = 0
	return _struct_mergeSpot(m, data, slab, off, depth)
}

// _struct_readStructsCellKey sets the Structs.Cell[key] that m points at to the
// value encoded in data and reuses its memory, as DecodeKanon does. data starts
// at offset off of slab, and the decode enters depth levels below the value at
// most.
func _struct_readStructsCellKey(m *struct {
	Row int8
	Col int8
}, data []byte, slab string, off, depth int) error {
	m.Row = 0
	m.Col = 0
	return _struct_mergeStructsCellKey(m, data, slab, off, depth)
}

// _struct_readExternalPairInt32String sets the external.Pair[int32, string]
// that m points at to the value encoded in data and reuses its memory, as
// DecodeKanon does. data starts at offset off of slab, and the decode enters
// depth levels below the value at most.
func _struct_readExternalPairInt32String(m *external.Pair[int32, string], data []byte, slab string, off, depth int) error {
	m.Key = 0
	m.Val = ""
	return _struct_mergeExternalPairInt32String(m, data, slab, off, depth)
}

// _struct_canonLink reports whether x, a map key of type Link, is the key that
// a decode of its projection yields, so that the map of a decode needs no other
// check to keep one entry for the keys of one projection.
func _struct_canonLink(x Link) bool {
	return false
}

// _struct_readLink sets the Link that m points at to the value encoded in data
// and reuses its memory, as DecodeKanon does. data starts at offset off of
// slab, and the decode enters depth levels below the value at most.
func _struct_readLink(m *Link, data []byte, slab string, off, depth int) error {
	m.N = 0
	seen, err := _struct_fieldsLink(m, data, slab, off, depth, [1]uint64{})
	if seen[0]&(1<<0) == 0 {
		m.Next = nil
	}
	return err
}

// _struct_readPadded sets the Padded that m points at to the value encoded in
// data and reuses its memory, as DecodeKanon does. data starts at offset off of
// slab, and the decode enters depth levels below the value at most.
func _struct_readPadded(m *Padded, data []byte, slab string, off, depth int) error {
	m.N = 0
	return _struct_mergePadded(m, data, slab, off, depth)
}

// _struct_readStructsNothingKey sets the Structs.Nothing[key] that m points at
// to the value encoded in data and reuses its memory, as DecodeKanon does. data
// starts at offset off of slab, and the decode enters depth levels below the
// value at most.
func _struct_readStructsNothingKey(m *struct{}, data []byte, slab string, off, depth int) error {
	return _struct_mergeStructsNothingKey(m, data, slab, off, depth)
}

// _struct_canonMute reports whether x, a map key of type Mute, is the key that
// a decode of its projection yields, so that the map of a decode needs no other
// check to keep one entry for the keys of one projection.
func _struct_canonMute(x Mute) bool {
	return x.Note == ""
}

// _struct_compareMute returns -1, 0 or +1 as the map key a sorts before, with
// or after b, two keys of type Mute.
func _struct_compareMute(Mute, Mute) int {
	return 0
}

// _struct_readMute sets the Mute that m points at to the value encoded in data
// and reuses its memory, as DecodeKanon does. data starts at offset off of
// slab, and the decode enters depth levels below the value at most.
func _struct_readMute(m *Mute, data []byte, slab string, off, depth int) error {
	m.Note = ""
	return _struct_mergeMute(m, data, slab, off, depth)
}

// _struct_canonChain reports whether x, a map key of type Chain, is the key
// that a decode of its projection yields, so that the map of a decode needs no
// other check to keep one entry for the keys of one projection.
func _struct_canonChain(x Chain) bool {
	return false
}

// _struct_cloneSpot copies the Spot that src points at into the one that dst
// points at, as CloneKanon does.
func _struct_cloneSpot(dst, src *Spot) {
	dst.Row = src.Row
	dst.Col = src.Col
}

// _struct_cloneExternalPairInt32String copies the external.Pair[int32, string]
// that src points at into the one that dst points at, as CloneKanon does.
func _struct_cloneExternalPairInt32String(dst, src *external.Pair[int32, string]) {
	dst.Key = src.Key
	dst.Val = strings.Clone(src.Val)
}

// _struct_cloneLink copies the Link that src points at into the one that dst
// points at, as CloneKanon does.
func _struct_cloneLink(dst, src *Link) {
	dst.N = src.N
	dst.Next = _struct_clonePtrLink(src.Next)
}

// _struct_cloneMute copies the Mute that src points at into the one that dst
// points at, as CloneKanon does.
func _struct_cloneMute(dst, src *Mute) {
}

// _struct_comparePtrChain returns -1, 0 or +1 as the map key a sorts before,
// with or after b, two keys of type *Chain.
func _struct_comparePtrChain(a, b *Chain) int {
	if a == nil || b == nil {
		return wire.CompareBool(a != nil, b != nil)
	}
	return _struct_compareChain(*a, *b)
}

// _struct_compareArray2Int32 returns -1, 0 or +1 as the map key a sorts before,
// with or after b, two keys of type [2]int32.
func _struct_compareArray2Int32(a, b [2]int32) int {
	for k := range 1 {
		if c := cmp.Compare(a[k], b[k]); c != 0 {
			return c
		}
	}
	return cmp.Compare(a[1], b[1])
}

// _struct_comparePtrLink returns -1, 0 or +1 as the map key a sorts before,
// with or after b, two keys of type *Link.
func _struct_comparePtrLink(a, b *Link) int {
	if a == nil || b == nil {
		return wire.CompareBool(a != nil, b != nil)
	}
	return _struct_compareLink(*a, *b)
}

// _struct_compareExternalMark returns -1, 0 or +1 as the map key a sorts
// before, with or after b, two keys of type external.Mark.
func _struct_compareExternalMark(a, b external.Mark) int {
	var sa, sb [128]byte
	ea, _ := a.AppendBinary(sa[:0])
	eb, _ := b.AppendBinary(sb[:0])
	return bytes.Compare(ea, eb)
}

// _struct_mergeSpot merges the encoding in data, which starts at offset off of
// slab, into the Spot that m points at, as MergeKanon does. The decode enters
// depth levels below m at most.
func _struct_mergeSpot(m *Spot, data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "Spot", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Varint {
				return wire.FormatError(tag, wire.Varint, "Spot.Row", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, "Spot.Row", 1, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int8(s)) {
				return wire.RangeError(s, "int8", "Spot.Row", 1, off+i)
			}
			m.Row = int8(s)
			i += n
		case 2:
			if tag != 2<<3|wire.Varint {
				return wire.FormatError(tag, wire.Varint, "Spot.Col", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, "Spot.Col", 2, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int8(s)) {
				return wire.RangeError(s, "int8", "Spot.Col", 2, off+i)
			}
			m.Col = int8(s)
			i += n
		default:
			n, err := wire.Skip(data[i:], tag, "Spot", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

// _struct_mergeStructsCellKey merges the encoding in data, which starts at
// offset off of slab, into the Structs.Cell[key] that m points at, as
// MergeKanon does. The decode enters depth levels below m at most.
func _struct_mergeStructsCellKey(m *struct {
	Row int8
	Col int8
}, data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "Structs.Cell[key]", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Varint {
				return wire.FormatError(tag, wire.Varint, "Structs.Cell[key].Row", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, "Structs.Cell[key].Row", 1, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int8(s)) {
				return wire.RangeError(s, "int8", "Structs.Cell[key].Row", 1, off+i)
			}
			m.Row = int8(s)
			i += n
		case 2:
			if tag != 2<<3|wire.Varint {
				return wire.FormatError(tag, wire.Varint, "Structs.Cell[key].Col", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, "Structs.Cell[key].Col", 2, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int8(s)) {
				return wire.RangeError(s, "int8", "Structs.Cell[key].Col", 2, off+i)
			}
			m.Col = int8(s)
			i += n
		default:
			n, err := wire.Skip(data[i:], tag, "Structs.Cell[key]", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

// _struct_mergeExternalPairInt32String merges the encoding in data, which
// starts at offset off of slab, into the external.Pair[int32, string] that m
// points at, as MergeKanon does. The decode enters depth levels below m at
// most.
func _struct_mergeExternalPairInt32String(m *external.Pair[int32, string], data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "external.Pair[int32, string]", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Varint {
				return wire.FormatError(tag, wire.Varint, "external.Pair[int32, string].Key", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, "external.Pair[int32, string].Key", 1, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int32(s)) {
				return wire.RangeError(s, "int32", "external.Pair[int32, string].Key", 1, off+i)
			}
			m.Key = int32(s)
			i += n
		case 2:
			if tag != 2<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "external.Pair[int32, string].Val", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "external.Pair[int32, string].Val", 2, off+i)
			}
			i += n
			m.Val = slab[off+i : off+i+int(l)]
			i += int(l)
		default:
			n, err := wire.Skip(data[i:], tag, "external.Pair[int32, string]", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

// _struct_fieldsLink decodes the fields in data into m for the decode and the
// merge of Link. The first occurrence of a tracked field whose bit in seen is
// clear decodes into the memory of the field, and every other occurrence
// merges. _struct_fieldsLink returns seen with the bits of the tracked fields
// that data contains.
func _struct_fieldsLink(m *Link, data []byte, slab string, off, depth int, seen [1]uint64) ([1]uint64, error) {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return seen, wire.ReadError(n, "Link", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Varint {
				return seen, wire.FormatError(tag, wire.Varint, "Link.N", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Link.N", 1, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int32(s)) {
				return seen, wire.RangeError(s, "int32", "Link.N", 1, off+i)
			}
			m.N = int32(s)
			i += n
		case 2:
			if tag != 2<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Link.Next", off+at)
			}
			if m.Next == nil {
				m.Next = new(Link)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Link.Next", 2, off+i)
			}
			i += n
			if depth < 2 {
				return seen, wire.DepthError("Link", 0, off+i)
			}
			var err error
			if seen[0]&(1<<0) == 0 {
				seen[0] |= 1 << 0
				err = _struct_readLink(m.Next, data[i:i+int(l)], slab, off+i, depth-2)
			} else {
				err = _struct_mergeLink(m.Next, data[i:i+int(l)], slab, off+i, depth-2)
			}
			if err != nil {
				return seen, err
			}
			i += int(l)
		default:
			n, err := wire.Skip(data[i:], tag, "Link", 0, off+at)
			if err != nil {
				return seen, err
			}
			i += n
		}
	}
	return seen, nil
}

// _struct_mergePadded merges the encoding in data, which starts at offset off
// of slab, into the Padded that m points at, as MergeKanon does. The decode
// enters depth levels below m at most.
func _struct_mergePadded(m *Padded, data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "Padded", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Varint {
				return wire.FormatError(tag, wire.Varint, "Padded.N", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, "Padded.N", 1, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int32(s)) {
				return wire.RangeError(s, "int32", "Padded.N", 1, off+i)
			}
			m.N = int32(s)
			i += n
		case 2:
			if tag != 2<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Padded.Pad", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n > 0 && l != 0 {
				return wire.LengthError(l, 0, "Padded.Pad", 2, off+i)
			}
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Padded.Pad", 2, off+i)
			}
			i += n
			m.Pad = [0]int32{}
		default:
			n, err := wire.Skip(data[i:], tag, "Padded", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

// _struct_mergeStructsNothingKey merges the encoding in data, which starts at
// offset off of slab, into the Structs.Nothing[key] that m points at, as
// MergeKanon does. The decode enters depth levels below m at most.
func _struct_mergeStructsNothingKey(m *struct{}, data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "Structs.Nothing[key]", 0, off+i)
		}
		i += n
		n, err := wire.Skip(data[i:], tag, "Structs.Nothing[key]", 0, off+at)
		if err != nil {
			return err
		}
		i += n
	}
	return nil
}

// _struct_mergeMute merges the encoding in data, which starts at offset off of
// slab, into the Mute that m points at, as MergeKanon does. The decode enters
// depth levels below m at most.
func _struct_mergeMute(m *Mute, data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "Mute", 0, off+i)
		}
		i += n
		n, err := wire.Skip(data[i:], tag, "Mute", 0, off+at)
		if err != nil {
			return err
		}
		i += n
	}
	return nil
}

// _struct_clonePtrLink returns a pointer to a copy of the value that x, a
// *Link, points at, and nil for a nil x.
func _struct_clonePtrLink(x *Link) *Link {
	if x == nil {
		return nil
	}
	c := new(Link)
	_struct_cloneLink(c, x)
	return c
}

// _struct_mergeLink merges the encoding in data, which starts at offset off of
// slab, into the Link that m points at, as MergeKanon does. The decode enters
// depth levels below m at most.
func _struct_mergeLink(m *Link, data []byte, slab string, off, depth int) error {
	_, err := _struct_fieldsLink(m, data, slab, off, depth, [1]uint64{^uint64(0)})
	return err
}
