// Code generated by kanon. DO NOT EDIT.
// source: record.go

//kanon:numbers Item Name=1 Count=2
//kanon:numbers Record Flag=1 Int8=2 Level=3 Uint16=4 Fixed=5 Float32=6 Float64=7 Complex=8 Wave=9 Text=10 Blob=11 Digest=12 At=13 Item=14 Label=15 Ref=16 ItemPtr=17 Children=18 Token=19 TokenPtr=20 Seal=21

package view

import (
	"io"
	"math"
	"slices"
	"strings"
	"time"

	"go.thesmos.sh/kanon"
	"go.thesmos.sh/kanon/internal/fixture/codec"
	"go.thesmos.sh/kanon/wire"
)

// The file compiles against a runtime that supports version 1 of the generator.
const (
	_ = kanon.EnforceVersion(1 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 1)
)

// The generated types implement kanon.Cloner.
var (
	_ kanon.Cloner[Item]   = (*Item)(nil)
	_ kanon.Cloner[Record] = (*Record)(nil)
)

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Item) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Name != "" {
		n += 1 + wire.SizeBytes(len(m.Name))
	}
	if m.Count != 0 {
		n += 1 + wire.SizeUvarint(uint64(m.Count))
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer.
// The error is always nil.
func (m *Item) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. The error is always nil.
func (m *Item) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if m.Count != 0 {
		i = wire.PutUvarint(buf, i, uint64(m.Count))
		i = wire.PutTag(buf, i, 2<<3|wire.Varint)
	}
	if m.Name != "" {
		i = wire.PutRaw(buf, i, m.Name)
		i = wire.PutUvarint(buf, i, uint64(len(m.Name)))
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. The error
// is always nil.
func (m *Item) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	m.encodeKanon(out)
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. The error is always nil.
func (m *Item) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which copy data once.
func (m *Item) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Item) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Item) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Item
// call it.
func (m *Item) decodeKanon(data []byte, slab string, off, depth int) error {
	m.Name = ""
	m.Count = 0
	return m.mergeKanon(data, slab, off, depth)
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Item
// call it.
func (m *Item) mergeKanon(data []byte, slab string, off, depth int) error {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, "Item", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Bytes {
				return wire.FormatError(tag, wire.Bytes, "Item.Name", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return wire.ReadError(n, "Item.Name", 1, off+i)
			}
			i += n
			m.Name = slab[off+i : off+i+int(l)]
			i += int(l)
		case 2:
			if tag != 2<<3|wire.Varint {
				return wire.FormatError(tag, wire.Varint, "Item.Count", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return wire.ReadError(n, "Item.Count", 2, off+i)
			}
			if u != uint64(uint32(u)) {
				return wire.RangeError(u, "uint32", "Item.Count", 2, off+i)
			}
			m.Count = uint32(u)
			i += n
		default:
			n, err := wire.Skip(data[i:], tag, "Item", 0, off+at)
			if err != nil {
				return err
			}
			i += n
		}
	}
	return nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded data stays
// reachable through m.
func (m *Item) Reset() {
	if m == nil {
		return
	}
	m.Name = ""
	m.Count = 0
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Item) CloneKanon() *Item {
	if m == nil {
		return nil
	}
	c := new(Item)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Item call it.
func (m *Item) cloneKanon(c *Item) {
	c.Name = strings.Clone(m.Name)
	c.Count = m.Count
}

// ItemView is the encoding of a Item. Each method reads one field by scanning
// the encoding, without decoding the rest, and returns the zero value when the
// encoding has no such field, and the last value when it has several. A method
// of a struct fails with kanon.ErrRepeatedView for a second occurrence instead,
// since a decode merges the occurrences. The bytes that a method returns for a
// string, a byte slice and a struct alias the view. A value of a type that
// encodes itself decodes with the method of its type, and the offsets of the
// errors of a method are offsets in the view.
type ItemView []byte

// Name returns the value of the field Name of the encoding in v.
func (v ItemView) Name() ([]byte, error) {
	i, err := wire.Find(v, 1<<3|wire.Bytes, "Item.Name")
	if err != nil || i < 0 {
		return nil, err
	}
	l, n := wire.Uvarint(v[i:])
	return []byte(v[i+n : i+n+int(l)]), nil
}

// Count returns the value of the field Count of the encoding in v.
func (v ItemView) Count() (uint32, error) {
	i, err := wire.Find(v, 2<<3|wire.Varint, "Item.Count")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uvarint(v[i:])
	if u != uint64(uint32(u)) {
		return 0, wire.RangeError(u, "uint32", "Item.Count", 2, i)
	}
	return uint32(u), nil
}

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Record) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Flag {
		n += 2
	}
	if m.Int8 != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.Int8)))
	}
	if m.Level != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.Level)))
	}
	if m.Uint16 != 0 {
		n += 1 + wire.SizeUvarint(uint64(m.Uint16))
	}
	if m.Fixed != 0 {
		n += 9
	}
	if math.Float32bits(m.Float32) != 0 {
		n += 5
	}
	if math.Float64bits(m.Float64) != 0 {
		n += 9
	}
	if math.Float32bits(real(m.Complex))|math.Float32bits(imag(m.Complex)) != 0 {
		n += 9
	}
	if math.Float64bits(real(m.Wave))|math.Float64bits(imag(m.Wave)) != 0 {
		n += 18
	}
	if m.Text != "" {
		n += 1 + wire.SizeBytes(len(m.Text))
	}
	if len(m.Blob) > 0 {
		n += 1 + wire.SizeBytes(len(m.Blob))
	}
	if m.Digest != ([8]byte{}) {
		n += 10
	}
	if !m.At.IsZero() || m.At.Location() != time.UTC {
		n += 1 + wire.SizeBytes(wire.SizeTime(m.At))
	}
	if s := m.Item.SizeKanon(); s > 0 {
		n += 1 + wire.SizeBytes(s)
	}
	if s := m.Label.SizeKanon(); s > 0 {
		n += 1 + wire.SizeBytes(s)
	}
	if m.Ref != nil {
		n += 2 + wire.SizeUvarint(wire.Zigzag(int64(*m.Ref)))
	}
	if m.ItemPtr != nil {
		n += 2 + wire.SizeBytes(m.ItemPtr.SizeKanon())
	}
	if len(m.Children) > 0 {
		n += 2 + wire.SizeBytes(_record_sizeSliceInt32(m.Children))
	}
	if m.Token != 0 {
		n += 2 + wire.SizeBytes(_record_sizeCodecToken(&m.Token))
	}
	if m.TokenPtr != nil {
		n += 2 + wire.SizeBytes(_record_sizeCodecToken(m.TokenPtr))
	}
	if m.Seal != (codec.Seal{}) {
		n += 2 + wire.SizeBytes(_record_sizeCodecSeal(&m.Seal))
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer. It
// fails when the value of a field fails to encode: a type that encodes itself
// returns an error, ValidateKanon of a type rejects a value, an interface
// stores a type that the tag option types of its field does not list, or a map
// has a key with a NaN component or two keys of one projection.
func (m *Record) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. It fails when the value of a field
// fails to encode: a type that encodes itself returns an error, ValidateKanon
// of a type rejects a value, an interface stores a type that the tag option
// types of its field does not list, or a map has a key with a NaN component or
// two keys of one projection.
func (m *Record) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if m.Seal != (codec.Seal{}) {
		w, err := _record_putCodecSeal(buf[:i], &m.Seal, "Record.Seal", 21)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
		i = wire.PutTag(buf, i, 21<<3|wire.Bytes)
	}
	if m.TokenPtr != nil {
		w, err := _record_putCodecToken(buf[:i], m.TokenPtr, "Record.TokenPtr", 20)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
		i = wire.PutTag(buf, i, 20<<3|wire.Bytes)
	}
	if m.Token != 0 {
		w, err := _record_putCodecToken(buf[:i], &m.Token, "Record.Token", 19)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
		i = wire.PutTag(buf, i, 19<<3|wire.Bytes)
	}
	if len(m.Children) > 0 {
		i -= _record_putSliceInt32(buf[:i], m.Children)
		i = wire.PutTag(buf, i, 18<<3|wire.Bytes)
	}
	if m.ItemPtr != nil {
		w, _ := m.ItemPtr.encodeKanon(buf[:i])
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
		i = wire.PutTag(buf, i, 17<<3|wire.Bytes)
	}
	if m.Ref != nil {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(*m.Ref)))
		i = wire.PutTag(buf, i, 16<<3|wire.Varint)
	}
	if w, err := m.Label.EncodeKanon(buf[:i]); err != nil {
		return 0, err
	} else if w > 0 {
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
		i = wire.PutTag(buf, i, 15<<3|wire.Bytes)
	}
	if w, _ := m.Item.encodeKanon(buf[:i]); w > 0 {
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
		i = wire.PutTag(buf, i, 14<<3|wire.Bytes)
	}
	if !m.At.IsZero() || m.At.Location() != time.UTC {
		end := i
		i = wire.PutTime(buf, i, m.At)
		i = wire.PutUvarint(buf, i, uint64(end-i))
		i = wire.PutTag(buf, i, 13<<3|wire.Bytes)
	}
	if m.Digest != ([8]byte{}) {
		i = wire.PutRaw(buf, i, m.Digest[:])
		i = wire.PutUvarint(buf, i, uint64(len(m.Digest)))
		i = wire.PutTag(buf, i, 12<<3|wire.Bytes)
	}
	if len(m.Blob) > 0 {
		i = wire.PutRaw(buf, i, m.Blob)
		i = wire.PutUvarint(buf, i, uint64(len(m.Blob)))
		i = wire.PutTag(buf, i, 11<<3|wire.Bytes)
	}
	if m.Text != "" {
		i = wire.PutRaw(buf, i, m.Text)
		i = wire.PutUvarint(buf, i, uint64(len(m.Text)))
		i = wire.PutTag(buf, i, 10<<3|wire.Bytes)
	}
	if math.Float64bits(real(m.Wave))|math.Float64bits(imag(m.Wave)) != 0 {
		i = wire.PutUint64(buf, i, math.Float64bits(imag(m.Wave)))
		i = wire.PutUint64(buf, i, math.Float64bits(real(m.Wave)))
		i = wire.PutUvarint(buf, i, 16)
		i = wire.PutTag(buf, i, 9<<3|wire.Bytes)
	}
	if math.Float32bits(real(m.Complex))|math.Float32bits(imag(m.Complex)) != 0 {
		i = wire.PutUint32(buf, i, math.Float32bits(imag(m.Complex)))
		i = wire.PutUint32(buf, i, math.Float32bits(real(m.Complex)))
		i = wire.PutTag(buf, i, 8<<3|wire.Fixed64)
	}
	if math.Float64bits(m.Float64) != 0 {
		i = wire.PutUint64(buf, i, math.Float64bits(m.Float64))
		i = wire.PutTag(buf, i, 7<<3|wire.Fixed64)
	}
	if math.Float32bits(m.Float32) != 0 {
		i = wire.PutUint32(buf, i, math.Float32bits(m.Float32))
		i = wire.PutTag(buf, i, 6<<3|wire.Fixed32)
	}
	if m.Fixed != 0 {
		i = wire.PutUint64(buf, i, uint64(m.Fixed))
		i = wire.PutTag(buf, i, 5<<3|wire.Fixed64)
	}
	if m.Uint16 != 0 {
		i = wire.PutUvarint(buf, i, uint64(m.Uint16))
		i = wire.PutTag(buf, i, 4<<3|wire.Varint)
	}
	if m.Level != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.Level)))
		i = wire.PutTag(buf, i, 3<<3|wire.Varint)
	}
	if m.Int8 != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.Int8)))
		i = wire.PutTag(buf, i, 2<<3|wire.Varint)
	}
	if m.Flag {
		i = wire.PutBool(buf, i, m.Flag)
		i = wire.PutTag(buf, i, 1<<3|wire.Varint)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. It fails
// when the value of a field fails to encode: a type that encodes itself returns
// an error, ValidateKanon of a type rejects a value, an interface stores a type
// that the tag option types of its field does not list, or a map has a key with
// a NaN component or two keys of one projection.
func (m *Record) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	if _, err := m.encodeKanon(out); err != nil {
		return b, err
	}
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. It fails when the value of a field fails to encode: a type that
// encodes itself returns an error, ValidateKanon of a type rejects a value, an
// interface stores a type that the tag option types of its field does not list,
// or a map has a key with a NaN component or two keys of one projection.
func (m *Record) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which copy data once.
func (m *Record) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Record) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Record) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Record
// call it.
func (m *Record) decodeKanon(data []byte, slab string, off, depth int) error {
	m.Flag = false
	m.Int8 = 0
	m.Level = 0
	m.Uint16 = 0
	m.Fixed = 0
	m.Float32 = 0
	m.Float64 = 0
	m.Complex = 0
	m.Wave = 0
	m.Text = ""
	m.Blob = m.Blob[:0]
	m.Digest = [8]byte{}
	m.At = time.Time{}
	m.Children = m.Children[:0]
	m.Token = 0
	m.Seal = codec.Seal{}
	seen, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{})
	if seen[0]&(1<<0) == 0 {
		m.Item.Reset()
	}
	if seen[0]&(1<<1) == 0 {
		m.Label.Reset()
	}
	if seen[0]&(1<<2) == 0 {
		m.Ref = nil
	}
	if seen[0]&(1<<3) == 0 {
		m.ItemPtr = nil
	}
	if seen[0]&(1<<4) == 0 {
		m.TokenPtr = nil
	}
	return err
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Record
// call it.
func (m *Record) mergeKanon(data []byte, slab string, off, depth int) error {
	_, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{^uint64(0)})
	return err
}

// fieldsKanon decodes the fields in data into m for decodeKanon and mergeKanon.
// The first occurrence of a tracked field whose bit in seen is clear decodes
// into the memory of the field, and every other occurrence merges. fieldsKanon
// returns seen with the bits of the tracked fields that data contains.
func (m *Record) fieldsKanon(data []byte, slab string, off, depth int, seen [1]uint64) ([1]uint64, error) {
	for i := 0; i < len(data); {
		at := i
		tag, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return seen, wire.ReadError(n, "Record", 0, off+i)
		}
		i += n
		switch tag >> 3 {
		case 1:
			if tag != 1<<3|wire.Varint {
				return seen, wire.FormatError(tag, wire.Varint, "Record.Flag", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Record.Flag", 1, off+i)
			}
			m.Flag = u != 0
			i += n
		case 2:
			if tag != 2<<3|wire.Varint {
				return seen, wire.FormatError(tag, wire.Varint, "Record.Int8", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Record.Int8", 2, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int8(s)) {
				return seen, wire.RangeError(s, "int8", "Record.Int8", 2, off+i)
			}
			m.Int8 = int8(s)
			i += n
		case 3:
			if tag != 3<<3|wire.Varint {
				return seen, wire.FormatError(tag, wire.Varint, "Record.Level", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Record.Level", 3, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int32(s)) {
				return seen, wire.RangeError(s, "int32", "Record.Level", 3, off+i)
			}
			m.Level = Level(s)
			i += n
		case 4:
			if tag != 4<<3|wire.Varint {
				return seen, wire.FormatError(tag, wire.Varint, "Record.Uint16", off+at)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Record.Uint16", 4, off+i)
			}
			if u != uint64(uint16(u)) {
				return seen, wire.RangeError(u, "uint16", "Record.Uint16", 4, off+i)
			}
			m.Uint16 = uint16(u)
			i += n
		case 5:
			if tag != 5<<3|wire.Fixed64 {
				return seen, wire.FormatError(tag, wire.Fixed64, "Record.Fixed", off+at)
			}
			u, n := wire.Uint64(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Record.Fixed", 5, off+i)
			}
			m.Fixed = int64(u)
			i += n
		case 6:
			if tag != 6<<3|wire.Fixed32 {
				return seen, wire.FormatError(tag, wire.Fixed32, "Record.Float32", off+at)
			}
			u, n := wire.Uint32(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Record.Float32", 6, off+i)
			}
			m.Float32 = math.Float32frombits(u)
			i += n
		case 7:
			if tag != 7<<3|wire.Fixed64 {
				return seen, wire.FormatError(tag, wire.Fixed64, "Record.Float64", off+at)
			}
			u, n := wire.Uint64(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Record.Float64", 7, off+i)
			}
			m.Float64 = math.Float64frombits(u)
			i += n
		case 8:
			if tag != 8<<3|wire.Fixed64 {
				return seen, wire.FormatError(tag, wire.Fixed64, "Record.Complex", off+at)
			}
			u, n := wire.Uint64(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Record.Complex", 8, off+i)
			}
			m.Complex = complex(math.Float32frombits(uint32(u)), math.Float32frombits(uint32(u>>32)))
			i += n
		case 9:
			if tag != 9<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Record.Wave", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n > 0 && l != 16 {
				return seen, wire.LengthError(l, 16, "Record.Wave", 9, off+i)
			}
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Record.Wave", 9, off+i)
			}
			i += n
			re, _ := wire.Uint64(data[i:])
			im, _ := wire.Uint64(data[i+8:])
			m.Wave = complex(math.Float64frombits(re), math.Float64frombits(im))
			i += 16
		case 10:
			if tag != 10<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Record.Text", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Record.Text", 10, off+i)
			}
			i += n
			m.Text = slab[off+i : off+i+int(l)]
			i += int(l)
		case 11:
			if tag != 11<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Record.Blob", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Record.Blob", 11, off+i)
			}
			i += n
			m.Blob = append(m.Blob[:0], data[i:i+int(l)]...)
			i += int(l)
		case 12:
			if tag != 12<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Record.Digest", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n > 0 && l != 8 {
				return seen, wire.LengthError(l, 8, "Record.Digest", 12, off+i)
			}
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Record.Digest", 12, off+i)
			}
			i += n
			i += copy(m.Digest[:], data[i:])
		case 13:
			if tag != 13<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Record.At", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Record.At", 13, off+i)
			}
			i += n
			t, err := wire.Time(data[i:i+int(l)], "Record.At", 13, off+i)
			if err != nil {
				return seen, err
			}
			m.At = t
			i += int(l)
		case 14:
			if tag != 14<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Record.Item", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Record.Item", 14, off+i)
			}
			i += n
			if depth < 1 {
				return seen, wire.DepthError("Item", 0, off+i)
			}
			var err error
			if seen[0]&(1<<0) == 0 {
				seen[0] |= 1 << 0
				err = m.Item.decodeKanon(data[i:i+int(l)], slab, off+i, depth-1)
			} else {
				err = m.Item.mergeKanon(data[i:i+int(l)], slab, off+i, depth-1)
			}
			if err != nil {
				return seen, err
			}
			i += int(l)
		case 15:
			if tag != 15<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Record.Label", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Record.Label", 15, off+i)
			}
			i += n
			if depth < 1 {
				return seen, wire.DepthError("external.Label", 0, off+i)
			}
			var err error
			if seen[0]&(1<<1) == 0 {
				seen[0] |= 1 << 1
				err = m.Label.DecodeKanon(data[i:i+int(l)], wire.Nested(slab, off+i, depth-1))
			} else {
				err = m.Label.MergeKanon(data[i:i+int(l)], wire.Nested(slab, off+i, depth-1))
			}
			if err != nil {
				return seen, err
			}
			i += int(l)
		case 16:
			if tag != 16<<3|wire.Varint {
				return seen, wire.FormatError(tag, wire.Varint, "Record.Ref", off+at)
			}
			if depth < 1 {
				return seen, wire.DepthError("Record.Ref", 16, off+i)
			}
			if m.Ref == nil {
				m.Ref = new(int32)
			}
			u, n := wire.Uvarint(data[i:])
			if n <= 0 {
				return seen, wire.ReadError(n, "Record.Ref", 16, off+i)
			}
			s := wire.Unzigzag(u)
			if s != int64(int32(s)) {
				return seen, wire.RangeError(s, "int32", "Record.Ref", 16, off+i)
			}
			*m.Ref = int32(s)
			i += n
			seen[0] |= 1 << 2
		case 17:
			if tag != 17<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Record.ItemPtr", off+at)
			}
			if m.ItemPtr == nil {
				m.ItemPtr = new(Item)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Record.ItemPtr", 17, off+i)
			}
			i += n
			if depth < 2 {
				return seen, wire.DepthError("Item", 0, off+i)
			}
			var err error
			if seen[0]&(1<<3) == 0 {
				seen[0] |= 1 << 3
				err = m.ItemPtr.decodeKanon(data[i:i+int(l)], slab, off+i, depth-2)
			} else {
				err = m.ItemPtr.mergeKanon(data[i:i+int(l)], slab, off+i, depth-2)
			}
			if err != nil {
				return seen, err
			}
			i += int(l)
		case 18:
			if tag != 18<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Record.Children", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Record.Children", 18, off+i)
			}
			i += n
			if err := _record_readSliceInt32(&m.Children, data[i:i+int(l)], slab, off+i, depth-1, "Record.Children", 18); err != nil {
				return seen, err
			}
			i += int(l)
		case 19:
			if tag != 19<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Record.Token", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Record.Token", 19, off+i)
			}
			i += n
			m.Token = 0
			if err := m.Token.UnmarshalBinary(data[i : i+int(l)]); err != nil {
				return seen, wire.UnmarshalError(err, "Record.Token", 19, off+i)
			}
			i += int(l)
		case 20:
			if tag != 20<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Record.TokenPtr", off+at)
			}
			if depth < 1 {
				return seen, wire.DepthError("Record.TokenPtr", 20, off+i)
			}
			if m.TokenPtr == nil {
				m.TokenPtr = new(codec.Token)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Record.TokenPtr", 20, off+i)
			}
			i += n
			*m.TokenPtr = 0
			if err := m.TokenPtr.UnmarshalBinary(data[i : i+int(l)]); err != nil {
				return seen, wire.UnmarshalError(err, "Record.TokenPtr", 20, off+i)
			}
			i += int(l)
			seen[0] |= 1 << 4
		case 21:
			if tag != 21<<3|wire.Bytes {
				return seen, wire.FormatError(tag, wire.Bytes, "Record.Seal", off+at)
			}
			l, n := wire.Uvarint(data[i:])
			if n <= 0 || uint64(len(data)-i-n) < l {
				return seen, wire.ReadError(n, "Record.Seal", 21, off+i)
			}
			i += n
			m.Seal = codec.Seal{}
			if err := m.Seal.UnmarshalBinary(data[i : i+int(l)]); err != nil {
				return seen, wire.UnmarshalError(err, "Record.Seal", 21, off+i)
			}
			i += int(l)
		default:
			n, err := wire.Skip(data[i:], tag, "Record", 0, off+at)
			if err != nil {
				return seen, err
			}
			i += n
		}
	}
	return seen, nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded data stays
// reachable through m.
func (m *Record) Reset() {
	if m == nil {
		return
	}
	m.Flag = false
	m.Int8 = 0
	m.Level = 0
	m.Uint16 = 0
	m.Fixed = 0
	m.Float32 = 0
	m.Float64 = 0
	m.Complex = 0
	m.Wave = 0
	m.Text = ""
	clear(m.Blob[:cap(m.Blob)])
	m.Blob = m.Blob[:0]
	m.Digest = [8]byte{}
	m.At = time.Time{}
	m.Item.Reset()
	m.Label.Reset()
	m.Ref = nil
	m.ItemPtr = nil
	clear(m.Children[:cap(m.Children)])
	m.Children = m.Children[:0]
	m.Token = 0
	m.TokenPtr = nil
	m.Seal = codec.Seal{}
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Record) CloneKanon() *Record {
	if m == nil {
		return nil
	}
	c := new(Record)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Record call it.
func (m *Record) cloneKanon(c *Record) {
	c.Flag = m.Flag
	c.Int8 = m.Int8
	c.Level = m.Level
	c.Uint16 = m.Uint16
	c.Fixed = m.Fixed
	c.Float32 = m.Float32
	c.Float64 = m.Float64
	c.Complex = m.Complex
	c.Wave = m.Wave
	c.Text = strings.Clone(m.Text)
	c.Blob = slices.Clone(m.Blob)
	c.Digest = m.Digest
	c.At = m.At
	m.Item.cloneKanon(&c.Item)
	c.Label = *m.Label.CloneKanon()
	c.Ref = _record_clonePtrInt32(m.Ref)
	c.ItemPtr = _record_clonePtrItem(m.ItemPtr)
	c.Children = slices.Clone(m.Children)
	c.Token = m.Token
	c.TokenPtr = _record_clonePtrCodecToken(m.TokenPtr)
	c.Seal = m.Seal
}

// RecordView is the encoding of a Record. Each method reads one field by
// scanning the encoding, without decoding the rest, and returns the zero value
// when the encoding has no such field, and the last value when it has several.
// A method of a struct fails with kanon.ErrRepeatedView for a second occurrence
// instead, since a decode merges the occurrences. The bytes that a method
// returns for a string, a byte slice and a struct alias the view. A value of a
// type that encodes itself decodes with the method of its type, and the offsets
// of the errors of a method are offsets in the view.
type RecordView []byte

// Flag returns the value of the field Flag of the encoding in v.
func (v RecordView) Flag() (bool, error) {
	i, err := wire.Find(v, 1<<3|wire.Varint, "Record.Flag")
	if err != nil || i < 0 {
		return false, err
	}
	u, _ := wire.Uvarint(v[i:])
	return u != 0, nil
}

// Int8 returns the value of the field Int8 of the encoding in v.
func (v RecordView) Int8() (int8, error) {
	i, err := wire.Find(v, 2<<3|wire.Varint, "Record.Int8")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uvarint(v[i:])
	s := wire.Unzigzag(u)
	if s != int64(int8(s)) {
		return 0, wire.RangeError(s, "int8", "Record.Int8", 2, i)
	}
	return int8(s), nil
}

// Level returns the value of the field Level of the encoding in v.
func (v RecordView) Level() (Level, error) {
	i, err := wire.Find(v, 3<<3|wire.Varint, "Record.Level")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uvarint(v[i:])
	s := wire.Unzigzag(u)
	if s != int64(int32(s)) {
		return 0, wire.RangeError(s, "int32", "Record.Level", 3, i)
	}
	return Level(s), nil
}

// Uint16 returns the value of the field Uint16 of the encoding in v.
func (v RecordView) Uint16() (uint16, error) {
	i, err := wire.Find(v, 4<<3|wire.Varint, "Record.Uint16")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uvarint(v[i:])
	if u != uint64(uint16(u)) {
		return 0, wire.RangeError(u, "uint16", "Record.Uint16", 4, i)
	}
	return uint16(u), nil
}

// Fixed returns the value of the field Fixed of the encoding in v.
func (v RecordView) Fixed() (int64, error) {
	i, err := wire.Find(v, 5<<3|wire.Fixed64, "Record.Fixed")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uint64(v[i:])
	return int64(u), nil
}

// Float32 returns the value of the field Float32 of the encoding in v.
func (v RecordView) Float32() (float32, error) {
	i, err := wire.Find(v, 6<<3|wire.Fixed32, "Record.Float32")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uint32(v[i:])
	return math.Float32frombits(u), nil
}

// Float64 returns the value of the field Float64 of the encoding in v.
func (v RecordView) Float64() (float64, error) {
	i, err := wire.Find(v, 7<<3|wire.Fixed64, "Record.Float64")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uint64(v[i:])
	return math.Float64frombits(u), nil
}

// Complex returns the value of the field Complex of the encoding in v.
func (v RecordView) Complex() (complex64, error) {
	i, err := wire.Find(v, 8<<3|wire.Fixed64, "Record.Complex")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uint64(v[i:])
	return complex(math.Float32frombits(uint32(u)), math.Float32frombits(uint32(u>>32))), nil
}

// Wave returns the value of the field Wave of the encoding in v.
func (v RecordView) Wave() (complex128, error) {
	i, err := wire.Find(v, 9<<3|wire.Bytes, "Record.Wave")
	if err != nil || i < 0 {
		return 0, err
	}
	l, n := wire.Uvarint(v[i:])
	if l != 16 {
		return 0, wire.LengthError(l, 16, "Record.Wave", 9, i)
	}
	re, _ := wire.Uint64(v[i+n:])
	im, _ := wire.Uint64(v[i+n+8:])
	return complex(math.Float64frombits(re), math.Float64frombits(im)), nil
}

// Text returns the value of the field Text of the encoding in v.
func (v RecordView) Text() ([]byte, error) {
	i, err := wire.Find(v, 10<<3|wire.Bytes, "Record.Text")
	if err != nil || i < 0 {
		return nil, err
	}
	l, n := wire.Uvarint(v[i:])
	return []byte(v[i+n : i+n+int(l)]), nil
}

// Blob returns the value of the field Blob of the encoding in v.
func (v RecordView) Blob() ([]byte, error) {
	i, err := wire.Find(v, 11<<3|wire.Bytes, "Record.Blob")
	if err != nil || i < 0 {
		return nil, err
	}
	l, n := wire.Uvarint(v[i:])
	return []byte(v[i+n : i+n+int(l)]), nil
}

// Digest returns the value of the field Digest of the encoding in v.
func (v RecordView) Digest() ([8]byte, error) {
	i, err := wire.Find(v, 12<<3|wire.Bytes, "Record.Digest")
	if err != nil || i < 0 {
		return [8]byte{}, err
	}
	l, n := wire.Uvarint(v[i:])
	if l != 8 {
		return [8]byte{}, wire.LengthError(l, 8, "Record.Digest", 12, i)
	}
	var x [8]byte
	copy(x[:], v[i+n:])
	return x, nil
}

// At returns the value of the field At of the encoding in v.
func (v RecordView) At() (time.Time, error) {
	i, err := wire.Find(v, 13<<3|wire.Bytes, "Record.At")
	if err != nil || i < 0 {
		return time.Time{}, err
	}
	l, n := wire.Uvarint(v[i:])
	return wire.Time(v[i+n:i+n+int(l)], "Record.At", 13, i+n)
}

// Item returns the value of the field Item of the encoding in v.
func (v RecordView) Item() (ItemView, error) {
	i, err := wire.FindOne(v, 14<<3|wire.Bytes, "Record.Item")
	if err != nil || i < 0 {
		return nil, err
	}
	l, n := wire.Uvarint(v[i:])
	return ItemView(v[i+n : i+n+int(l)]), nil
}

// Label returns the value of the field Label of the encoding in v.
func (v RecordView) Label() ([]byte, error) {
	i, err := wire.FindOne(v, 15<<3|wire.Bytes, "Record.Label")
	if err != nil || i < 0 {
		return nil, err
	}
	l, n := wire.Uvarint(v[i:])
	return []byte(v[i+n : i+n+int(l)]), nil
}

// Ref returns the value of the field Ref of the encoding in v.
func (v RecordView) Ref() (int32, error) {
	i, err := wire.Find(v, 16<<3|wire.Varint, "Record.Ref")
	if err != nil || i < 0 {
		return 0, err
	}
	u, _ := wire.Uvarint(v[i:])
	s := wire.Unzigzag(u)
	if s != int64(int32(s)) {
		return 0, wire.RangeError(s, "int32", "Record.Ref", 16, i)
	}
	return int32(s), nil
}

// ItemPtr returns the value of the field ItemPtr of the encoding in v.
func (v RecordView) ItemPtr() (ItemView, error) {
	i, err := wire.FindOne(v, 17<<3|wire.Bytes, "Record.ItemPtr")
	if err != nil || i < 0 {
		return nil, err
	}
	l, n := wire.Uvarint(v[i:])
	return ItemView(v[i+n : i+n+int(l)]), nil
}

// Token returns the value of the field Token of the encoding in v.
func (v RecordView) Token() (codec.Token, error) {
	i, err := wire.Find(v, 19<<3|wire.Bytes, "Record.Token")
	if err != nil || i < 0 {
		return 0, err
	}
	l, n := wire.Uvarint(v[i:])
	var x codec.Token
	if err := x.UnmarshalBinary(v[i+n : i+n+int(l)]); err != nil {
		return 0, wire.UnmarshalError(err, "Record.Token", 19, i+n)
	}
	return x, nil
}

// TokenPtr returns the value of the field TokenPtr of the encoding in v.
func (v RecordView) TokenPtr() (codec.Token, error) {
	i, err := wire.Find(v, 20<<3|wire.Bytes, "Record.TokenPtr")
	if err != nil || i < 0 {
		return 0, err
	}
	l, n := wire.Uvarint(v[i:])
	var x codec.Token
	if err := x.UnmarshalBinary(v[i+n : i+n+int(l)]); err != nil {
		return 0, wire.UnmarshalError(err, "Record.TokenPtr", 20, i+n)
	}
	return x, nil
}

// Seal returns the value of the field Seal of the encoding in v.
func (v RecordView) Seal() (codec.Seal, error) {
	i, err := wire.Find(v, 21<<3|wire.Bytes, "Record.Seal")
	if err != nil || i < 0 {
		return codec.Seal{}, err
	}
	l, n := wire.Uvarint(v[i:])
	var x codec.Seal
	if err := x.UnmarshalBinary(v[i+n : i+n+int(l)]); err != nil {
		return codec.Seal{}, wire.UnmarshalError(err, "Record.Seal", 21, i+n)
	}
	return x, nil
}

// _record_sizeSliceInt32 returns the length of the encoding of the elements of
// x, a []int32.
func _record_sizeSliceInt32(x []int32) int {
	n := 0
	for k := range x {
		n += wire.SizeUvarint(wire.Zigzag(int64(x[k])))
	}
	return n
}

// _record_sizeCodecToken returns the length of the encoding of the codec.Token
// that x points at, and 1 when x fails to encode itself, so that the value is
// present and its encode reports the failure.
func _record_sizeCodecToken(x *codec.Token) int {
	var scratch [128]byte
	enc, err := x.AppendBinary(scratch[:0])
	if err != nil {
		return 1
	}
	return len(enc)
}

// _record_sizeCodecSeal returns the length of the encoding of the codec.Seal
// that x points at, and 1 when x fails to encode itself, so that the value is
// present and its encode reports the failure.
func _record_sizeCodecSeal(x *codec.Seal) int {
	var scratch [128]byte
	enc, err := x.AppendBinary(scratch[:0])
	if err != nil {
		return 1
	}
	return len(enc)
}

// _record_putCodecSeal writes the encoding of the codec.Seal that x points at
// into the end of buf, which has room for it, and returns its length. It fails
// when x fails to encode itself.
func _record_putCodecSeal(buf []byte, x *codec.Seal, loc string, num int) (int, error) {
	var scratch [128]byte
	enc, err := x.AppendBinary(scratch[:0])
	if err != nil {
		return 0, wire.MarshalError(err, loc, num)
	}
	return copy(buf[len(buf)-len(enc):], enc), nil
}

// _record_putCodecToken writes the encoding of the codec.Token that x points at
// into the end of buf, which has room for it, and returns its length. It fails
// when x fails to encode itself.
func _record_putCodecToken(buf []byte, x *codec.Token, loc string, num int) (int, error) {
	var scratch [128]byte
	enc, err := x.AppendBinary(scratch[:0])
	if err != nil {
		return 0, wire.MarshalError(err, loc, num)
	}
	return copy(buf[len(buf)-len(enc):], enc), nil
}

// _record_putSliceInt32 writes the encoding of x, a []int32, into the end of
// buf, which has room for it, and returns its length.
func _record_putSliceInt32(buf []byte, x []int32) int {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(x[k])))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i
}

// _record_readSliceInt32 appends the elements that data encodes, a []int32
// without its length, to *dst. data starts at offset off of slab, and the
// decode enters depth levels below the value at most. loc and num locate the
// field in errors.
func _record_readSliceInt32(dst *[]int32, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]int32, 0, wire.CountVarints(data))
	}
	for i := 0; i < len(data); {
		x = append(x, 0)
		last := len(x) - 1
		u, n := wire.Uvarint(data[i:])
		if n <= 0 {
			return wire.ReadError(n, loc, num, off+i)
		}
		s := wire.Unzigzag(u)
		if s != int64(int32(s)) {
			return wire.RangeError(s, "int32", loc, num, off+i)
		}
		x[last] = int32(s)
		i += n
	}
	*dst = x
	return nil
}

// _record_clonePtrInt32 returns a pointer to a copy of the value that x, a
// *int32, points at, and nil for a nil x.
func _record_clonePtrInt32(x *int32) *int32 {
	if x == nil {
		return nil
	}
	return new(*x)
}

// _record_clonePtrItem returns a pointer to a copy of the value that x, a
// *Item, points at, and nil for a nil x.
func _record_clonePtrItem(x *Item) *Item {
	if x == nil {
		return nil
	}
	return x.CloneKanon()
}

// _record_clonePtrCodecToken returns a pointer to a copy of the value that x, a
// *codec.Token, points at, and nil for a nil x.
func _record_clonePtrCodecToken(x *codec.Token) *codec.Token {
	if x == nil {
		return nil
	}
	return new(*x)
}
