// Code generated by kanon. DO NOT EDIT.
// source: codec.go

package union

import (
	"testing"

	"go.thesmos.sh/kanon/kanontest"
)

// kanonSpecCodecs describes Codecs to the conformance suite.
var kanonSpecCodecs = kanontest.Spec[Codecs]{
	Fields: []kanontest.Field{
		{Name: "Token", Number: 1, Union: "Kind", Case: CodecKindToken},
		{Name: "Word", Number: 2, Union: "Kind", Case: CodecKindWord},
		{Name: "Stamp", Number: 3, Union: "Kind", Case: CodecKindStamp},
		{Name: "Code", Number: 4, Union: "Kind", Case: CodecKindCode},
	},
}

// TestKanonCodecs runs the conformance suite on Codecs.
func TestKanonCodecs(t *testing.T) {
	kanontest.Run(t, kanonSpecCodecs)
}

// BenchmarkKanonCodecs measures the codec of Codecs.
func BenchmarkKanonCodecs(b *testing.B) {
	kanontest.Bench(b, kanonSpecCodecs)
}

// FuzzKanonCodecs fuzzes the decode of Codecs.
func FuzzKanonCodecs(f *testing.F) {
	kanontest.Fuzz(f, kanonSpecCodecs)
}
